### ISSUE TITLE
Split double-sided PageObjects into two PageObjects

### ISSUE THREAD

**Issue by michaelbeacom** [py-pdf/PyPDF2#100]
Hi,

I have a small issue, and I'm not sure if the software is working as intended or not.

For a given document that is formatted as spreads (i.e. two pages side by side for each page of the document), I want to split the spread into separate pages, so that spread 1 becomes pages 1 & 2, spread 2 becomes pages 3 & 4, etc.

However, it seems that I am not getting separate instances of the page, because the cropBox I am setting for page2 also gets set for page1, and I end up the right side of the spread for pages 1 and 2.

```python
#convert spreads into pages
#python /path/to/spread2pages.py inputfile.pdf outputfile.pdf

import PyPDF2
from sys import argv

script, infile_name, outfile_name = argv

inputStream = file(infile_name, "rb")
inpdf = PyPDF2.PdfFileReader(inputStream)

outpdf = PyPDF2.PdfFileWriter()

#get corner locations
llx,lly = inpdf.getPage(0).cropBox.lowerLeft
urx,ury = inpdf.getPage(0).cropBox.upperRight

for i in xrange(inpdf.getNumPages()):
    #left side
    page1 = inpdf.getPage(i)
    page1.cropBox.lowerLeft = (llx,lly)
    page1.cropBox.upperRight = ((llx+urx)/2,ury)
    outpdf.addPage(page1)
    #right side
    page2 = inpdf.getPage(i) 
    page2.cropBox.lowerLeft = ((llx+urx)/2,lly)
    page2.cropBox.upperRight = (urx,ury)
    outpdf.addPage(page2)

#save ouput
print "saving..."
outputStream = file(outfile_name, "wb")
outpdf.write(outputStream)
inputStream.close()
outputStream.close()
```

This code does what I need, but I am wondering if there is a way to do it with a single PdfFileReader:

```
#convert spreads into pages
#python /path/to/spread2pages.py inputfile.pdf outputfile.pdf

import PyPDF2
from sys import argv

script, infile_name, outfile_name = argv

#there doesn't seem to be a way to get separate instances of the same page
#from a single reader object, so I have to import two reader objects.
inputStream = file(infile_name, "rb")
inpdf = PyPDF2.PdfFileReader(inputStream)
inputStream2 = file(infile_name, "rb")
inpdf2 = PyPDF2.PdfFileReader(inputStream2)

outpdf = PyPDF2.PdfFileWriter()

#get corner locations
llx,lly = inpdf.getPage(0).cropBox.lowerLeft
urx,ury = inpdf.getPage(0).cropBox.upperRight

for i in xrange(inpdf.getNumPages()):
    #left side
    inpdf.getPage(i).cropBox.lowerLeft = (llx,lly)
    inpdf.getPage(i).cropBox.upperRight = ((llx+urx)/2,ury)
    outpdf.addPage(inpdf.getPage(i))
    #right side
    inpdf2.getPage(i).cropBox.lowerLeft = ((llx+urx)/2,lly)
    inpdf2.getPage(i).cropBox.upperRight = (urx,ury)
    outpdf.addPage(inpdf2.getPage(i))

#save output
print "saving..."
outputStream = file(outfile_name, "wb")
outpdf.write(outputStream)
inputStream.close()
inputStream2.close()
outputStream.close()
```

**Comment by belteshassar** [comment]
There is a dirty hack that can be used if you want to duplicate a page and modify the two pages in different ways. You can make a copy of the PageObject. This works for the methods that replace, add or delete children of the PageObject rather than modifying existing ones since shallow copies contain references to the same children as the original. Unfortunately, using deepcopy to also make copies of the children doesn't work (I believe that the duplication of the PdfFileReader object causes some weird conflict).

In the example above, this hack will not work straight out since page1.cropBox.lowerLeft = (llx,lly), and inpdf2.getPage(i).cropBox.lowerLeft = ((llx+urx)/2,lly) modify the same object cropBox. A simple way around this is to replace the entire cropBox object with a new one instead of modifying the properties of the existing one.

**Comment by pmaupin** [comment]
The pdfrw library generally operates at a lower level than PyPDF2, so in a lot of cases, it will take more lines of code than PyPDF2 to perform the same function.  For instance, it doesn't currently parse into the graphics stream, so you have to do that yourself.

But one feature it supports (that I don't think PyPDF2 does) is Form XOBjects.  You can take a PDF page, and turn it into a Form XObject, and then reference it from multiple pages.  This allows a single instance of the PdfReader, and reduces the amount of data in the output file.  I made an example that I believe produces the desired result here:

https://github.com/pmaupin/pdfrw/blob/master/examples/unspread.py

**Comment by mstamy2** [comment]
Thank you for looking in to this. I'll try to incorporate your work into a solution.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by crh878** [comment]
Has any progress been made on this issue? I'm trying to split a single pdf page into a 30 page pdf file and am having difficulties.

**Comment by applecat** [comment]
I have the same issue. We need split PDF's double pages into one paged, but can't copy page.
I have workaround with double PdfFileReader instances:
```
def split_pdf(input_filename, output_filename):
    output = PdfFileWriter()
    input1 = PdfFileReader(open(input_filename, "rb"))
    input2 = PdfFileReader(open(input_filename, "rb"))

    for i in range(0, input1.getNumPages()):
        p = input1.getPage(i)
        (w, h) = p.mediaBox.upperRight
        print (w, h)
        if w <= h:
            output.addPage(p)
        else:
            # Split into two pages
            p.mediaBox.upperRight = (w/2, h)
            output.addPage(p)

            q = input2.getPage(i)
            q.mediaBox.upperLeft = (w/2, h)
            q.mediaBox.upperRight = (w, h)
            output.addPage(q)

    outputStream = open(output_filename, "wb")
    output.write(outputStream)
    outputStream.close()

```

But problem with this solution is that output filesize is 2x bigger than input file size. Seems that double pages still contains all its data, but it's simply hidden.

**Comment by tyll** [comment]
This seems to work with a single reader but still doubles the PDF size:

```python
# copy page to pagecopy:
pagecopy = PyPDF2.pdf.PageObject.createBlankPage(None, page.mediaBox.getWidth(),
                                                 page.mediaBox.getHeight())
pagecopy.mergePage(page)
```

**Comment by suica** [comment]
> This seems to work with a single reader but still doubles the PDF size:
> 
> ```python
> # copy page to pagecopy:
> pagecopy = PyPDF2.pdf.PageObject.createBlankPage(None, page.mediaBox.getWidth(),
>                                                  page.mediaBox.getHeight())
> pagecopy.mergePage(page)
> ```

It works :)
Thank you!

**Comment by niilz** [comment]
@tyll This was exactly what I was looking for.

**Comment by FancyUsername** [comment]
Had the same issue when trying to split the same page twice via cropping. Easy solution: copy.copy(doc.getPage(0))
Just copy the page, e.g. cropping seems to be (shallow) part of the PageObject

**Comment by ohnekopf** [comment]
> Had the same issue when trying to split the same page twice via cropping. Easy solution: copy.copy(doc.getPage(0))
> Just copy the page, e.g. cropping seems to be (shallow) part of the PageObject

That worked for me, thanks

**Comment by MartinThoma** [comment]
One of the hard parts of development is to decide what belongs where. When should a function be added to the library itself and when should it be done just with the library?

In this case, I would say that cropping a PDF is something that PyPDF2 should support. But splitting a double-sided PageObject into two (or 4 / 6 / 8 ...) is a task I see more in the user-space: It shouldn't be done by PyPDF2 directly, but be possible to do it with PyPDF2.

For this reason, I'm closing this issue.
