### ISSUE TITLE
PyPDF breaks drag and drop on Windows

### ISSUE THREAD

**Issue by dtreth** [py-pdf/PyPDF2#1032]
I was trying to create a script to unencrypt and split PDFs where you could drag the PDF onto the script and it would automatically work from there. I couldn't figure it out even though it worked through the command-line. So I made this script:

```
import sys
import tkinter as tk
import PyPDF2

def popupmsg(msg, title) -> None:
    root = tk.Tk()
    root.title(title)
    label = tk.Label(root, text=msg)
    label.pack(side="top", fill="x", pady=10)
    B1 = tk.Button(root, text="Okay", command = root.destroy)
    B1.pack()
    root.mainloop()


popupmsg(__name__, "__name__")
popupmsg(sys.argv, "Input Args")
```

I am using Python 3.10.4 on Windows 21H2 and I have associated all .py* files with the py launcher. If you comment out the `import PyPDF2` line it works as expected but uncomment it and drag and drop just shows a console window for a fraction of a second and nothing gets displayed. I think PyPDF might be clobbering the args? I honestly have no idea I just managed to track down the issue to the import statement.

**Comment by dtreth** [comment]
Mevermind, it's a virtual environment issue... Now I have to figure out how to activate a virtual environment on drag-and-drop... sorry for the noise.

**Comment by MartinThoma** [comment]
No problem - thank you for coming back and closing the issue :heart: 

Good luck with finding the problem!
