### ISSUE TITLE
page1.merge_page(page2, expand=True) doesn't seem to work

### ISSUE THREAD

**Issue by GeoTN** [py-pdf/PyPDF2#1035]
I am trying to merge two PDF page into one page. One thing is, those Pdf are kinda long (3 meters each, so 6 meters in the end)
When I try to merge those two pdf, the second PDF doesn't write past a certain area.

## Code

```python
import PyPDF2 as pdf
from PyPDF2.generic import RectangleObject
from PyPDF2 import PageObject, PdfReader, PdfWriter, Transformation

reader = PdfReader("E036_000_Tralongpdf2.0.pdf")
page = reader.pages[0]

x1, y1, x2, y2 = page.cropbox
op1 = Transformation().translate(tx=0, ty=0)
page.add_transformation(op1)
reader2 = PdfReader("E036_000_Tralongpdf1.0.pdf")
page2 = reader2.pages[0]

x21, y21, x22, y22 = page2.cropbox
assert x21 == 0
assert y21 == 0

op2 = Transformation().translate(tx=0, ty=y22 - 2000)  # ty=y2)
page2.add_transformation(op2)
page3 = PageObject.createBlankPage(reader, width=845, height=19000)
rect = RectangleObject((0.0, 0.0, 845.0, 25000.0))
print(page3.mediabox)
page3.cropbox = rect
page3.merge_page(page2)
page3.merge_page(page)

writer = PdfWriter()
page3.trimBox = rect
print(page3.cropbox)
writer.add_page(page3)
with open("output.pdf", "wb") as fp:
    writer.write(fp)

```

## Environment

PyPDF==2.4.0

**Comment by MartinThoma** [comment]
> Pdf are kinda long (3 meters each, so 6 meters in the end)

Ok :smile: Can you share those?

**Comment by GeoTN** [comment]
Here
[E036_000_Tralongpdf2.0.PDF](https://github.com/py-pdf/PyPDF2/files/9002202/E03
[E036_000_Tralongpdf1.0.PDF](https://github.com/py-pdf/PyPDF2/files/9002206/

E036_000_Tralongpdf1.0.PDF)
6_000_Tralongpdf2.0.PDF)
 [main.txt](https://github.com/py-pdf/PyPDF2/files/9002217/main.txt)

**Comment by MartinThoma** [comment]
Thanks for sharing! It looks to me as if you're merging them as

```
| 1 |
| 2 |
```

The x-axis goes (left-right), the y-axis goes (top-bottom).

**Comment by GeoTN** [comment]
Yep, but even with that, the | 1 | is still missing or partly written...

**Comment by MartinThoma** [comment]
This is an intermediate fix:

```python
from PyPDF2.generic import RectangleObject
from PyPDF2 import PdfReader, PdfWriter, Transformation

# Get the original data
reader = PdfReader("1.pdf")
page1 = reader.pages[0]
print(page1.cropbox)

reader2 = PdfReader("2.pdf")
page2 = reader2.pages[0]

# Merge them into one page
offset = page1.cropbox.right
print(offset)
op = Transformation().translate(tx=offset, ty=0)
page2.add_transformation(op)
cb = page2.cropbox
page2.mediabox = RectangleObject((cb.left + offset, cb.bottom, cb.right + offset, cb.top))
page2.cropbox = RectangleObject((cb.left + offset, cb.bottom, cb.right + offset, cb.top))
page2.trimbox = RectangleObject((cb.left + offset, cb.bottom, cb.right + offset, cb.top))
page2.bleedbox = RectangleObject((cb.left + offset, cb.bottom, cb.right + offset, cb.top))
page2.artbox = RectangleObject((cb.left + offset, cb.bottom, cb.right + offset, cb.top))

page1.merge_page(page2, expand=True)
mb = page1.mediabox
page1.mediabox = RectangleObject((mb.left, mb.bottom, mb.right, mb.top))
page1.cropbox = RectangleObject((mb.left, mb.bottom, mb.right, mb.top))
page1.trimbox = RectangleObject((mb.left, mb.bottom, mb.right , mb.top))
page1.bleedbox = RectangleObject((mb.left, mb.bottom, mb.right, mb.top))
page1.artbox = RectangleObject((mb.left, mb.bottom, mb.right, mb.top))
print(page1.mediabox )

# Write the result back
writer = PdfWriter()
writer.add_page(page1)

with open("output.pdf", "wb") as fp:
    writer.write(fp)
```

**Comment by MartinThoma** [comment]
It's might related to #272 and #879

**Comment by MartinThoma** [comment]
There are two issues in PyPDF2:

1. When doing the transformation, one/multiple of the boxes don't get adjusted
2. When doing the merge with expand=True, one/multiple of the boxes don't get adjusted.

**Comment by GeoTN** [comment]
Ok thanks a lot!
Have a good day.

**Comment by MartinThoma** [comment]
Please leave the issue open, even if the quick-fix works for you. I want the library itself to be correct. At the very least I feel like we need more documentation here, but I'm pretty certain we need to adjust PyPDF2.

**Comment by MartinThoma** [comment]
> 1. When doing the transformation, one/multiple of the boxes don't get adjusted

On 10.07.2022 I've merged https://github.com/py-pdf/PyPDF2/pull/1066 .

Transformations done via the `Transformation` class , e.g

```
>>> from PyPDF2 import Transformation
 >>> op = Transformation().scale(sx=2, sy=3).translate(tx=10, ty=20)
>>> page.add_transformation(op)
```

only affect the content of a page, not the page itself. 

I've just noticed that this is not documented (e.g. in https://pypdf2.readthedocs.io/en/latest/user/cropping-and-transforming.html ). I'll fix that.
