### ISSUE TITLE
PdfReadError: File has not been decrypted

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/PyPDF2#1088]
I was trying to read metadata from a PDF that is not encrypted. The file **is encrypted** with an empty password:

```
$ pdfinfo example.pdf

...
Encrypted:      yes (print:yes copy:no change:no addNotes:no algorithm:RC4)
...
```

## Environment

```bash
$ python -m platform
Linux-5.4.0-121-generic-x86_64-with-glibc2.31

# Seen first (inclusive)
$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.4.2

# Seen last (inclusive)
$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.8.0
```

## Code + PDF

The PDF: [`pdf/9bc3765eb6426bb34139d419a6e1f79e.pdf`](https://corpora.tika.apache.org/base/docs/govdocs1/941/941536.pdf)

```pycon
>>> from PyPDF2 import PdfReader
>>> reader = PdfReader("pdf/9bc3765eb6426bb34139d419a6e1f79e.pdf")

>>> len(reader.pages)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 1469, in __len__
    return self.length_function()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 389, in _get_num_pages
    return self.trailer[TK.ROOT]["/Pages"]["/Count"]  # type: ignore
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 680, in __getitem__
    return dict.__getitem__(self, key).get_object()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 252, in get_object
    obj = self.pdf.get_object(self)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 1090, in get_object
    raise PdfReadError("File has not been decrypted")
PyPDF2.errors.PdfReadError: File has not been decrypted

>>> reader.metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 319, in metadata
    obj = self.trailer[TK.INFO]
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 680, in __getitem__
    return dict.__getitem__(self, key).get_object()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 252, in get_object
    obj = self.pdf.get_object(self)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 1090, in get_object
    raise PdfReadError("File has not been decrypted")
PyPDF2.errors.PdfReadError: File has not been decrypted

```

**Comment by MartinThoma** [comment]
Related to #416 and #991

**Comment by MartinThoma** [comment]
Another example: `https://corpora.tika.apache.org/base/docs/govdocs1/942/942303.pdf`

**Comment by MatthiasValvekens** [comment]
That file is encrypted, but with an empty user password :) (AKA "mild obfuscation" rather than encryption, but hey). Seems to be 128-bit RC4.

I don't remember offhand how PyPDF2 handles this case, but it could be that a `.decrypt('')` call on the reader is all that is needed.

**Comment by MartinThoma** [comment]
@MatthiasValvekens When I specify `PdfReader(stream, password="")`, I get `PyPDF2.errors.PdfReadError: Wrong password`.

**Comment by MartinThoma** [comment]
Seeing that basically every PDF viewer automatically tries the empty password, I think PyPDF2 should do the same. From a users perspective, this is very confusing.

**Comment by pubpub-zz** [comment]
> Seeing that basically every PDF viewer automatically tries the empty password, I think PyPDF2 should do the same. From a users perspective, this is very confusing.

I agree with your proposal, however, there definitively seems to be a problem with the decoder : I did some test with pdfminer.six and the empty password do work

**Comment by xilopaint** [comment]
> Seeing that basically every PDF viewer automatically tries the empty password, I think PyPDF2 should do the same.

Hope to see this implemented soon!
