### ISSUE TITLE
PdfFileMerger deprecation warning tells to use "PdfMerge" instead of "PdfMerger"

### ISSUE THREAD

**Issue by T4m** [py-pdf/PyPDF2#1106]
After a dependencies updates, I got the following warning in the console :

`PendingDeprecationWarning: PdfFileMerger is deprecated and will be removed in PyPDF2 3.0.0. Use PdfMerge instead.`

"PdfMerge" actually doesn't exist in this library. The message is supposed to state `PdfMerger` (with an r)

Place of the bug: PyPDF2._utils.deprecate_with_replacement

**Comment by MartinThoma** [comment]
Thank you for reporting! Do you want to make a small pr fixing this?

**Comment by MartinThoma** [comment]
You can look for the line `deprecate_with_replacement("PdfFileMerger", "PdfMerge")`.

**Comment by pubpub-zz** [comment]
new goal : less thant 75 issues open!😁

**Comment by MartinThoma** [comment]
My goal is to close/merge those PRs from before April 2022 :smile: 

Similarly for the issues: I want to get rid of the really old stuff. I recently started to close issues that didn't have a PDF / code to reproduce. They have very little chance of ever getting closed + they cost energy to check.
