### ISSUE TITLE
Add `with ... as ...` Usage to `PdfMerger()`

### ISSUE THREAD

**Issue by JianzhengLuo** [py-pdf/PyPDF2#1108]
## Explanation

As I need to call `write()` and `close()` in `PdfMerger()`, why not add  `__enter__` and `__exit__` method to it so I can use it more elegantly.

## Code Example

```python3
from PyPDF2 import PdfMerger

with PdfMerger(strict=False) as merger:
    for name in ["01.pdf", "02.pdf", "03.pdf", ...]:
        merger.append(name)
    merger.write("./output.pdf")
```

**Comment by JianzhengLuo** [comment]
I'd like so, but as a middle school student in China, I am still busy even in summer vacation, but I will try my BEST!

**Comment by JianzhengLuo** [comment]
I noticed that `write()` is also necessary, and it has a parameter called `fileObj`, so I decided to add `fileObj` to the class initialization, now the code looks like this:

```python3
from PyPDF2 import PdfMerger

with PdfMerger(strict=False, fileObj="./output.pdf") as merger:
    for name in ["01.pdf", "02.pdf", "03.pdf", ...]:
        merger.append(name)
```

**Comment by JianzhengLuo** [comment]
`PdfWriter()` also needed to call `write()`, so I made it just like `PdfMerger()`----set `fileobj` when initializing.

**Comment by MartinThoma** [comment]
Please leave this open until the pr is merged
