### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by james811223ad** [py-pdf/PyPDF2#1109]
I'm trying to save a pdf with PdfFileWriter, but it's failing.

## Environment

AWS Fargate
```bash
$ python -m platform
maybe Linux-4.14.252-131.483.amzn1.x86_64-x86_64-with-glibc2.10

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.2.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
...
from PyPDF2 import PdfFileWriter, PdfFileReader

logger = logging.getLogger('foo')

def add_bookmarks_to_pdf(pdf_path, bookmarks, rotations, save_path):
    ...
    
    doc_orig = PdfFileReader(pdf_path)
    
    doc_new = PdfFileWriter()
    
    bookmarks_list = []
    
    for bookmark in bookmarks:
        ...
    
    bookmarks_list = sorted(bookmarks_list, key=lambda x: x[1])
    
    rotations_dict = {}
    
    for rotation in rotations:
        ...
    
    for i in range(doc_orig.getNumPages()): 
        ...
        
        if rotate:
            page = page.rotate(rotate)
        
        doc_new.addPage(page)
    
    for page, bookmark in bookmarks_list:
        doc_new.add_bookmark(bookmark, page)
    
    try:
        with open(save_path, 'wb') as f:
            doc_new.write(f)
    
    except Exception as e:
        logger.error(f'Failed to save {save_path}.')
        
        logger.exception(e)

        raise e
```

Can't share the pdf, since it's confidential. There're 0 pages being rotated, and 590 pages being bookmarked.

## Traceback

This is the Traceback I see:

Failed to save /tmp/tmpydh_kixk/602140805_indexed.pdf.
maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyarmordoc/bookmarking/bookmarking.py", line 71, in add_bookmarks_to_pdf
    doc_new.write(f)
  File "/usr/local/lib/python3.8/site-packages/PyPDF2/_writer.py", line 728, in write
    self._sweep_indirect_references(external_reference_map, self._root)
  File "/usr/local/lib/python3.8/site-packages/PyPDF2/_writer.py", line 847, in _sweep_indirect_references
    self._sweep_indirect_references(extern_map, realdata)
...

The full traceback is too long.

**Comment by MartinThoma** [comment]
Can you update the PyPDF2 version and check again?

**Comment by james811223ad** [comment]
Newest version works

**Comment by MartinThoma** [comment]
Nice! Thank you for checking ❤️
