### ISSUE TITLE
Can't extract text from documents

### ISSUE THREAD

**Issue by hemilparmar** [py-pdf/PyPDF2#1115]
When i parse some documents in PdfFileWriter class it is not giving me the right text it adds the random space between characters and in some documents it is only giving white spaces.
suppose we have 3 page of pdf with text so it is giving only white space and not a single character from that pdf
version : 1.27.4
[3.pdf](https://github.com/py-pdf/PyPDF2/files/9118198/3.pdf)

**Comment by MartinThoma** [comment]
Thank you for reaching out @hemilparmar 

Your bug report does not contain the minimal information required to help you. We have the bug issue template to help you report the right thing. For this reason, I'm closing the issue.

**Comment by hemilparmar** [comment]
@MartinThoma  Please check

**Comment by MartinThoma** [comment]
Please update your PyPDF2 version
