### ISSUE TITLE
KeyError: '/W'

### ISSUE THREAD

**Issue by Lightup1** [py-pdf/PyPDF2#1134]
Replace this: What happened? What were you trying to achieve?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.22000-SP0

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.6.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import os
import PyPDF2
pdf_filename="ST辅仁：2019年年度报告.PDF"
txt_filename="ST辅仁：2019年年度报告.txt"
with open(pdf_filename, 'rb') as pdfFileObj:
            pdfReader = PyPDF2.PdfReader(pdfFileObj)
            x=pdfReader.numPages
            with open(txt_filename,"a",encoding='utf-8') as file1:
                for i in range(x):
                    pageobj=pdfReader.pages[i]
                    text=pageobj.extract_text()
                    file1.writelines(text)
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
[ST辅仁：2019年年度报告.PDF](https://github.com/py-pdf/PyPDF2/files/9150656/ST.2019.PDF)

## Traceback

This is the complete Traceback I see:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
e:\pdf2txt\test\pdf2txt.ipynb Cell 4 in <cell line: 1>()
----> [1](vscode-notebook-cell:/e%3A/pdf2txt/test/pdf2txt.ipynb#ch0000004?line=0) dir_pdf2txt(dirlist[1])
e:\pdf2txt\test\pdf2txt.ipynb Cell 4 in dir_pdf2txt(dir_name)
     [15](vscode-notebook-cell:/e%3A/pdf2txt/test/pdf2txt.ipynb#ch0000004?line=14) pageobj=pdfReader.pages[i]
     [16](vscode-notebook-cell:/e%3A/pdf2txt/test/pdf2txt.ipynb#ch0000004?line=15) print(i)
---> [17](vscode-notebook-cell:/e%3A/pdf2txt/test/pdf2txt.ipynb#ch0000004?line=16) text=pageobj.extract_text()
     [18](vscode-notebook-cell:/e%3A/pdf2txt/test/pdf2txt.ipynb#ch0000004?line=17) file1.writelines(text)

File c:\Users\Baiyi Yu\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_page.py:1433, in PageObject.extract_text(self, Tj_sep, TJ_sep, space_width)
   1415 def extract_text(
   1416     self, Tj_sep: str = "", TJ_sep: str = "", space_width: float = 200.0
   1417 ) -> str:
   1418     """
   1419     Locate all text drawing commands, in the order they are provided in the
   1420     content stream, and extract the text.
   (...)
   1431     :return: The extracted text
   1432     """
-> 1433     return self._extract_text(self, self.pdf, space_width, PG.CONTENTS)

File c:\Users\Baiyi Yu\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_page.py:1135, in PageObject._extract_text(self, obj, pdf, space_width, content_key)
   1133 if "/Font" in resources_dict:
...
File c:\Users\Baiyi Yu\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic.py:681, in DictionaryObject.__getitem__(self, key)
    680 def __getitem__(self, key: Any) -> PdfObject:
--> 681     return dict.__getitem__(self, key).get_object()

KeyError: '/W'

```

**Comment by pubpub-zz** [comment]
this is a robustness issue (thanks for the test file 😊) 
will be fixed in #1136

**Comment by Lightup1** [comment]
The key error dissappered after this merge #1136 .
But the extract results seem to be garbled.
Like this :
```
]
-Añ-J  7 ]
-Añh1Ñ*6
ˆJ  
:Ôp  7 :#§AñhÔCp  
\ œ
(Ã œ
(  7 Eµñ9ŸJLö
f9Ÿ6Ñ-9L€ œ
(
 
Eµñ2  7 "ã	‡Eµñ2f9Ÿ9L€ œ
(  
EµñLö
  7 Eµñ9ŸJLö
9L€ œ
```
Is it a bug from pypdf2 or just this pdf file is broken?

**Comment by MartinThoma** [comment]
@Lightup1 You mean `page.extract_text()` leads to this? Is your editor showing it with `utf-8` or might it be an encoding issue of the editor?

**Comment by MartinThoma** [comment]
I think it might make sense to open another issue for that

**Comment by MartinThoma** [comment]
Regarding adding your to CONTRIBUTORS.md: Should I just add you as

> [Lightup1](https://github.com/Lightup1)

or do you want me to use another name / link to another profile?

**Comment by Lightup1** [comment]
> Regarding adding your to CONTRIBUTORS.md: Should I just add you as
> 
> > [Lightup1](https://github.com/Lightup1)
> 
> or do you want me to use another name / link to another profile?

Thanks this one [Lightup1](https://github.com/Lightup1) is OK.

**Comment by Lightup1** [comment]
> @Lightup1 You mean `page.extract_text()` leads to this? Is your editor showing it with `utf-8` or might it be an encoding issue of the editor?

I've tried encoding with `UTF-8` and `UTF-16`. They all show these garbled characters.
And some characters which can be copied inside a pdf viewer like edge or Adobe PDF viewer are not shown in the written file. It seems that  `page.extract_text()` missed some information inside the PDF which should be extracted as they  can be copied in these viewers.

**Comment by MartinThoma** [comment]
I'll re-open the issue for the moment so that we don't forget about it. However, we should really create a new issue.

**Comment by Lightup1** [comment]
Thank you @MartinThoma  I just opened a new issue and this one can be closed
