### ISSUE TITLE
Missing pages after writing pdf

### ISSUE THREAD

**Issue by james811223ad** [py-pdf/PyPDF2#1135]
I have a script to add bookmarks and rotate some pages in a pdf, then writes a new pdf. The script has assertion that the original pdf and new pdf have the same pages. For some reason, the pdf produced by the script has blank pages after certain page. When I tested with no bookmarks or rotations to apply, I get pdf with missing pages after a certain page. The pdfs I tested have around 1000 pages.

## Environment

The script was run in AWS Fargate

```bash
$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.5.0
```

## Code

This is a minimal, complete example that shows the issue:

```python
...

def add_bookmarks_to_pdf(pdf_path, bookmarks, rotations, save_path):
    doc_orig = PdfFileReader(pdf_path)
    doc_new = PdfFileWriter()
    bookmarks_list = []

    for bookmark in bookmarks:
        bm = bookmark.get('text')
        
        if isinstance(bm, str):
            bookmarks_list.append((int(bookmark.get('page')) - 1, bm))
    
    bookmarks_list = sorted(bookmarks_list, key=lambda x: x[1])
    
    rotations_dict = {}
    
    for rotation in rotations:
        rotation_instruction = rotation.get('pageRotation')

        if isinstance(rotation_instruction, str):
            rotations_dict.update({int(rotation.get('page')) - 1: int(rotation_instruction[1:4])})
    
    for i in range(doc_orig.getNumPages()): 
        page = doc_orig.getPage(i)
        
        rotate = rotations_dict.get(i)
        
        if rotate:
            page = page.rotate(rotate)
        
        doc_new.addPage(page)
    
    for page, bookmark in bookmarks_list:
        doc_new.add_bookmark(bookmark, page)
    
    assert doc_orig.getNumPages() == doc_new.getNumPages()

    doc_new.write(f)
```

**Comment by MartinThoma** [comment]
Does this always happen for a given set of pages? Does it always happen after the same page? 

Does it happen for all examples you tried?

> When I tested with no bookmarks or rotations to apply, I get pdf with missing pages after a certain page

So the same as with bookmarks / rotations, right?

**Comment by james811223ad** [comment]
> Does this always happen for a given set of pages?
> It happens if there're many pages.

> Does it always happen after the same page?
> No

> Does it happen for all examples you tried?
> Only for pdfs with many pages, I'd say more than 500/600 maybe?

> So the same as with bookmarks / rotations, right?
> With bookmarks and/or rotations the new pdf would have blank pages after a certain page when open up.
> Without bookmarks and/or rotations the new pdf would have missing pages after a certain page when open up.

**Comment by MartinThoma** [comment]
You might have been running into https://github.com/py-pdf/PyPDF2/pull/1105 - thanks for letting us know that it's fixed :heart:
