### ISSUE TITLE
Can't extract text,  getting unnecessary numbers

### ISSUE THREAD

**Issue by hemilparmar** [py-pdf/PyPDF2#1171]
When i try to parse the pdf can not get text from pdf. getting the random numbers.

PyPDF2 version :  2.8.0
File : 
[test.pdf](https://github.com/py-pdf/PyPDF2/files/9181676/test.pdf)

Code :
with open(filename, 'rb') as file:
       pdfreader = PyPDF2.PdfFileReader(file)

       for obj in range(pdfreader.numPages):
           pageobj = pdfreader.getPage(obj)
           print(f"\n**********Page:{obj+1}**********\n")
           text = pageobj.extractText()
           print(text)

**Comment by hemilparmar** [comment]
Please check the above details and provide some solution.
Thank You

**Comment by pubpub-zz** [comment]
@hemilparmar,
if you open your file in Acrobat Reader, and try to copy some text, you will see that odd characters : this is due to a scrambled ToUnicode translation that has been introduced at will to prevent text extraction. This is not a issue with PyPDF2. Sorry
This issue could be closed.

**Comment by hemilparmar** [comment]
Okay, Thanks

**Comment by MartinThoma** [comment]
I've just checked: Tika and pdfium also cannot extract anything. It's probably just impossible.

@pubpub-zz do you think it's possible to detect that it's not possible to extract meaningful information?

**Comment by hemilparmar** [comment]
@MartinThoma @pubpub-zz  I've also tried with fitz. it's giving me random symbols

**Comment by pubpub-zz** [comment]
If something could be trued if has to be outside pypdf2 with humans help
As a proposal https://stackoverflow.com/questions/43466703/remap-scrambled-pdf-characters-to-readable-text

**Comment by MartinThoma** [comment]
@hemilparmar The best thing you can do in this case:

1. Convert to an image (e.g. with fitz)
2. Apply OCR (e.g. tesseract-ocr)
