### ISSUE TITLE
Named destinations are not found in PDF exported with LibreOffice Writer

### ISSUE THREAD

**Issue by gcrabbe** [py-pdf/PyPDF2#1173]
## MCVE

PyPDF2 seems unable to retrieve the named destinations in a sample PDF document exported with LibreOffice Writer 7.3: 

[lorem_ipsum.pdf](https://github.com/py-pdf/PyPDF2/files/9197028/lorem_ipsum.pdf)

```python
>>> import PyPDF2 
>>> r = PyPDF2.PdfReader("lorem_ipsum.pdf")
>>> r.metadata
{'/Creator': 'Writer', '/Producer': 'LibreOffice 7.3', '/CreationDate': "D:20220727095634+02'00'"}
>>> r.named_destinations
{}
```

At first, I suspected a bug in LibreOffice, but Poppler's `pdfinfo` utility seems to have no trouble with it:

```bash
$ pdfinfo -dests lorem_ipsum.pdf 
Page  Destination                 Name
   1 [ XYZ   92  736 null      ] "Dolor2520sit2520amet"
   2 [ XYZ   92  627 null      ] "Sodales2520posuere2520metus2520id"
```

URL anchor links also work as expected:

```bash
$ firefox lorem_ipsum.pdf#Sodales2520posuere2520metus2520id
```

## Environment

```bash
$ python -m platform
Linux-5.15.0-41-generic-x86_64-with-glibc2.10

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.8.1
```

**Comment by mtd91429** [comment]
In this case, the `/Root` contains a `/Dests` entry (object 23) which points to the name dictionary. The error seems to occur around [line 649](https://github.com/py-pdf/PyPDF2/blob/d8bd12f3e1d6b5a5b0a488413dbe8ec598b84355/PyPDF2/_reader.py#L649) of _reader.py (Just below the comment "Entries in a name tree node dictionary". which, for what it's worth, is not the correct table number for the PDFv1.7 specs; it should be Table 36). 

The current code assumes that the named destination dictionary is nested under a key with `/Names`. In this instance, it isn't; it is the bare name tree dictionary. This should be a simple fix. I'll try a PR shortly for it.

**Comment by pubpub-zz** [comment]
@mtd91429 , standby : I'm publishing the fix 😉

**Comment by mtd91429** [comment]
lol, never mind!

**Comment by pubpub-zz** [comment]
What a team! no bug will survive for a very long time 😆🤣🤣🤣

**Comment by MartinThoma** [comment]
:clap: :clap: :clap: 

You're amazing :heart:
