### ISSUE TITLE
Extracted text includes non-visible content

### ISSUE THREAD

**Issue by equaeghe** [py-pdf/PyPDF2#1199]
I was extracting text from [a specific pdf file](https://proceedings.mlr.press/v161/zou21a/zou21a.pdf) (generated with LaTeX) and on one page (sixth of the paper, number 1157) where a diagram is present (likely generated with [LateXit](https://www.chachatelier.fr/latexit/)), a block of non-text xml-like(?) base64-encoded(?) content is present. I assume PyPDF2 should not include it as extracted text.

This non-text output looks like
```
<latexit sha1_base64="9MhPbHbMEbe02jvX1Eg/vLAXmes=">AABMknicxZxbc9u4Fcex29s2vWXbPrTTmQ7bjGe2mcRjpU2306dNnOtGSZTYTryJ0gxB0xJjiVIkyrGiqE/9NH3oS/tl+m16zgEIkCDBQ3nS2WhikQB+Bwe3P8ALJKejZJ7t7Pz3k0+/893vff8Hn/3wwo9+/JOf/uzi5z9/Np8sZlF8EE1Gk9mhDOfxKEnjgyzJRvHhdBaHYzmKn8uTXYx/fhrP5skk3c+W0/jVOBykyXEShRkEvb742/6ZfH3yt1U/i88y+Juky6A3m7y5une3e2u9fn3x0s72Dv0LqgcdfXBJ6H+9yedb/xJ9cSQmIhILMRaxSEUGxyMRijl8XoqO2BFTCHslVhA2g6OE4mOxFheAXUCqGFKEEHoCfwdw9lKHpnCONudER5DLCP7PgAzElk5zBMfHFKq+Mf+gkNaXx4pso49L+Jba5hhCMzGEUI7LU7blsEwZePgXKksCfk4pBEsZlUp0DN8jOM/Af/y7hJQxHB0BNYOjCMJGEKpCMI8ZfKt6xZIPqZ5DShfDEfq0Ja5+658t8gP/B2IfvMQyjajeYnEGx2NdFiz1BGohoBrFVHviIZSuS8cDSrGAOtnWtj7mR1K93gNPUvjuQq4L4/W3XX+qBnG0YR/BHhQX+vkK6m9JtRNTn1pDyAzOJR3tQG39UVyBMuHRl+aoQ6MQrT4F6i2UVvWxHtPn2xJ2dLUl0P64VXpJ6YIWKRcQOmrQmxUpTQYWE+Nrfboxjc2M8pmId41pBzQKp1AeHJlnjWnnEC6pVQfkbZM6rqgdTqj1Y/CmuWQS/JzAeQYhElI0pUXdQJ+Xjan42gwhfkC9Mim1Z9vUCSminziC0Fzrm9LhOFCz0kzrjEqNs08G30MK7UM7JjSq1HkxBbb0iOJsKhtmR2MfckzEKeW4gk8fRtgH+rvWeebp0PcVfSdwNCUFXFK/XxZmRRzb72h0j6m1U0iPHti80cacWhVLPKOeoMISqm91PKZ5eEhn+eiNqMZX4jn51gd2QTmv9EyNbIe0IaZeu9YaUVTAgPrVyMy+2BJzOC5rla8k6E2olcn6hf0fe8O6oQ4wvaRPHStZNvKyEcseecgjlow9ZMySxx7ymCUHHnLAkkMPOWTJxEMmLPnGQ75hyRMPecKSIw85YsmxhxyzZOrtfynLTjzkhCWnHnLKkm895FuWnHnIGUvOvXU0Z9nMQ2YsufCQC5Y89ZCnLPnOQ75jyTMPecaSSw+5ZMn3HvK9mSGaNDvULK7a2qp8keC1XZKGW4JXdEnabQleySVptiV4BZdUS0WG125JKm0JXrMlqbMleK2WpMo50U6lJemxzYVXZ0k6bAlelSXpryV4NZb6SsAyvA5LfYWUE7z6StJZS/CqK0lfLcGrrSRdtQSvspL01BK8uqprAEvwmir1mjAneC2VpJqW4DVUklpagtdOSSppCV4zJamjJXitlKSKluA1UpIaWsJq4wVGIW941PUGm+dND3mTJXc95C5L3vKQt1jytoe8zZJ3POQdlrzrIe+y5D0PeY8l73vI+yz5tYf8miUfeMgHLNn1kF2WfOghH7LkIw/5iCUfe8jHLNnzkD2WfOIhn7DkUw/5lCX3vCvhPZbd95D7LHngIQ9Y8pmHfMaSzz3kc5Y89JCHLPmNh/yGJV94yBdG7ZtmiBulGYLXd0lKbgle1yUpuCV4PZek3JbgdVySYluC129JSm0JXrclKbQleL2WpMyW4HVakiJbgtdnSUpsCV6XJSmwJXg9lqS8luB1WJLiWoLXX0lKawledyUprCV4vZWkrJbgdVaSolqC11dJSmoJXlcl6acleDWVpJuW4FVUkl5agldPSTppCV41JemjJXi1lKSLluBVUpIeWoJXR0k6aAmriu49ZHUnekRPPYrPSs57Tzky2prrcn6vm1fZyKisy/J6Gxm9dVleeSOjvC7La3BkNNhleTWOjBq7LK/LkdFll+UVOjIK7bK8VkdGq12WV+3IqLbL8vodGf12WV7JI6PkLstremQ03WV5dY+Murssr/OR0XmX5RU/Morvsrz2R0b7XZafBSIzC7gsPx9Eej6oo9XcwPH7Xn6/FX/g8Z2fNSIza7gsP39EZv5wWX4micxM4rL8nBKZOcVl+dklMrOLyxbnmbrnlfikNaLnRROBT7qPPE8x2883uxXdx+u1Nqp/u6LciuR1+1mlvRXJt/b9inoqktfOBxX9U2Sb+wqu+imyzX0FV/sU2ea+gqt8iuR1r1fRLkW2uTvgKpci29wdcHVLkW3uDuyZdWyZ5dezLyqjSJEvWPKwMu4V2eZ62x31iuTH/GP44FscAxHWWuiX4ps0IB/t+XtSJ+dea0pSnSm9M1Jc7fZL4fyTi5je4ShbsKH8c6JQh5UtFMP5J1pTemtkRPVQtuPG8XfxQ6pZv8X6FPxd9bp6et+6ntSbhFULxfB2ZfNZqsbyT8bwimdasVQM55+VYTvjc0zXSjmGszN2ntj0dQj/FM3l0lbcWenpI36ftXr+OK1w01acap0qXQznn7QNxaSWz2P4J294pVsdrcXwdiXxWarG8iMjrLRhHsY/5fOPczeOb9lhTdsON2rdqoVyDGcnqrEQtWRVaV3/563YiTO75XwxnL+vfNczFxTD+bvAMb3f6toohvN3yuoVcn8Dbex6da0cw9/tctvksFWL9CpcrxW35xmXexuMyIOGUeXG8eWo9uheyx7dq+nRvZY92l2v5XzdOq28RtvTvT7Qb7em1NLqas2++a72O2AdbPrW6YzaITE1m68kJ1CzxfOZUO8pFdNz5c5Th+ZNg3bWw8J7tn7rY11y/MaVT5scqgyvJGr2aFc/Ni3nfWbeVGm2mOl3WHIvUXnUfiJcNT7UaR/Tnhj1Vrfa/YBXxqHOA8/QWmDC1hvYukz8rpgYj5UtFTI7p63Tiq3Tc1hKqD7L9ajeKO9QKQPaRxTANT2mS+jeiOKbWxzP8E78sd45tBYvxTXaqaTaDt8EzwpvqQeib9KuxCXKHb+v6bYLaF/Gx92bw398ZbxsrhZmegWXaxLugmnquZf1PJzq8Wa5TouRpPZnDZw+aUPtlerWR/y4FgPxiHrAmHaCNfmb6nRr2reHrf8BPti6+M1pvlIC10IeM6D9EPYYrfrimnNC3Sjmc017in3yd/C3fIT5uGH50WtqF9tr3Xq7BbngbsIp9ZsjWNPinrrmFkdiWvBLXYmlUC61x0KNlSsm3z6Nojy+7IPakaZG2QmtneaNuaM6pNTLy/njrJk5nqiauUJeBOQF1v6Q0rke+XOcCalz6zi5faFb2Nr9A2Nr7rX1smLrFWMr8trq6zYol5ibvdIGex9q7HF9OPTaq1r7UOmZxf7xWN9zmInAyYcb7WMTpnbtFr0Z67WJ2qca6hk2o/Ol6cVcrR035IB33XCspPQ3brC/1agFp1R2qef5YglOKAb3cV4TeDfDph7p3ZPldFd1OlX/1fB1rVVOq9r4h7utrrf00aat+mnjXF+LMU3+LvTqorouOypoZLUvYk8s7xENPHNTnrfqtRNa84wLKwu1j9UXu9brm3xnuF1jqP4zoeujmBS47aphi6461N7BmMohdSv8P6xLupLGvaNl6/mMFtIqLN/b2D6PmzRD4e7lnC7ab+9v1bJaS6oRrFoZ91+7OeD8fUy1g8oV03vl7fPYL7V3QGdh6blcMa/tc5YHc+qR7ziPL6inqqtILNexyLSOZh5vyj5cp9hNPan2ts3ytWt8f53N6dohgqMv6AoAyyeF2m+vZpmAmCmNK9wLPiY2Jc0ZiCD4VbE/Br+GuVvNJecdtYpOIO8zgW+s589isdeeke6koriv/ahRpVw+v7LK97F2dOuomOKZrb2YrOW/NKBWeHh8geamxPH4ibgNq0Gfn/neXpVqJf5e8OYl6XL+CxjXzQ7b/Kiv59c+tQHO2idge6p1uuqJ9bS51rB8p3qfempm4FWBV7WW547tnRRGej6iccTYHAOqQ4wbUq54zVjXnn1af2KrvXLm8LZ+qf6JO5dt/tsm/6DkQWDq3ldr5Z7ZXHPltCvnHHPfd0JsnjZH7G8hlQF7wWY5lllcNZRTYE+67aSp80HVqbqPgGNxMy9cem3aohhWl++ILOCI3SxHy9WXuVuIbyrvhO5L5dp+vlKXbdT70/OkrfNNUTjWTjb0qEjW+/G0lKIu94jST2i0YLpN+0KVr/dktyZdnT91d3I386jOQr1Pt2pT+mopFW9ErNcHs41Hbp0Ff01VU9Z5dSzUb/ls5klO1ed+x8TW1wO2XrKxUlrOV2YbX5ev+s2ohV6ZnKdX1Fmo9+VGbcqiV+q3QyRp3TuhfpsEPUB9fltaPa7pTrhqyaIlv4XqnFLl4fP64qWO++tb1YNn17Y7f97eefKnS1/d1L/M9Zn4jfg9rP464kvxlbgHSnUA1v8h/in+Lf7T/WX3r90b3V2V9NNPNPMLUfrX7f4PAJ6ZXg==</latexit>
```

## Environment

```bash
$ python -m platform
Linux-5.15.52-gentoo-a-x86_64-AMD_Ryzen_7_PRO_4750U_with_Radeon_Graphics-with-glibc2.35

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.4.1
```

## PDF + Code

The pdf ‘zou21.pdf’ can be found on the PMLR website, e.g., via the page https://proceedings.mlr.press/v161/zou21a.html. PMLR papers have a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0) and therefore I think they can be included in your tests.

```python
import PyPDF2
pdf = PyPDF2.PdfReader('zou21a.pdf')
text = pdf.pages[5].extract_text()
```

**Comment by pubpub-zz** [comment]
@equaeghe, thanks for the test case.
I ran it with the latest version and I get something different:
'corollariesandlemmasaredeferredtotheappendix.We\nhighlightthekeyprooftechniqueanditsnoveltyand\ndifferencecomparedwithpriorworks.Thenwewillgoover\neachofthekeystepsindetail.\n6.1\nPROOFTECHNIQUEANDNOVELTY\nProofTechnique.\nOurproofreliesontwosequences\n(greenarrowsinFigure1):\nProjectedSGLD\n(\nx\nProj-SGLD\nk\n)and\nMetropolizedSGLD\n(\nx\nMH\nk\n).ProjectedSGLDisconstructed\nbyaddinganaccept/rejectsteptothestandardSGLDal-\ngorithm,whichwasstudiedinZhangetal.[2017].\nMetropolizedSGLDisaﬁvirtualﬂsequenceconstructed\nbyfurtheraddingaMetropolisHastingstepintoProjected\nSGLD(theMetropolisHastingstepiscomputationallyin-\ntractablesothatMetropolizedSGLDisnotapracticalal-\ngorithmandweonlyuseitfortheoreticalanalysis).Dueto\nsuchMetropolisHastingstep,MetropolizedSGLDisatime-\nreversibleMarkovchainandthusenjoysgoodconductance\nproperties.Basedonthesetwoauxiliarysequences,wewill\nprovetheconvergenceofSGLDfollowingthreesteps:(1)\nshowthattheoutputofProjectedSGLDisclosetothatof\nSGLDindistribution(seeLemma6.1);(2)showthatthe\ntransitiondistributionofProjectedSGLDisclosetothatof\nMetropolizedSGLD(seeLemma6.2);and(3)provethe\nconvergenceofProjectedSGLDbasedontheconductance\nofMetropolizedSGLD(seeLemma6.4).\nTechnicalNovelty.\nInordertoprovetheconvergencerate\nofSGLD,priorworks[Raginskyetal.,2017,Xuetal.,\n2018]typicallymakeuseoftheLMCiterates\nx\nLMC\nk\nandde-\ncomposethesamplingerrorofSGLD(theerrorbetween\nx\nk\nand\nx\nˇ\n)intotwoparts:(1)theerrorbetweenSGLDiter-\natesandLMCiterates;and(2)thesamplingerrorofLMC\n(thoughRaginskyetal.[2017],Xuetal.[2018]boundthe\nsamplingerrorof\nx\nLMC\nk\nindifferentways).Weillustratethe\nroadmapofdifferentprooftechniquesinFigure1.Notethat\ntheirresultsontheerrorbetween\nx\nk\nand\nx\nLMC\nk\ndivergeas\nk\nincreases,duetotheuncertaintyofstochasticgradients.\nThissuggeststhatLMCmaynotbeagoodenoughauxiliary\nchainforstudyingSGLD.Incontrast,ourconstructedaux-\niliarysequences(i.e.,ProjectedSGLDandMetropolized\nSGLD)areclosertoSGLDsincetheyalsocovertheran-\ndomnessofstochasticgradients(thisrandomnesscanbe\nincludedaspartofthetransitiondistribution,seeSection\n6.3formoredetails).Therefore,ourprooftechniquecan\nleadtoasharperconvergenceanalysisthanthoseinRa-\nginskyetal.[2017],Xuetal.[2018],whichconsequently\ngivesafasterconvergencerateofSGLDforsamplingfrom\nnon-log-concavedistributions.\nWewouldalsoliketopointoutthatwhiletheconstructionof\nMetropolizedSGLDfollowsthesamespiritofZhangetal.\n[2017],ithasadifferentgoalandthusthecorresponding\nanalysisisnotthesame.,Zhangetal.[2017]\nFigure1:IllustrationoftheanalysisframeworkofSGLDin\ndifferentworks:\nRaginskyetal.(2017)\n,\nXuetal.(2018)\n,\nthiswork\n.ThegoalistoprovetheconvergenceofSGLD\niterates\nx\nk\ntothepointfollowingthetargetdistribution\nx\nˇ\n.\nNotethat,\nx\nLMC\nk\n,\nx\nProj-SGLD\nk\nand\nx\nMH\nk\ndenotethe\nk\n-thiteratesof\nLMC,Proj-SGLD,andMetropolizedSGLDrespectively;\nx\nLD\nt\ndenotesthesolutionof\n(1.1)\nattime\nt\n;\nx\nˇ\nLMC\ndenotesthe\npointfollowingthestationarydistributionofLMC.\nonlycharacterizesthehittingtimeofSGLDtoacertainset\nbylowerboundingtherestrictedconductanceofSGLD,but\ndoesnotproveitsconvergenceto\nˇ\n.Incontrast,wefocus\nontheabilityofSGLDforsamplingfromacertaintarget\ndistribution.Thuswenotonlyneedtoanalyzetheconduc-\ntanceofSGLD,butalsoneedtoboundtheapproximation\nerrorbetweenthedistributionof\nx\nk\nandthetargetone(see\nLemma6.4andB.3andtheirproofsformoredetails),which\nismorechallenging.Asaconsequence,weprovethatthe\nsamplingerrorofSGLDtothetargetdistributioncanbe\nupperboundedby\nO\n(\np\n\n)\n,whiletheanalysisinZhangetal.\n[2017]canonlygive\nO\n(1)\nsamplingerror.\n6.2\nPROJECTEDSGLDANDITSEQUIVALENCE\nTOSGLD\nProjectedSGLDisconstructedbyaddinganextrastepin\nAlgorithm2withthefollowingaccept/rejectrule:\nx\nk\n+1\n=\n(\nx\nk\n+1\nx\nk\n+1\n2B\n(\nx\nk\n;r\n)\n\\B\n(\n0\n;R\n);\nx\nk\notherwise\n:\n(6.1)\nThisstepensureseachnewiterate\nx\nk\n+1\ndoesnotgotoofar\nawayfromthecurrentiterateandalliteratesarerestrictedin\na(relatively)largeregion\nB\n(\n0\n;R\n)\n.Theentirealgorithmis\nsummarizedinAlgorithm2.Duetotheaboveaccept/reject\nrule,ProjectedSGLDisslightlydifferentfromthestandard\nSGLDalgorithm(seeAlgorithm1).However,wecanshow\nthatProjectedSGLDisnearlythesameasSGLDgiven\nproperchoicesof\nR\nand\nr\n.Inparticular,inthefollowing\nlemma,wewillshowthatthetotalvariancedistancebe-\ntweenthedistributionsoftheoutputsofbothalgorithmscan\nbearbitrarilysmall.\nLemma6.1.\nLet\n\nSGLD\nK\nand\n\nProj-SGLD\nK\nbethedistributions\noftheoutputsofthestandardSGLDalgorithmandthe\nprojectedSGLDalgorithm.Forany\n\n2\n(0\n;\n1)\n,set\nR\n=\n\nR\n(\n\n\n1\n=\n4)\n;r\n=\np\n2\n\n\n2+\np\n2log(8\nK\n)\n=d\n\n:\n1157\n'

Word spacing is not good but I can not find your latexit.

**Comment by pubpub-zz** [comment]
@equaeghe,
After test I confirm the sequence you've found. If you open the document with acrobat , and you copy the text from page 1157 you will also observe the latexit sequence.

This issue can be closed

**Comment by MartinThoma** [comment]
That's an interesting one. Let's first look at how others behave:

* Google Chrome Pdf Viewer: Not visible, even Ctrl+a -> Ctrl+c -> Ctrl+V does not show it
* Evince PDF viewer: Not visible, but Ctrl+a -> Ctrl+c -> Ctrl+V does show it
* Tika: Does extract it

I would also expect it not to be extracted... but I have no clue how to distinguish it from other content.

**Comment by pubpub-zz** [comment]
> 

For information it is "behind" a Tj operator within an XObject. it is normal to extract it

**Comment by equaeghe** [comment]
> For information it is "behind" a Tj operator within an XObject. it is normal to extract it

So does this mean it is actually LaTeXit that shouldn't inject that content there and so that I should report it there?

**Comment by MartinThoma** [comment]
You could ask LaTeXit why they do it. I'm pretty certain they do it on purpose. It is "Figure 1" (the image) that has this text "behind" it.

Interestingly, Google also extracts this:

![image](https://user-images.githubusercontent.com/1658117/183236048-dc515d05-4c25-4535-bf80-18f18cf4c11d.png)

**Comment by MartinThoma** [comment]
I will close this for now, but I do see when you comment here. I'd be very interested in why latexit adds those tags.
