### ISSUE TITLE
Unspecific type hints for reader.metadata

### ISSUE THREAD

**Issue by adamchainz** [py-pdf/PyPDF2#1222]
Take the below example file:

```python
from PyPDF2 import PdfReader

with open("example.pdf", "rb") as fp:
    reader = PdfReader(fp)
    metadata = reader.metadata
    assert metadata is not None
    date_str = metadata["/CreationDate"]
    date_str = date_str.removeprefix("D:").replace("'", "")
    print(date_str)
```

It runs fine:

```
$ python example.py
20220415093243+0200
```

but Mypy complains about using `remove_prefix()` on `date_str`:

```
$ mypy example.py
example.py:8: error: "PdfObject" has no attribute "removeprefix"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

This is due to `DocumentInformation` being a subclass of `DictionaryObject`, and thus only guaranteeing that the values returned are `PdfObject`s. In practice they seem to only be `TextStringObject`s, which subclass `str`. If they're always `TextStringObject`s, the types in `DocumentInformation` should be adjusted accordingly.

## Environment

```bash
$ python -m platform
macOS-12.5-arm64-arm-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.9.0
```

## Code + PDF

above, used `metadata.pdf` from PyPDF2 resources

**Comment by MartinThoma** [comment]
Thank you for mentioning this issue!

Instead of using the dictionary key, I recommend now (after the PR I just merged and that will be on PyPI tomorrow) to use the property:

```python
# Old, makes mypy complain:
date_str = metadata["/CreationDate"]

# New, makes mypy happy and you don't have to parse that string:
date = metadata.creation_date
```

**Comment by adamchainz** [comment]
Great, thanks!
