### ISSUE TITLE
XFA forms: internally protected document 

### ISSUE THREAD

**Issue by pubpub-zz** [py-pdf/PyPDF2#1224]
the pdf viewed by PyPDF2 is not totally different that the one viewed in PDF
pdf has been reported from #245

## Environment

Windows + Python 10 + PyPDF 2.10.0

## Code + PDF
[fdo-fundingapplication-demandedefinancement.pdf](https://github.com/py-pdf/PyPDF2/files/9006093/fdo-fundingapplication-demandedefinancement.pdf)

`import PyPDF2;PdfReader("c:/fdo-fundingapplication-demandedefinancement.pdf").pages[0].extract_text()`

reports :
> The document you are trying to load requires Adobe Reader 8 or higher. You may not have the
> Adobe Reader installed or your viewing environment may not be properly configured to use
> Adobe Reader.
> 
> For information on how to install Adobe Reader and configure your viewing environment please
> see  http://www.adobe.com/go/pdf_forms_configure.
> 

but the page 0 displays a form in PDF.
Also 1 page is detected but 6 pages are readable in Acrobat Reader

same problem with pdfminer.six

**Comment by pubpub-zz** [comment]
after further review this PDF is an XFA form without any "PDF" rendering. My proposed way forward:

- add a function `get_xfa_form`:

        if not an XFA form, returns None
        if it is an XFA form, returns a dictionary where keys are the XFA keys (config, datasets,form....), and the value is the content decoded object (eg.: {'xdp:xdp': '<?xml version="1.0" encoding...', 'form': '<form checksum="Ez8929e...', '</xdp:xdp>': '</xdp:xdp>'})
for signed data, the pdf will be decoded with the default empty key

- the extract_text will require too much rendering to report something consistant : no change propose

@MartinThoma  your opinion?

**Comment by MartinThoma** [comment]
> the pdf viewed by PyPDF2 is not totally different that the one viewed in PDF

I don't understand this.

> after further review this PDF is an XFA form without any "PDF" rendering: add a function get_xfa_form

Can there be multiple xfa forms on a single page?

> the extract_text will require too much rendering to report something consistant : no change propose

Fine with me :-)

**Comment by pubpub-zz** [comment]
> > the pdf viewed by PyPDF2 is not totally different that the one viewed in PDF
> 
> I don't understand this.

I reword: PyPDF2 extract_tract reports just one sentence whereas PDF **Reader** shows a full form:
![image](https://user-images.githubusercontent.com/4083478/185750290-e7da2b9b-7b6e-47e7-a881-4c244e26dddf.png)

> > after further review this PDF is an XFA form without any "PDF" rendering: add a function get_xfa_form
>
> Can there be multiple xfa forms on a single page?

the PDF spec states:
___
>(Optional; PDF 1.5) A stream or array containing **an** XFA resource, whose format shall be described by the Data Package (XDP) 
>Specification. (see the Bibliography).
>The value of this entry shall be either a stream representing the entire contents of **the XML Data Package** or an array of text 
>string and stream pairs representing the individual packets comprising the XML Data Package.
>See 12.7.8, “XFA Forms,” for more information.
___

My  understanding is that there is only one XFA package within one PDF (actually making merging very tough)
