### ISSUE TITLE
ModuleNotFoundError: No module named 'PyPDF2.generic' in colab

### ISSUE THREAD

**Issue by WevertonGomesCosta** [py-pdf/PyPDF2#1241]
in colab when importing PyPDF2, returns the error:
No module named 'PyPDF2.generic'

I had to import the PyPDF2==2.4.1 version so that this error would not appear.

**Comment by igadmile** [comment]
Yeah `2.10.0` works fine.

**Comment by pubpub-zz** [comment]
@WevertonGomesCosta,
please indicate Python version, how you did installed PyPDF2 and a simple test code with traces of your issue

**Comment by MartinThoma** [comment]
@WevertonGomesCosta Thank you for reporting the issue that quickly :heart:  If you want to, I can add you as a contributor: https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by WevertonGomesCosta** [comment]
@MartinThoma Thanks so much for fixing it quickly.
I accept the invitation to be a contributor.
