### ISSUE TITLE
No module name PyPDF2.generic in 2.10.1

### ISSUE THREAD

**Issue by jseltmann** [py-pdf/PyPDF2#1243]
Importing fails for version 2.10.1 because of a missing module, but works when I use 2.10.0.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.18.16-zen1-1-zen-x86_64-with-glibc2.36

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/work/Test/venv/lib/python3.10/site-packages/PyPDF2/__init__.py", line 10, in <module>
    from ._encryption import PasswordType
  File "/home/work/Test/venv/lib/python3.10/site-packages/PyPDF2/_encryption.py", line 36, in <module>
    from PyPDF2.generic import (
ModuleNotFoundError: No module named 'PyPDF2.generic'
```

## Code + PDF

This is a minimal, complete example that shows the issue:

see above

## Traceback

This is the complete Traceback I see:

see above

**Comment by pubpub-zz** [comment]
@MartinThoma 
the generic folder is not inserted in the whl file

**Comment by MartinThoma** [comment]
Damn - I'll upload a fix in ~10 minutes

**Comment by walber** [comment]
Workaround: 
`pipenv install pypdf2==2.10.0`

**Comment by MartinThoma** [comment]
`PyPDF2==2.10.2` fixes it.

**Comment by MartinThoma** [comment]
@jseltmann Thank you for reporting it :heart: 

I've you want, I can add you to the contributors list: https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by MartinThoma** [comment]
I wish we could find a way to do this: https://stackoverflow.com/q/72892816/562769

That would have prevented this issue.
