### ISSUE TITLE
Interactive Form Support

### ISSUE THREAD

**Issue by mstamy2** [py-pdf/PyPDF2#125]
`PyPDF2` can access form data now, including field names and any field values that have been written. It can also write a nice little report on all fields similar to `pdftk`.

Next step: Allow form fields to be filled.

**Comment by Ev3r10sT** [comment]
I upgraded to centos7 and PyPDF2 looks like the only alternative to pdftk (which is not supported anymore because of libgcj)...
So how is that writing to forms thing going? :+1:

**Comment by Khwunchai** [comment]
I've been playing with it for a while using a combination of PdfFileReader and PdfFileWriter. I've found that PyPDF2 could fill most of the blank, there are some fields could not be read at all therefore cannot fill those fields and some fields (specifically checkboxes) could not be fill.

**Comment by Mr0grog** [comment]
It seems like the properties available on `Field` instances are a pretty strict subset of the available properties (in my case, I was trying to get the `MaxLen` property for a text field). It seems important to at least have a method to get arbitrary properties by key (e.g. `fieldInstance.getEntry("MaxLen")`), though having actual class attributes (e.g. `fieldInstance.maxLength`) would be a little better :)

If there’s any help I can provide working on this, let me know.

**Comment by mritchie712** [comment]
@Khwunchai could you share your solution to write to fields?

**Comment by apatnekar** [comment]
How to you write value of a button field with PyPDF2? I couldn't find any example anywhere.

**Comment by caver456** [comment]
Hi - just a user here who would definitely be interested in using pypdf2 to replace the fdfgen-and-subprocess-call-to-pdftk workflow to fill out a pdf form (with or without the fdf middleman file).  Is this issue still being worked on?  Thanks

**Comment by MartinThoma** [comment]
I feel like this issue is too vague. We have several open topics in https://github.com/py-pdf/PyPDF2/labels/workflow-forms - I guess if all of them are done, this one is also done.
