### ISSUE TITLE
Path objects get copied with incorrect position and scale

### ISSUE THREAD

**Issue by programmarchy** [py-pdf/PyPDF2#1266]
I have PDF containing a grid, which I merge with a blank page. (The PDF was exported from PowerPoint.) However, the lines in the grid do not get faithfully reproduced. Instead, the lines get shifted over and down. See the following screenshot, with the original at 25% opacity and the output at 100% opacity:

![line_bug](https://user-images.githubusercontent.com/622192/186446326-8e3c9025-e312-444b-ba96-9c8cd9a8a159.png)

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-12.5.1-arm64-arm-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.3
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfReader, PdfWriter, PageObject

reader = PdfReader('./grid.pdf')
writer = PdfWriter()

page = reader.pages[0]
mediabox = page.mediabox
blank_page = PageObject.create_blank_page(None, mediabox.width, mediabox.height)
page.merge_page(blank_page)
page.mediabox = mediabox
writer.add_page(page)
writer.add_metadata(reader.metadata)

with open('./grid-output.pdf', 'wb') as outfile:
  writer.write(outfile)
```

[grid.pdf](https://github.com/py-pdf/PyPDF2/files/9416989/grid.pdf)

**Comment by programmarchy** [comment]
Can isolate the problem a little further:

```python
from PyPDF2 import PdfReader, PdfWriter, PageObject
from PyPDF2.generic import ContentStream, NameObject

reader = PdfReader('./grid.pdf')
writer = PdfWriter()

page = reader.pages[0]
contents = page.get_contents()
contents = ContentStream(contents, page.pdf)
page[NameObject('/Contents')] = contents
writer.add_page(page)
writer.add_metadata(reader.metadata)

with open('./grid-output.pdf', 'wb') as outfile:
  writer.write(outfile)
```

**Comment by programmarchy** [comment]
Pretty sure this boils down to a floating point precision issue.

Here's the original input stream:

```
q Q q 0 0.2400177 612 791.76 re W n /Cs1 cs 1 1 1 sc 0 792 m 612 792 l 612
0.2400177 l 0 0.2400177 l h f Q q /Cs1 cs 1 1 1 sc 0 792 m 612 792 l 612 0.00002065301
l 0 0.00002065301 l h f 12700 w 1 j /Cs1 CS 0 0 0 SC q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm 3377967 -6350 m 3377967 3885365 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm 3377967 5450181 m 3377967 7520819 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm -6350 2320006 m 6762284 2320006 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm -6350 3879015 m 6762284 3879015 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm -6350 5456531 m 6762284 5456531 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm -6350 7514469 m 6762284 7514469 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm 0 -6350 m 0 9104631 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm 6755934 -6350 m 6755934 9104631 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm -6350 0 m 6762284 0 l S Q q 0.00007874016 0 0 -0.00007874016 40.01834 754.2001
cm -6350 9098281 m 6762284 9098281 l S Q Q
```

Notice there's up to 11 decimal places e.g. `0.00007874016`.

However, this gets reduced to 5 digits by `FloatObject` in [generic/_base.py#L249](https://github.com/py-pdf/PyPDF2/blob/main/PyPDF2/generic/_base.py#L249):

```python
o = f"{self:.5f}"
```

Changing `FloatObject` from 5 digits to 12 digits of precision fixes the issue:

```python
o = f"{self:.12f}"
```

So I think a fix would be pretty simple, but the question becomes what is the correct precision to use. I have Adobe PDF Reference Version 1.7 from 2006 on hand, which says in Appendix C:

<img width="505" alt="Screen Shot 2022-08-24 at 3 38 28 PM" src="https://user-images.githubusercontent.com/622192/186518771-d22d54a0-d5ba-4b86-9b6f-d040d5e142dd.png">

That matches the current implementation, _but_ this is pretty old so I imagine Acrobat may use higher precision now, and other applications like Microsoft PowerPoint are generating PDFs that have 11 decimal places, so this will occur in the wild.

Thoughts on how many decimal places should be included? Should it be configurable?

**Comment by MartinThoma** [comment]
Thank you for opening the issue and a pr ❤️

I'm currently on vacation, but I'll have a look next week. I want to see what the pdf standard says about floats.

Do we need to use decimal in the first place? Is there any benefit to use decimal within pdf?

**Comment by programmarchy** [comment]
You're welcome, and sounds good. Hope you enjoy your vacation.

Here's what I found in the PDF standard when I looked, which pointed me to the table in Appendix C posted earlier:

<img width="479" alt="3 2 2 Numeric Objects" src="https://user-images.githubusercontent.com/622192/186713197-af86ffe5-6414-4269-8b5d-19af7ec4731e.png">

Regarding using `decimal.Decimal`, I think using it makes perfect sense, because it preserves exactly what was read from a PDF content stream. If the parser immediately converts a number token into a floating point representation, then the original precision that was specified in the file would be lost.

**Comment by pubpub-zz** [comment]
Just to complete:
![image](https://user-images.githubusercontent.com/4083478/186748327-a6915f74-b4c9-474e-9397-538a48e63e93.png)

@programmarchy approach sounds good. In order to keep always the adequate number of digits what about using str() ?:
```
    def write_to_stream(
        self, stream: StreamType, encryption_key: None | str | bytes
    ) -> None:
        stream.write(str(self))
```

**Comment by programmarchy** [comment]
@pubpub-zz Do you mean call `str` on Decimal? That was actually my first attempt, but I ran into trouble with it, because for some numbers it will use the exponential format:

```
>>> str(Decimal("0.0000000000000123123"))
'1.23123E-14'
```

The method I landed on in the PR will have the correct output:

```
>>> '{0:f}'.format(Decimal("0.0000000000000123123"))
'0.0000000000000123123'
```

**Comment by MasterOdin** [comment]
My reading of the spec is that it doesn't specify a set precision all implementations may use, rather it just gives an example of what typical implementations may use (circa 2006), but an implementation can use more or less precision and still be spec compliant.

For PyPDF2, I would take this that we should support "infinite" decimal places to be as forward facing as possible and it's more on the incoming input stream to have a reasonable amount of decimal places, but if a user wants their PDF to have every decimal to have 300 decimal points, well so be it.
