### ISSUE TITLE
ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by DL6ER** [py-pdf/PyPDF2#1270]
See https://github.com/py-pdf/PyPDF2/issues/1269 for further details, this reports another issue I've come accross.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-122-generic-x86_64-with-glibc2.29

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.3
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import PyPDF2
with open("Introduction to Programming Using Python ( PDFDrive ).pdf", "rb") as f:
  pdfreader = PyPDF2.PdfFileReader(f, strict=True)
  metadata = pdfreader.metadata
```

PDF file used above: [Introduction to Programming Using Python ( PDFDrive ).pdf](https://github.com/egyvedriyanto78/Learn-Python/blob/355daf24912356c57e8fafa6b07e5b17691c1ed0/Books/Introduction%20to%20Programming%20Using%20Python%20(%20PDFDrive%20).pdf)

## Traceback

This is the complete Traceback I see:
```
Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    metadata = pdfreader.metadata
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_reader.py", line 327, in metadata
    obj = self.trailer[TK.INFO]
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/generic/_data_structures.py", line 150, in __getitem__
    return dict.__getitem__(self, key).get_object()
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/generic/_base.py", line 163, in get_object
    obj = self.pdf.get_object(self)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_reader.py", line 1151, in get_object
    retval = read_object(self.stream, self)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/generic/_data_structures.py", line 822, in read_object
    return DictionaryObject.read_from_stream(stream, pdf, forced_encoding)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/generic/_data_structures.py", line 269, in read_from_stream
    value = read_object(stream, pdf, forced_encoding)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/generic/_data_structures.py", line 851, in read_object
    return NumberObject.read_from_stream(stream)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/generic/_base.py", line 299, in read_from_stream
    return NumberObject(num)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/generic/_base.py", line 274, in __new__
    val = int(value)
ValueError: invalid literal for int() with base 10: b''
```

**Comment by DL6ER** [comment]
Another PDF file triggering this:
- [Top_Secret_Schedule.pdf](https://github.com/hackintoanetwork/aa/blob/f8b41cbd99910f7b27efa013a2719ae25b4363f3/Top_Secret_Schedule.pdf)

**Comment by MartinThoma** [comment]
Validating the PDF with [demo.verapdf.org](https://demo.verapdf.org/):

> 	Exception: Couldn't parse stream caused by exception: PDFParser::GetXRefSection(...)can not locate xref table

So this is not a PyPDF2 bug, but a robustness issue. An exception is expected (at least in strict mode), but we could give a better one.

**Comment by DL6ER** [comment]
Thanks for sharing this URL. I tested a few PDFs I posted in my updated comment above and have seen some errors even when the PDFs can be read normally with a PDF viewer.

E.g.

> Exception: Caught unexpected runtime exception during validation caused by exception: Wrapped org.verapdf.exceptions.VeraPDFParserException: Error while parsing object : 10 0 caused by exception: Error while parsing object : 10 0 caused by exception: PDFParser::GetDictionary()invalid pdf dictonary

for [Effective Java 3rd Edition by Joshua Bloch.pdf](https://github.com/bookyue/my_books/blob/53e6378b740807dc7d18f871acbf80ee72962d31/programming_language/java/Effective%20Java%203rd%20Edition%20by%20Joshua%20Bloch.pdf)

**Comment by pubpub-zz** [comment]
this is fixed by PR #1315.
This PR can not be closed

**Comment by MartinThoma** [comment]
@pubpub-zz I guess you mean that this issue (#1270) can be closed?

**Comment by MartinThoma** [comment]
I've just noticed that we now call `logger_warning(f"FloatObject ({value}) invalid; use 0.0 instead", __name__)`  a lot of times. Actually so much that I think it affects performance.

**Comment by MartinThoma** [comment]
Oh wow, even when commenting the log lines out executing the sample takes REALLY long! Maybe I should add this to one of the performance tickets

**Comment by pubpub-zz** [comment]
I would propose you to create a new ticket to only focus on the performance issue.
output to stderr may be the issue

**Comment by pubpub-zz** [comment]
+1?

**Comment by MartinThoma** [comment]
I've moved that to https://github.com/py-pdf/PyPDF2/issues/1329 :-)
