### ISSUE TITLE
TypeError: 'NumberObject' object is not subscriptable

### ISSUE THREAD

**Issue by DL6ER** [py-pdf/PyPDF2#1273]
See https://github.com/py-pdf/PyPDF2/issues/1269 for further details.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-122-generic-x86_64-with-glibc2.29

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.3
```
## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import PyPDF2
with open("shiv_resume.pdf", "rb") as f:
  pdfreader = PyPDF2.PdfFileReader(f, strict=False)
```

PDF used above: [shiv_resume.pdf](https://github.com/shivpatankar/shivpatankar.github.io/blob/121f0889cfa1eec9096722fb08f30cf4f94358cf/media/resume/shiv_resume.pdf)

## Traceback

This is the complete Traceback I see:

```
Xref table not zero-indexed. ID numbers for objects will be corrected.
Xref table not zero-indexed. ID numbers for objects will be corrected.
Superfluous whitespace found in object header b'17' b'23'

Traceback (most recent call last):
  File "test4.py", line 3, in <module>
    pdfreader = PyPDF2.PdfFileReader(f, strict=True)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_reader.py", line 1775, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_reader.py", line 275, in __init__
    self.read(stream)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_reader.py", line 1279, in read
    self._read_xref_tables_and_trailers(stream, startxref, xref_issue_nr)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_reader.py", line 1435, in _read_xref_tables_and_trailers
    xrefstream = self._read_pdf15_xref_stream(stream)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_reader.py", line 1515, in _read_pdf15_xref_stream
    assert cast(str, xrefstream["/Type"]) == "/XRef"
TypeError: 'NumberObject' object is not subscriptable
```

**Comment by MartinThoma** [comment]
@DL6ER Thank you for sharing this issue and all the details you put in here (and in all the other issues as well) :hugs: I appreciate this a lot :heart:

**Comment by MartinThoma** [comment]
One part that might be interesting to you: `PdfFileReader` was deprecated. Instead, please use `PdfReader`. The difference is only that the old PdfFileReader has `strict=True` by default and `PdfReader` has `strict=False` as default. We decided to do this change as most users will want `strict=False` and the `PdfFileReader` doesn't actually need a file - ByteIO works fine as well

**Comment by DL6ER** [comment]
Just to clarify: `with`, i.e. `close()` is also not needed?

**Comment by pubpub-zz** [comment]
the PDF file is linearized. and there seems to be some issues in reading this part of the header. I will deeper analyze it later

**Comment by MartinThoma** [comment]
Exactly! PyPDF2 takes care of that: https://github.com/py-pdf/PyPDF2/blob/main/PyPDF2/_reader.py#L272-L274

**Comment by pubpub-zz** [comment]
the problem is not directly due to "Linearization"but to other errors (generated by linearization process ???)
- the pointer to the 3rd (and potentially 4th)chained xref/trailer is invalid : in such case we will stop xref_trailer analysis
(I've fixed the /Prev enry in 2nd chained trailer to extend the test coverage)
- I've added a solution to search for an entry when the xref pointer is invalid
- I've also added the same solution to search for an entry when the id/gen is not present in the xref.

PR #1297 completed
