### ISSUE TITLE
binascii.Error: Odd-length string

### ISSUE THREAD

**Issue by DL6ER** [py-pdf/PyPDF2#1274]
See https://github.com/py-pdf/PyPDF2/issues/1269 for further details.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-122-generic-x86_64-with-glibc2.29

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.3
```
## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import PyPDF2
with open("Nano Energy 2022_2D Mosaic Heterostructure Overall Water Splitting.pdf", "rb") as f:
  pdfreader = PyPDF2.PdfFileReader(f, strict=False)
  content = " ".join([page.extractText() for page in pdfreader.pages])
```

PDF used above: [Nano Energy 2022_2D Mosaic Heterostructure Overall Water Splitting.pdf](https://github.com/hogroup/howebsite/blob/master/publications_files/Nano%20Energy%202022_2D%20Mosaic%20Heterostructure%20Overall%20Water%20Splitting.pdf)

More examples:

- [Vigneau et al (2022) Food Qual Prefer.pdf](https://github.com/yxj-HGNwmb5kdp8ewr/yxj-HGNwmb5kdp8ewr.github.io/blob/95799560c544b8ebe85fc16cca5aaf5b908d3ef6/files/Vigneau%20et%20al%20%282022%29%20Food%20Qual%20Prefer.pdf)
- [Hossain et al. - 2021 - Marine Policy.pdf](https://github.com/alj1983/iSea/blob/a0f65c60fd0bf8c0875c05e040fe88038115dab5/Literature/Hossain%20et%20al.%20-%202021%20-%20Marine%20Policy.pdf)
- [Cardello et al (2022) Food Qual Prefer.pdf](https://github.com/yxj-HGNwmb5kdp8ewr/yxj-HGNwmb5kdp8ewr.github.io/blob/95799560c544b8ebe85fc16cca5aaf5b908d3ef6/files/Cardello%20et%20al%20%282022%29%20Food%20Qual%20Prefer.pdf)

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "test4.py", line 4, in <module>
    content = " ".join([page.extractText() for page in pdfreader.pages])
  File "test4.py", line 4, in <listcomp>
    content = " ".join([page.extractText() for page in pdfreader.pages])
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1538, in extractText
    return self.extract_text()
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1510, in extract_text
    return self._extract_text(
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1146, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 22, in build_char_map
    map_dict, space_code, int_entry = parse_to_unicode(ft, space_code)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 185, in parse_to_unicode
    process_rg, process_char = process_cm_line(
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 245, in process_cm_line
    parse_bfrange(l, map_dict, int_entry)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 275, in parse_bfrange
    unhexlify(fmt % a).decode(
binascii.Error: Odd-length string
```

**Comment by DL6ER** [comment]
Another file triggering this error: [Finn_ProgNeurobio2020_updated.pdf](https://github.com/thefinnlab/thefinnlab.github.io/blob/0fc9cb0ce00fe0a34c3f17cd3dd96ee352e07081/files/Finn_ProgNeurobio2020_updated.pdf)

**Comment by DL6ER** [comment]
A very similar exception (same traceback as above, only the last step is different)
```
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 279, in parse_bfrange
    ] = unhexlify(fmt2 % c).decode("utf-16-be", "surrogatepass")
binascii.Error: Odd-length string
```
 is raised with these PDF files: [1](https://github.com/yxj-HGNwmb5kdp8ewr/yxj-HGNwmb5kdp8ewr.github.io/blob/95799560c544b8ebe85fc16cca5aaf5b908d3ef6/files/Giacalone%20Llobell%20Jaeger%20%282022%29%20Food%20Qual%20Prefer.pdf), [2](https://github.com/htcondor/htcondor.github.io/blob/470c2301476239664c3ca34d3c18f1aa5b1fece3/doc/jocs20-principles.pdf), [3](https://github.com/yxj-HGNwmb5kdp8ewr/yxj-HGNwmb5kdp8ewr.github.io/blob/95799560c544b8ebe85fc16cca5aaf5b908d3ef6/files/Giacalone%20%26%20Jaeger%20%282021%29%20Appetite.pdf), [4](https://github.com/yxj-HGNwmb5kdp8ewr/yxj-HGNwmb5kdp8ewr.github.io/blob/95799560c544b8ebe85fc16cca5aaf5b908d3ef6/files/Song%20et%20al%20%282022%29%20Food%20Res%20Int%20%28HPP%20review%29.pdf), [5](https://github.com/mikemattaUH/starter-hugo-academic/blob/5da1d978087a60603d30ee3151788f9fed87fcd0/content/publication/Matta2022%20cost_anal/Matta2022%20cost.pdf), [6](https://github.com/yxj-HGNwmb5kdp8ewr/yxj-HGNwmb5kdp8ewr.github.io/blob/95799560c544b8ebe85fc16cca5aaf5b908d3ef6/files/Song%20et%20al%20%282022%29%20Food%20Res%20Int%20%28Conjoint%20survey%29.pdf), [7](https://github.com/yxj-HGNwmb5kdp8ewr/yxj-HGNwmb5kdp8ewr.github.io/blob/95799560c544b8ebe85fc16cca5aaf5b908d3ef6/files/Jaeger%20%26%20GIacalone%20%282021%29%20Food%20Res%20Int.pdf)

**Comment by DL6ER** [comment]
Another similar one:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1538, in extractText
    return self.extract_text()
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1510, in extract_text
    return self._extract_text(
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1146, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 22, in build_char_map
    map_dict, space_code, int_entry = parse_to_unicode(ft, space_code)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 185, in parse_to_unicode
    process_rg, process_char = process_cm_line(
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 247, in process_cm_line
    parse_bfchar(l, map_dict, int_entry)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 292, in parse_bfchar
    map_to = unhexlify(lst[1]).decode(
binascii.Error: Odd-length string
```

- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/a571657bf8468e60139aab1ad6749a10ed0bd0ff/pdf/psgallery-downloads.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/bb047fe19558e8bf79cf6a40c0a00653e0320571/pdf/psgallery-downloads.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/456105978956d144b34c33f10a5822b9a578504a/pdf/psgallery-downloads.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/0c497a63d8128aa385b935aef971b22fe43f0bf5/pdf/psgallery-downloads.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/f733f877d5b65f543f82dba5370fbf2db07fbce6/pdf/psgallery-downloads-community.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/1cdc55631aaa586ac7a70e3d01f07a6ba607a994/pdf/psgallery-downloads.pdf)
- [book.pdf](https://github.com/Ishmam-Ruhan/Programming-Essential-Books/blob/1dcaac9a9a2a5680ef6cfe26b97dcfc746559e2e/book.pdf)
- [Chuyên đề 29. Phương trình mặt cầu - câu hỏi.pdf](https://github.com/KevinNitroG/Public-Archive-Files/blob/3d2906af24b71e4d7ac5d28f8c84dc498f5b030d/L%E1%BB%9Bp%2012/%28NBV%29-%C3%94N%20THI%20THPTQG%202021%20-%20THEO%20CHUY%C3%8AN%20%C4%90%E1%BB%80/CHUY%C3%8AN%20%C4%90%E1%BB%80%2029.%20PH%C6%AF%C6%A0NG%20TR%C3%8CNH%20M%E1%BA%B6T%20C%E1%BA%A6U/M%E1%BB%A8C%20%C4%90%E1%BB%98%209-10/Chuy%C3%AAn%20%C4%91%E1%BB%81%2029.%20Ph%C6%B0%C6%A1ng%20tr%C3%ACnh%20m%E1%BA%B7t%20c%E1%BA%A7u%20-%20c%C3%A2u%20h%E1%BB%8Fi.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/a571657bf8468e60139aab1ad6749a10ed0bd0ff/pdf/psgallery-downloads-community.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/429aeda577d3ac0d2bc81e9312e05c6b9c30d3b9/pdf/psgallery-downloads.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/0c497a63d8128aa385b935aef971b22fe43f0bf5/pdf/psgallery-downloads-community.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/bef585976ff8938e8da5f13925f0fb6d66e17acf/pdf/psgallery-downloads-community.pdf)
- [Chuyên đề 10. Thể tích khối chóp - đáp án.pdf](https://github.com/KevinNitroG/Public-Archive-Files/blob/3d2906af24b71e4d7ac5d28f8c84dc498f5b030d/L%E1%BB%9Bp%2012/%28NBV%29-%C3%94N%20THI%20THPTQG%202021%20-%20THEO%20CHUY%C3%8AN%20%C4%90%E1%BB%80/CHUY%C3%8AN%20%C4%90%E1%BB%80%2010.%20TH%E1%BB%82%20T%C3%8DCH%20KH%E1%BB%90I%20CH%C3%93P/M%E1%BB%A8C%20%C4%90%E1%BB%98%207-8/Chuy%C3%AAn%20%C4%91%E1%BB%81%2010.%20Th%E1%BB%83%20t%C3%ADch%20kh%E1%BB%91i%20ch%C3%B3p%20-%20%C4%91%C3%A1p%20%C3%A1n.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/456105978956d144b34c33f10a5822b9a578504a/pdf/psgallery-downloads-community.pdf)
- [ZTP-for-factories.pdf](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/42fc166e0b4bdbcab4f7f14fb069daca30b7acc7/1.0/ZTP-for-factories.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/bef585976ff8938e8da5f13925f0fb6d66e17acf/pdf/psgallery-downloads.pdf)
- [ZTP-for-factories.pdf](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/b10244a1e6fc1f75d56beb2e3aa1e3793d955e1a/1.0/ZTP-for-factories.pdf)
- [typeset.pdf](https://github.com/zopyx/print-css-rocks/blob/8f053fe32866f27fdc47915833a873f1701a4932/lessons/generated/lesson-fonts-emoji/typeset.pdf)
- [Chuyên đề 30. Phương trình mặt phẳng - đáp án.pdf](https://github.com/KevinNitroG/Public-Archive-Files/blob/3d2906af24b71e4d7ac5d28f8c84dc498f5b030d/L%E1%BB%9Bp%2012/%28NBV%29-%C3%94N%20THI%20THPTQG%202021%20-%20THEO%20CHUY%C3%8AN%20%C4%90%E1%BB%80/CHUY%C3%8AN%20%C4%90%E1%BB%80%2030.%20PH%C6%AF%C6%A0NG%20TR%C3%8CNH%20M%E1%BA%B6T%20PH%E1%BA%B2NG/M%E1%BB%A8C%20%C4%90%E1%BB%98%209-10/Chuy%C3%AAn%20%C4%91%E1%BB%81%2030.%20Ph%C6%B0%C6%A1ng%20tr%C3%ACnh%20m%E1%BA%B7t%20ph%E1%BA%B3ng%20-%20%C4%91%C3%A1p%20%C3%A1n.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/f733f877d5b65f543f82dba5370fbf2db07fbce6/pdf/psgallery-downloads.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/1cdc55631aaa586ac7a70e3d01f07a6ba607a994/pdf/psgallery-downloads-community.pdf)
- [ZTP-for-factories.pdf](https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/305089bf55d3ec82e0566c9e361173aace734223/1.0/ZTP-for-factories.pdf)
- [Chuyên đề 31. Phương trình đường thẳng- câu hỏi.pdf](https://github.com/KevinNitroG/Public-Archive-Files/blob/3d2906af24b71e4d7ac5d28f8c84dc498f5b030d/L%E1%BB%9Bp%2012/%28NBV%29-%C3%94N%20THI%20THPTQG%202021%20-%20THEO%20CHUY%C3%8AN%20%C4%90%E1%BB%80/CHUY%C3%8AN%20%C4%90%E1%BB%80%2031.%20PH%C6%AF%C6%A0NG%20TR%C3%8CNH%20%C4%90%C6%AF%E1%BB%9CNG%20TH%E1%BA%B2NG/M%E1%BB%A8C%20%C4%90%E1%BB%98%209-10/Chuy%C3%AAn%20%C4%91%E1%BB%81%2031.%20Ph%C6%B0%C6%A1ng%20tr%C3%ACnh%20%C4%91%C6%B0%E1%BB%9Dng%20th%E1%BA%B3ng-%20c%C3%A2u%20h%E1%BB%8Fi.pdf)
- [Chuyên đề 31. Phương trình đường thẳng- đáp án-p2.pdf](https://github.com/KevinNitroG/Public-Archive-Files/blob/3d2906af24b71e4d7ac5d28f8c84dc498f5b030d/L%E1%BB%9Bp%2012/%28NBV%29-%C3%94N%20THI%20THPTQG%202021%20-%20THEO%20CHUY%C3%8AN%20%C4%90%E1%BB%80/CHUY%C3%8AN%20%C4%90%E1%BB%80%2031.%20PH%C6%AF%C6%A0NG%20TR%C3%8CNH%20%C4%90%C6%AF%E1%BB%9CNG%20TH%E1%BA%B2NG/M%E1%BB%A8C%20%C4%90%E1%BB%98%209-10/Chuy%C3%AAn%20%C4%91%E1%BB%81%2031.%20Ph%C6%B0%C6%A1ng%20tr%C3%ACnh%20%C4%91%C6%B0%E1%BB%9Dng%20th%E1%BA%B3ng-%20%C4%91%C3%A1p%20%C3%A1n-p2.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/429aeda577d3ac0d2bc81e9312e05c6b9c30d3b9/pdf/psgallery-downloads-community.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/259613e76380496102ba02ce9bcf1ee709c048ae/pdf/psgallery-downloads-community.pdf)
- [psgallery-downloads.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/259613e76380496102ba02ce9bcf1ee709c048ae/pdf/psgallery-downloads.pdf)
- [psgallery-downloads-community.pdf](https://github.com/jdhitsolutions/PSGalleryReport/blob/bb047fe19558e8bf79cf6a40c0a00653e0320571/pdf/psgallery-downloads-community.pdf)

They all seem to be "valid" as in I can read them with a normal PDF viewer.

**Comment by Butterfly** [comment]
> They all seem to be "valid" as in I can read them with a normal PDF viewer.

I have an observation. My apologies if it has already been documented. I really want to help because this is such a happy little corner of the Internet. For now, about the only thing I have knowledge to do is test drive PDFs as they're offered up.

So I was downloading a few to have on hand. My method is to click the email URL that then opens up to a Github page for the corresponding PDF file. When I do that, Github most often responds, "Unable to render code block." It seems notable because one file.. and so far only that one file.. did open up and was readable on its own Github page.

Decided to mention this because it happened. I figure maybe other Users might just be right clicking and saving so they wouldn't see that difference in display occurring.

Because it's occurring across a variety of sources, wouldn't it be cool if this Github trips over some super simple tweak that addresses a minuscule code bug that affects a huge portion of the World's PDF file issues. :fireworks: :partying_face:

**Comment by DL6ER** [comment]
Thanks for your comment. I'm my experience

> Unable to render code block

isn't a very reliable indicator. I've seen it quite a few times for PDF files that were actually okay and a (sometimes "a few") page refreshings later we can actually see the preview.

**Comment by pubpub-zz** [comment]
the problem is similar to #1285, however some files helped to robustified the mod 👍  😊
