### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by DL6ER** [py-pdf/PyPDF2#1278]
See https://github.com/py-pdf/PyPDF2/issues/1269 for further details.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-122-generic-x86_64-with-glibc2.29

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.3
```
## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfReader

with open("Work Flow From Check to QA.pdf", "rb") as f:
  reader = PdfReader(f, strict=False)
  content = " ".join([page.extract_text() for page in reader.pages])
```

PDF used above: [Work Flow From Check to QA.pdf](https://github.com/AlvinSk413/EsskayTools/blob/2184f45c9110ce7d9b544a30931adaa8daad59bb/Utility%20Tool/Utility/NCM/Work%20Flow%20From%20Check%20to%20QA.pdf)

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    content = " ".join([page.extract_text() for page in reader.pages])
  File "test.py", line 4, in <listcomp>
    content = " ".join([page.extract_text() for page in reader.pages])
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1510, in extract_text
    return self._extract_text(
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1444, in _extract_text
    process_operation(operator, operands)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1258, in process_operation
    float(operands[5]),
IndexError: list index out of range
```

**Comment by pubpub-zz** [comment]
for local ref
[Work Flow From Check to QA.pdf](https://github.com/py-pdf/PyPDF2/files/9432350/Work.Flow.From.Check.to.QA.pdf)

**Comment by pubpub-zz** [comment]
The page contains an array of content stream. They have to be reassembled adding line breaks.  PR #1281 will fix this issue

**Comment by MartinThoma** [comment]
Thank you for reporting the issue @DL6ER ! I'll release a PyPDF2 version with the fix on Sunday to PyPI.

**Comment by MartinThoma** [comment]
We value good error reports @DL6ER! I can add you to https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html if you want :-)

**Comment by DL6ER** [comment]
@MartinThoma Sure, you can add me if your want. I will "contribute" some more issues over the next days ;-)

**Comment by MartinThoma** [comment]
You're added :-) (It might take ~5 minutes until the docs refresh)
