### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_object'

### ISSUE THREAD

**Issue by DL6ER** [py-pdf/PyPDF2#1295]
See https://github.com/py-pdf/PyPDF2/issues/1269 for further details, this reports another issue I've come accross.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-122-generic-x86_64-with-glibc2.29

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.3
```
## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import PyPDF2
with open("Segmentation & Activation Lab.pdf", "rb") as f:
  pdfreader = PyPDF2.PdfFileReader(f, strict=False)
  full_content = " ".join([page.extractText() for page in pdfreader.pages])
```

PDF used above: [Segmentation & Activation Lab.pdf](https://github.com/eknee/dep/blob/32bb9045f2c23c5db05ab9ac3e76d4a8e97655da/Lab%20Guides/Day%204%20-%20Activating/Segmentation%20%26%20Activation%20Lab.pdf)

## Traceback

This is the complete Traceback I see:

``` plain
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1538, in extractText
    return self.extract_text()
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1510, in extract_text
    return self._extract_text(
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_page.py", line 1146, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 21, in build_char_map
    encoding, space_code = parse_encoding(ft, space_code)
  File "/usr/local/lib/python3.8/dist-packages/PyPDF2/_cmap.py", line 124, in parse_encoding
    enc: Union(str, DictionaryObject) = ft["/Encoding"].get_object()  # type: ignore
AttributeError: 'NoneType' object has no attribute 'get_object'

```

**The PDF can be read using a normal PDF viewer** and the PDF even comes from Adobe.

Another example:
- [Day 4 - Segmentation & Activation.pdf](https://github.com/eknee/dep/blob/74b8cd412d97533c6c607d285fa0cf5e6322f088/Lab%20Guides/Day%204%20-%20Activating/Day%204%20-%20Segmentation%20%26%20Activation.pdf)

**Comment by pubpub-zz** [comment]
This file uses a /XRefStm entry that seems not be be processed currently. Work in progress
