### ISSUE TITLE
PyPDF2 failing for few documents

### ISSUE THREAD

**Issue by venuzeo** [py-pdf/PyPDF2#1304]
I have seen couple of issues with PyPDF2 version 1.25.1 with Python 2.7.18 when trying to read a pdf file. 

i)**TypeError: 'NumberObject' object has no attribute '__getitem__'.** 
This is happening when reading a pdf file. Below is the code

```python
import PyPDF2
pdf1File = open('filename1', 'rb')
pdf1Reader = PyPDF2.PdfFileReader(pdf1File, strict=False)
```

It is failing in the below line in pdf.py file under PyPDF2

```python
assert xrefstream["/Type"] == "/XRef".
```

ii)**PdfReadError: Could not find object.**

This is happening in **getObject** method in pdf.py file, where we have below piece of code

```python
# if self.strict:
       raise utils.PdfReadError("Could not find object.")
```

So, even if i am passing strict as False, it is always raising exception here.

I see in the latest version of PyPDF2 2.10.4, both the issues are fixed.
Can you please help in providing the fix in the pyPDF2 version 1.25.1, as i see from versions 2.x, PyPDF2 supports only python version 3.6+.
But, is there any way we can patch the fix in version 1.25.1 so that we can fix for python 2.7.18

**Comment by MartinThoma** [comment]
Python versions below 3.5 will not be supported by this project. Neither will I do updates on 1.x any longer (I'm open to simple PRs, but I will not accept more complex ones)

**Comment by MartinThoma** [comment]
Why don't you upgrade to Python 3.8+?
