### ISSUE TITLE
Watermark Sometimes Not Overlayed

### ISSUE THREAD

**Issue by JZL** [py-pdf/PyPDF2#131]
I have two pdf files(https://dl.dropboxusercontent.com/u/24397004/To%20Share/all-trunc.tiff.pdf and https://dl.dropboxusercontent.com/u/24397004/To%20Share/multipage_tiff_example.tiff.pdf) and am overlaying a [signature watermark](https://dl.dropboxusercontent.com/u/24397004/To%20Share/sign3.pdf) on the second page(see my answer to [issue 101](https://github.com/mstamy2/PyPDF2/issues/101)). On the first one, it [works perfectly](https://dl.dropboxusercontent.com/u/24397004/To%20Share/all-trunc.tiff.signed.pdf) but on the second one it [does not](https://dl.dropboxusercontent.com/u/24397004/To%20Share/multipage_tiff_example.tiff.signed.pdf). Is there anything I can do to guarantee that it will overlay on top?

**Comment by MartinThoma** [comment]
All of the links are dead and I have examples showing that watermarking works in principle.

If anybody has those issues, please upload example files to GitHub + post example code

**Comment by JZL** [comment]
Hi,

Sorry for never responding or closing the issue all those years ago! Past me must have resolved it somehow :-)

**Comment by MartinThoma** [comment]
Hehe, all good. Just for your information: I'm the new maintainer :wave:  A couple of users are now super active in bringing PyPDF2 forward. We've added recent decryption algorithm support and drastically improved text extraction capabilities. Also some performance improvements were made.
