### ISSUE TITLE
Infinite loop while reading metadata

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/PyPDF2#1329]
When I try to read the metadata of [Effective Java 3rd Edition by Joshua Bloch.pdf](https://github.com/bookyue/my_books/blob/53e6378b740807dc7d18f871acbf80ee72962d31/programming_language/java/Effective%20Java%203rd%20Edition%20by%20Joshua%20Bloch.pdf) it takes extremely long. It might even be an infinite loop.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-125-generic-x86_64-with-debian-bullseye-sid

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.5
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfReader
import time

t0 = time.time()
reader = PdfReader("Effective Java 3rd Edition by Joshua Bloch.pdf")
t1 = time.time()
print(f"Creating PDF Reader: {t1-t0:.2f} seconds")

t0 = time.time()
metadata = reader.metadata
t1 = time.time()
print(f"Reading metadata: {t1-t0:.2f} seconds")
```

The PDF: [Effective Java 3rd Edition by Joshua Bloch.pdf](https://github.com/bookyue/my_books/blob/53e6378b740807dc7d18f871acbf80ee72962d31/programming_language/java/Effective%20Java%203rd%20Edition%20by%20Joshua%20Bloch.pdf)

**Comment by MartinThoma** [comment]
Interestingly, extracting the text works just fine:

```python

text = ""
for i, page in enumerate(reader.pages, start=1):
    t0 = time.time()
    text += page.extract_text()
    t1 = time.time()
    print(f"Reading page {i}: {t1-t0:.2f} seconds")
```

**Comment by MartinThoma** [comment]
It's the line `obj = self.trailer[TK.INFO]` that takes so long

**Comment by MartinThoma** [comment]
`generic._data_structures.read_object` seems to be the issue

**Comment by MartinThoma** [comment]
@pubpub-zz In case you have some time, I would say this is a pretty important issue.

**Comment by pubpub-zz** [comment]
Got it!
the file is corrupt within the /Info leading to infinite loop. Cope with such situation
fixed also a warning on cmap encoding

some other possible issues detected and injected

My concern is about test: the test file does not respect the licensing. I would not like to refer it for testing

**Comment by MartinThoma** [comment]
> My concern is about test: the test file does not respect the licensing.

I guess you mean the PDF document?

**Comment by pubpub-zz** [comment]
Yes

**Comment by MartinThoma** [comment]
The fix was in `PyPDF2/generic/_data_structures.py`:

The `elif tok in b"0123456789+-.":` and 
```
    else:
        raise PdfReadError("...")
```

broke the infinite loop
