### ISSUE TITLE
BUG: 'IndexError: index out of range' when using extract_text

### ISSUE THREAD

**Issue by diavral** [py-pdf/PyPDF2#1358]
I am a new user of PyPDF2 within 24 hours. Maybe it is my problem.
I got an error when using extract_text,a suggestion of extract_text and a mistake in document.

# Environment
```
(PDFProcess) E:\pyProject\PDFProcess>python -m platform
Windows-10-10.0.19041-SP0(Windows家庭中文版)
(PDFProcess) E:\pyProject\PDFProcess>python -c "import PyPDF2,sys;print(PyPDF2.__version__,sys.version,sep='###')"
2.10.9###3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
```

**PDF**-> [UnicodeCharts](https://www.unicode.org/Public/15.0.0/charts/CodeCharts.pdf)

```python
from PyPDF2 import PdfReader

reader = PdfReader("Unicode/CodeCharts_15.0.0.pdf")
page_0 = reader.pages[0]
page_0.extract_text() 
```

## Bug 
**Location**: PyPDF2/generic/_data_structures.py --> class `ContentStream(DecodedStreamObject)::__init__`
approximately in line 690, code  `if data[-1] != b"\n":` will raise `IndexError` when `data == b""`
maybe should change it to if-elif statement:
```
if len(data) ==0:pass
elif if data[-1] != b"\n": 
    data += b"\n"
```
or just change to:
```
if len(data) ==0 or data[-1] != b"\n":
    data += b"\n"
```

## Suggestion
**Location**:PyPDF2/_page.py  --> class `PageObject(DictionaryObject)::_extract_text` --> function `process_operation`  -->`elif operator == b"Tj"`:
approximately in line 1514 ,not sure yet.
when I use (fixed) page_num.extract_text() ,I got a String without appropriate separator such as '\n' to break or split lines,
I try to add a newline between `#fmt: on` and `else:return  None`
```
                # fmt: on
    text+="*LineBreak*"
else:
    return None
```
It works in pure text page,but have bad performance in other formats like table.
I have little knowledge about where is right place to add linebreaks.
So,I think it is necessary to add a new argument like `def extract_text(sep:str=""):` and then implement.

## Documentation

https://pypdf2.readthedocs.io/en/latest/user/reading-pdf-annotations.html#attachments

**Location**:docs/user/reading-pdf-annotations.md  --> Attachments
The example code has NameError, 
```python
attachments = {}
for page in reader.pages:
    if "/Annots" in page:
        for annotation in page["/Annots"]:
            subtype = annot.get_object()["/Subtype"]
            if subtype == "/FileAttachment":
                fileobj = annotobj["/FS"]
                attachments[fileobj["/F"]] = fileobj["/EF"]["/F"].get_data()
```
`for annotation`  --> `subtype = annot` --> `fileobj = annotobj`
Variables' name should be uniformed in the above example.

**Comment by MartinThoma** [comment]
@diavral Thank you for your contribution! The first bug fix you've described will be merged in a few minutes. A new version of PyPDF2 will be on PyPI on Sunday - with your fix! Good work :+1:

**Comment by MartinThoma** [comment]
Regarding your suggestion

```
                # fmt: on
    text+="*LineBreak*"
else:
    return None
```

It causes multiple severe issues (left is before, right is after applying your suggestion):

![image](https://user-images.githubusercontent.com/1658117/192080607-a42c86e3-c317-4617-9bde-b434d199c05c.png)

![image](https://user-images.githubusercontent.com/1658117/192080627-c78352bc-9b68-40f3-83c9-1eb2432ebec9.png)

**Comment by MartinThoma** [comment]
@diavral I don't understand the last part about the documentation. How should the example look like?

**Comment by MartinThoma** [comment]
(I'm closing this issue as the bug is fixed - I will still read your response :-) )

**Comment by diavral** [comment]
> @diavral I don't understand the last part about the documentation. How should the example look like?

Apologize.I think the second and third are not very important things, so the description is not clear.

For document, in docs/user/reading-pdf-annotations.md,
what I really want to say is the variable name.
\#Text and #Highlights are ok, but when it comes to #Attachments,
`annot` have three variable name, `annotation` in second for statement,`annotobj` in second if statement.
It looks weird and obviously '*undefined*'.That is why I said variables' name should be uniformed in the #Attachments example.
```python
attachments = {}
for page in reader.pages:
    if "/Annots" in page:
        for annotation in page["/Annots"]:
            subtype = annot.get_object()["/Subtype"]
            if subtype == "/FileAttachment":
                fileobj = annotobj["/FS"]
                attachments[fileobj["/F"]] = fileobj["/EF"]["/F"].get_data()
```
In addition,the second suggestion is just a thought of mine,
I think `extract_text` should have a performance like a PDF Reader Application(even just a browser like FireFox) 
that breaks lines in a paragraph of text.
```python
reader = PdfReader("Unicode/CodeCharts_15.0.0.pdf")
page_0=reader.pages[0].extract_text()
# expected:(proper text)
# , and other general information<->for a successful implementation
print(page_0[715:746],page_0[1585:1616],sep="<->")
# result:(print)
# , and othergeneral information.<->for a successfulimplementation.
```
I'm sure adding code somewhere could improve the poor performance above, 
but I know nothing about the PDF structure and how PyPDF2 parse PDF pages, so it is just an idea.(I can do nothing for it.)

Now I have a new proposal,about **type hint**, but it's a tedious work.

In docs/user/cropping-and-transforming.md #Scaling a Page (the Canvas)
```python
page=reader.pages[0]
mb = page.mediabox
page.mediabox = RectangleObject((mb.left, mb.bottom, mb.right, mb.top))
```
In fact, the code will have warnings on some IDE,
`Expected type 'Union[RectangleObject, Tuple[float, float, float, float]]', got 'Tuple[FloatObject, FloatObject, FloatObject, FloatObject]' instead`

As the `mb.left` as an example,return value is `FloatObject`,however,in class `RectangleObject`, `arr: Union["RectangleObject", Tuple[float, float, float, float]]`.
Obviously this type hint needs to be modified,although the code works.

In same file,#Page rotation
```python
writer=PdfWriter()
with open("output.pdf", "wb") as fp:
    writer.write(fp)
```
warning is `Expected type 'Union[Path, str, BytesIO, BufferedReader, BufferedWriter, FileIO]', got 'BinaryIO' instead`. 

I mentioned document and type hint because they appear in the official example, 
and I think maintainer should get them done if condition allowed. 
But obviously, these details should take a back seat to the main job :-)
