### ISSUE TITLE
PyPDF2 doesn't install pillow

### ISSUE THREAD

**Issue by pachewise** [py-pdf/PyPDF2#1390]
Running PyPDF2 from scratch and trying to extract images (via `page.images` property) throws ModuleNotFoundError.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/2257119/195187341-da6de5bb-e52e-441c-8cb3-c111abb964ee.png">

This is because my current setup doesn't have pillow installed, _and PyPDF2 doesn't install it_. My proposal is to either add an extra to the setuptools config that installs pillow, or to have this requirement more visible in the docs. 

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-12.6-x86_64-i386-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.11.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
with open("2210.03747.pdf", "rb") as your_pdf_file:
    pdf = PdfReader(your_pdf_file)
    for page in pdf.pages:
        for image in page.images:
            print(image)
```

Any PDF with xObject images; for example: https://arxiv.org/pdf/2210.03747.pdf

## Traceback

This is the complete Traceback I see:

```
x_object_obj = {'/Type': '/XObject', '/Subtype': '/Image', '/Width': 417, '/Height': 328, '/BitsPerComponent': 8, '/ColorSpace': '/DeviceRGB', '/SMask': IndirectObject(33, 0, 4575023296), '/Filter': '/FlateDecode'}

    def _xobj_to_image(x_object_obj: Dict[str, Any]) -> Tuple[Optional[str], bytes]:
        """
        Users need to have the pillow package installed.
    
        It's unclear if PyPDF2 will keep this function here, hence it's private.
        It might get removed at any point.
    
        :return: Tuple[file extension, bytes]
        """
>       from PIL import Image
E       ModuleNotFoundError: No module named 'PIL'

venv/lib/python3.10/site-packages/PyPDF2/filters.py:567: ModuleNotFoundError
```

**Comment by MartinThoma** [comment]
You're right, we should have an optional dependency for it. I'll fix that this week. Maybe simply "image". 

In the mean time, you can also install pillow manually

**Comment by pubpub-zz** [comment]
I do not know if PIL can be installed automatically : Many library do exists (some with SIMD) and also many are requiring binary compilation.

**Comment by MartinThoma** [comment]
> I do not know if PIL can be installed automatically

That depends on your system. If you look at the distribution files ( https://pypi.org/project/Pillow/#files ) you can see that there are many different Wheels (.whl). You can see against which Systems / Platforms they compile.

I would say that it should be typically no problem. If not, then the user has to compile it from source - that might work or not. We don't have control over that.

I don't see a more user friendly way. In the end, people can always choose not to install the dependency and simply not use the functions that require it (hence we should always import those in a very small scope, within the function that needs them)
