### ISSUE TITLE
Support for custom crypto routines

### ISSUE THREAD

**Issue by Trigve** [py-pdf/PyPDF2#1405]
## Explanation

I'm using PyPDF2 in embedded python (from C++ code) in which I already implement crypto functions needed (AES, ...) so there is no need for the cryptodome dependency. I have implemented the feature already and could provide the PR.

## Code Example

This change is backward compatible, that is nothing need to be changed in the user code. Only the ones which want to provide own implementations needs to.

Example from my code
```python
from PyPDF2 import PdfReader, PdfWriter, types

class CryptRC4(types.CryptBase):
    ...
	
    def encrypt(self, data: bytes) -> bytes :
        ...
	
    def decrypt(self, data: bytes) -> bytes :
        ...

class CryptAES(types.CryptProcessed):
    # Same structure as above
    ...

class CryptoProvider(types.CryptoProvider):
    """Custom crypto routines provider."""
    
    def provider_aes(self, key: bytes) -> pypdf2.types.CryptProcessed:
        ...
    
    def AES_ECB_decrypt(self, key: bytes, data: bytes) -> bytes :
        ...

    # Plus other methods

# Use custom provider; keyword-only argument
PdfReader('some.pdf',
    password = ...,
    crypto_prov = CryptoProvider()
)
```

**Comment by MartinThoma** [comment]
I want to avoid to have to maintain cryptography code. It's too easy to get something wrong and I don't have the capacity to check those things well enough.

I acknowledge that the pycryptodome-dependency is a pain in some cases.

My suggestion would be to create another package that exports `Crypto` as a package. A couple of packages do this:

* https://pypi.org/project/PyMuPDF/ , but you import `fitz`
* https://pypi.org/project/pycryptodome/ , but you import `Crypto`

This way PyPDF2 would not have to change at all and your implementation could potentially be used by other projects.

If you need help with the packaging stuff, I can support. What do you think?

**Comment by Trigve** [comment]
Agree, it's better solution.
