### ISSUE TITLE
Docs: "Full Changelog" urls are not clickable in the docs for versions > 2.4.2

### ISSUE THREAD

**Issue by aqeelat** [py-pdf/PyPDF2#1423]
Starting in version 2.6.0, the full changelog urls (the git diffs) are written as plan text (not in md url syntax) which makes them not clickable in rtd.

Can I fix it?

**Comment by MartinThoma** [comment]
I'm not sure what you mean, but I'm always open for improvements :-)

**Comment by MartinThoma** [comment]
Now I've got it - thank you :pray:  I fixed it :-)
