### ISSUE TITLE
Text Extraction occasionally adds spaces in words

### ISSUE THREAD

**Issue by BrandWest** [py-pdf/PyPDF2#1424]
The text extraction is used to extract text from a PDF to perform manipulation and regex searches on the strings.

## Environment

Ubuntu, python 3

```bash
$ python -m platform
Linux-5.15.0-52-generic-x86_64-with-glibc2.35

python 3.10.6

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.11.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```
from PyPDF2 import PdfReader

def pdfParser():
	partsOfPage = []
	text = ''

	sourceFile = 'MS365.pdf'

	def visitor_body(text, cm, tm, fontDict, fontSize):
		y = tm[5]
		if y > 50 and y < 720:
			partsOfPage.append(text)
	
	reader = PdfReader(sourceFile)
	totalPages = reader.getNumPages()
	for pageNumber in range(totalPages):
		page = reader.getPage(pageNumber)
		
		page.extract_text(visitor_text=visitor_body)
		text += ''.join(partsOfPage)
		text += "\n"
		partsOfPage = []
	print(text)

#main
if __name__ == '__main__':
	pdfParser()

```
[MS365.pdf](https://github.com/py-pdf/PyPDF2/files/9944959/MS365.pdf)

The specific location is page 19 string: "1.3 (L1) Ensure modern authentication for SharePoint applic ations is required (Automated)" Please don't add to your tests.

## Traceback
N/A The program does not crash.

**Comment by arc12** [comment]
I have found what I think is the same problem occurring MANY times in PDF files which appear to be exports from a MS Word original. For example, in the attached document on "Page 5" (4th page), extracts to the following:
School Education included as a MMP under NeGP
School Education has been included as a Mission Mod e Project (MMP) under the
National e-Governance Plan (NeGP) by the Apex Commi ttee for the NeGP. The MMP
is focused on Primary, Secondary, and Higher Second ary education. A MMP by
design has to cover a multitude of stakeholders in the ecosystem and arrive at a set
of stakeholder centric services that have a measura ble outcome/ impact over an
agreed project timeframe.

Note the spurious spaces in "Mode", "Committee", "Secondary", "measurable". 
[Core-Scope-Document for digital school.pdf](https://github.com/py-pdf/PyPDF2/files/9951908/Core-Scope-Document.for.digital.school.pdf)

**Comment by pubpub-zz** [comment]
for your knowledge, the text can be often cut in chunks. the distance is currently not calculated and space adding is currently calculated based on some extrapolations. some improvements/developments should but will require a little of time

**Comment by BrandWest** [comment]
A work around was to:
1. Open PDF in document viewer
2. Select the print icon
3. Print to file
4. Select output format PDF
5. Print

This removed the issue for the PDF's I was working with,
