### ISSUE TITLE
How to remove bookmarks/outlines?

### ISSUE THREAD

**Issue by pubpub-zz** [py-pdf/PyPDF2#1428]
### Discussed in https://github.com/py-pdf/PyPDF2/discussions/1427

<div type='discussions-op-text'>

<sup>Originally posted by **mitchpaulus** November  8, 2022</sup>
I'm looking to remove existing bookmarks/outlines from a PDF when merging. There is the `add_outline_item` but I did not see any methods corresponding to removal. A simple web search didn't turn up anything useful. 

Is there a canonical way to do this within PyPDF2?</div>

**Comment by MartinThoma** [comment]
Did #1432 fix this?

**Comment by pubpub-zz** [comment]
Correct
