### ISSUE TITLE
Possibility to completely remove /DecodeParms

### ISSUE THREAD

**Issue by AlexMatiash** [py-pdf/PyPDF2#1434]
## Explanation

It seems that there is no way to completely remove /DecodeParms when it is not needed anymore. The best result I'm able to achieve is 

`/DecodeParms null`

with:
```
if len(decodeParams) == 0:
     xObjectChild[NameObject(StreamAttributes.DECODE_PARMS)] = NullObject()
else:
    xObjectChild[NameObject(StreamAttributes.DECODE_PARMS)] = getObjectFromDecodeParams(decodeParams)
```

It would be great to have something like:

```python
# something like

xObjectChild.remove(NameObject(StreamAttributes.DECODE_PARMS))

# or

xObjectChild[NameObject(StreamAttributes.DECODE_PARMS)] = EmptyObject() # that actually removes corresponding attribute

```

**Comment by pubpub-zz** [comment]
you can do this using `del`:
`del xObjectChild[StreamAttributes.DECODE_PARMS]`
you don't even need to call NameObject

**Comment by AlexMatiash** [comment]
> you can do this using `del`: `del xObjectChild[StreamAttributes.DECODE_PARMS]` you don't even need to call NameObject

Thank you!
