### ISSUE TITLE
Documentation: Small fixes in dev page

### ISSUE THREAD

**Issue by pavlidvg** [py-pdf/PyPDF2#1436]
I'm currently in the process of familiarizing myself with the code and I've read some of the developer documentation page as well as a few other minor problems in other pages. So far the list includes:

1) Typos in **"The PDF Format"** page, when explaining `xref` tables
2) Missing link on testing on the **"Developer Intro"** page

I can fix through these minor changes in the future, as well as try to add a bit od documentation wherever needed if that's not an issue. I am just busy with actually understanding the codebase so I'm leaving it as an Issue if anyone is interested

**Comment by MartinThoma** [comment]
(2) is fixed.

**Comment by MartinThoma** [comment]
I guess #1438 fixed (1). Thank you @pavlidvg :-)
