### ISSUE TITLE
ReadTheDocs doesn't contain latest docs from GitHub repo

### ISSUE THREAD

**Issue by yasoob** [py-pdf/PyPDF2#1455]
I was reading the docs on RTD and observed that there was a mistake in the [`PageObject` module documentation](https://pypdf2.readthedocs.io/en/latest/modules/PageObject.html#PyPDF2._page.PageObject.extract_text). It states the following about `visitor_text`: 

> It has three arguments: text,
    current transformation matrix and text matrix.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/3696393/204139994-b7554ac6-2874-4af7-a3c4-0081711a30fb.png">
 
I confirmed that I was on the latest docs page:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/3696393/204140061-2eae62c8-9eee-4b1e-be19-8e0a52876608.png">

But when I came to GitHub to submit a PR, I saw that the docs were [already fixed here](https://github.com/py-pdf/PyPDF2/blob/main/PyPDF2/_page.py#L1298-L1302):

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/3696393/204140093-bccf4453-5108-418c-8cba-cc3d5e16d0c5.png">

It seems like the latest docs have not been deployed from GitHub to RTD.

**Comment by MartinThoma** [comment]
Is that change already in a release?

I would need to check, but I guess read the docs does a pip install from pypi. Not sure if that is the most reasonable

https://pypdf2.readthedocs.io/en/latest/modules/PageObject.html

**Comment by MasterOdin** [comment]
The latest tag should correspond (by default) with the latest commit on `main` branch, and can verified as such at https://readthedocs.org/projects/pypdf2/builds/. 

Looking at the latest build, it does indeed use the latest git commit, but that the `PageObject` page has been broken for some amount of time:

```
/home/docs/checkouts/readthedocs.org/user_builds/pypdf2/checkouts/latest/PyPDF2/_page.py:docstring of PyPDF2._page.PageObject.extract_text:22: ERROR: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pypdf2/checkouts/latest/PyPDF2/_page.py:docstring of PyPDF2._page.PageObject.extract_text:25: ERROR: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pypdf2/checkouts/latest/PyPDF2/_page.py:docstring of PyPDF2._page.PageObject.extract_text:28: ERROR: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pypdf2/checkouts/latest/PyPDF2/_writer.py:docstring of PyPDF2.PdfWriter.open_destination:7: ERROR: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pypdf2/checkouts/latest/PyPDF2/_page.py:docstring of PyPDF2._page.Transformation:21: CRITICAL: Unexpected section title.
```

and maybe this explains why it doesn't show any version after 2.3.0 in that little modal on the site. Not sure if there's an easy way to have RTD backfill versions if that was desired.

**Comment by MartinThoma** [comment]
Readthedocs was building correctly. The issue was that we had two times almost exactly the same docstring. See #1485.

**Comment by MasterOdin** [comment]
@MartinThoma would you want a CI workflow that validates the sphinx build works, as hopefully a better signal to catch things breaking as doesn't seem like RTD offers a good way to monitor?

**Comment by MartinThoma** [comment]
Nothing was broken. We were just looking at the wrong function.

**Comment by MartinThoma** [comment]
Sphinx lets you know if the build fails ... but we could add a readthedocs-badge to the readme (replacing the current documentation badge)

https://docs.readthedocs.io/en/stable/badges.html
