### ISSUE TITLE
Citation information for PyPDF2

### ISSUE THREAD

**Issue by sickofhoneysuckle** [py-pdf/PyPDF2#1475]
## Explanation

Hello, I was wondering how I could cite PyPDF2 in my research paper. I used the software to convert part of a corpus for an NLP project.  BibTex formatting would be preferred! Thanks!

**Comment by MartinThoma** [comment]
@sickofhoneysuckle Thanks for considering it! We need to discuss this internally (see #1476). How fast do you need it?

**Comment by sickofhoneysuckle** [comment]
Thanks for responding! I'm submitting a first draft to my PI, but I'll leave it blank for now and communicate with her that a citation is forthcoming (:  I would need it by the end of the month if possible.

**Comment by MartinThoma** [comment]
In case we don't merge #1476 until then, an acceptable one might be:

```
@misc{pypdf2,
 title         = {The {PyPDF2} library, version 2},
 author        = {Mathieu Fenniak and {PyPDF2 Contributors}},
 year          = {2022},
 url           = {https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html}
}
```

**Comment by sickofhoneysuckle** [comment]
I very much appreciate it thank you! Also thank you for all your work on this package. I wouldn't have been able to create a corpus without it (:
