### ISSUE TITLE
pdfdocencode table is wrong

### ISSUE THREAD

**Issue by jribbens** [py-pdf/PyPDF2#151]
In the _pdfDocEncoding translation table, characters 9, 10 and 13 are marked as illegal when in fact they should translate to themselves. This means that decode_pdfdocencoding() fails on all multi-line strings.

**Comment by michaelmhoffman** [comment]
+1. The PDFDocEncoding Character set is defined in Annex D of the PDF Specification 1.7. Unlike other control characters, 9, 10, and 13 are defined.

**Comment by MartinThoma** [comment]
Those map directly to ASCII, right?

So:

* 9: `\t`
* 10: `\n`
* 13: `\r`

Do you have an example PDF + code that shows the issue?

**Comment by jribbens** [comment]
@MartinThoma Yes that's right. Unfortunately I don't have an example PDF to hand 7 years later...

**Comment by MartinThoma** [comment]
Thank you for confirming :heart: 

> Unfortunately I don't have an example PDF to hand 7 years later...

Hehe, I would have been surprised if you had - but I thought I check if I'm lucky :smile: I'm currently working through all open issues / PRs
