### ISSUE TITLE
Default documentation version does not match default PyPI version

### ISSUE THREAD

**Issue by maxbeer99** [py-pdf/PyPDF2#1511]
The default and linked to Doc version ist v:latest, not v:stable which leads to discrepancies between doc and actual usage.

### Example - Merging PDFs:
The basic example in the usage guide

~~~python
merger = PdfWriter()

for pdf in ["file1.pdf", "file2.pdf", "file3.pdf"]:
    merger.append(pdf)
~~~

does not work in the current PyPI version (1.12.1) due to changes in `PdfWriter`. The corresponding example in doc v:stable

~~~python
merger = PdfMerger()

for pdf in ["file1.pdf", "file2.pdf", "file3.pdf"]:
    merger.append(pdf)
~~~
works as expected. This is obviously confusing for simple users.

### Suggested Solution:
Make v:stable the default doc version.

**Comment by MartinThoma** [comment]
Thank you for the hint!

I changed the default version and I enabled the "warning banner for non-stable / non-latest version")

**Comment by MartinThoma** [comment]
![image](https://user-images.githubusercontent.com/1658117/209195079-e2755826-374d-45b0-ac18-456ac8f54417.png)

**Comment by MartinThoma** [comment]
![image](https://user-images.githubusercontent.com/1658117/209195169-7c978f55-0c61-4675-8e90-3c4365aa68a9.png)

**Comment by MartinThoma** [comment]
@maxbeer99 If you want, I can add you to the contributors page: https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by maxbeer99** [comment]
Thank you for the quick fix. It would be nice to be added to the contributors page.

**Comment by MartinThoma** [comment]
@maxbeer99 Do you want to be added as 'maxbeer99' or with another name? Should the link go to your GitHub profile?

**Comment by maxbeer99** [comment]
maxbeer99 is fine, with link to my GitHub profile please.

**Comment by MartinThoma** [comment]
Done: https://github.com/py-pdf/pypdf/commit/377e18b3a4948f612d52671349fc5cea5a45cdf8
See https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html (might take a few minutes until the docs are built)
