### ISSUE TITLE
Add font information to PdfReader instance

### ISSUE THREAD

**Issue by tiarno** [py-pdf/PyPDF2#153]
It would be a nice enhancement to include information on what fonts are contained in a pdf and whether or not they are embedded. I believe I have the code that does it, but after looking over the code base, there is probably a smarter way to go about it.

Here is a gist link:
https://gist.github.com/tiarno/8a2995e70cee42f01e79

**Comment by LizaKoz** [comment]
Hi, this is a very cool enhancement! is it possible anyhow to get a text which is bold? thank u!

**Comment by MartinThoma** [comment]
I've added `PageObject._get_fonts()`. I will leave it private (the leading underscore) for the moment as I first want to see if/how people use it.

Please leave a comment / a :+1: if you use it :-)

**Comment by vnmabus** [comment]
Will this be converted to a public method or function at some point?

**Comment by stefan6419846** [comment]
I am not aware of any recent requests for it, thus this probably never changed. You are of course invited to propose a corresponding PR if there is indeed more interest in this being publicly available.
