### ISSUE TITLE
Allow specifying the PDF file version

### ISSUE THREAD

**Issue by mapguymike** [py-pdf/PyPDF2#162]
PyPDF2 currently writes to v1.3 (Acrobat 4.x). Is it possible to allow saving to other versions? 

We recently used the library to combine several thousands of pages into file sets (of engineering drawings). Each of the individual filenames (pages) were used as bookmarks in the set. I have found that I cannot use Acrobat X to insert or replace a page manually afterwards because it messes up the bookmarks. If I save the modified PDF using the optimized pdf option (where I can specify the version I want and in this case it would be 1.3) the bookmarks are deleted.

Before:
![image](https://cloud.githubusercontent.com/assets/3391494/5396744/89e987bc-8122-11e4-90c0-4c53dd5468bd.png)

Save as
![image](https://cloud.githubusercontent.com/assets/3391494/5396753/a64532d0-8122-11e4-8099-e68e7a2fc514.png)

After:
![image](https://cloud.githubusercontent.com/assets/3391494/5396767/b523633a-8122-11e4-8be8-6810701b4d36.png)

**Comment by akaiame** [comment]
+1
Being able to choose pdf version would be wonderful. There's quite a few things that are not compatible with older versions. It would be great even if the pdf version could simply be kept the same from the original pdfs after merging.

**Comment by MartinThoma** [comment]
This is how you can do it:

```python
from PyPDF2 import PdfReader, PdfWriter

reader = PdfReader("example.pdf")
writer = PdfWriter()
writer._header = b"%PDF-2.0"  # <--- the line you need

writer.add_page(reader.pages[0])

with open(foo, "wb) as fp:
    writer.write(fp)
```

**Comment by MartinThoma** [comment]
I think we should expose `writer._header` as `writer.pdf_header` to be consistent with the reader.

**Comment by MartinThoma** [comment]
Yes, exactly that was my thought.

At some point we might even be able not to simply take the max, but to actually tell which features belong to which version. I think it would be better to use the minimal version that supports all features which are used within the PDF - meaning a PDF which is labeled as 1.7 might actually only use 1.3 features. But that would be way more complex :smile:

**Comment by MartinThoma** [comment]
Thank you for bringing this topic up - it was implemented and will be part of the next release (probably on Sunday or on Monday)
