### ISSUE TITLE
ExtractText yields nothing for apparently good PDF

### ISSUE THREAD

**Issue by chrisinmtown** [py-pdf/PyPDF2#168]
PyPDF2 version 1.23 fails to extract any text from the first 3 pages of this PDF file:
   http://emma.msrb.org/EP295293-EP10300-EP632440.pdf

The file seems well-formed to me; both Acrobat and evince display it nicely.  The linux utility pdftotext converts it to text and I see the expected content just fine.

Here's the relevant bit of my little script:

``` python
    with open(filename, "rb") as pdf_file:
        try:
            pdf_obj = PdfFileReader(pdf_file)
            # gather properties
            prop_en = pdf_obj.getIsEncrypted()
            err = ""
            if not prop_en:
                # Look for any text on the first N pages
                prop_img = True
                prop_pg = pdf_obj.getNumPages()
                for i in xrange(min(prop_pg, 3)):
                    pagei = pdf_obj.getPage(i)
                    pageitext = pagei.extractText()
                    # Set property and stop searching at first text found
                    if len(pageitext) > 0:
                        prop_img = False
                        break
```

Is there a gotcha here that I'm missing?  Pls advise, thanks in advance for help.

**Comment by chrisinmtown** [comment]
I would like to mention that I have many unprotected, machine-searchable (i.e., non-image) PDF files like this - I just posted one link. Unlike the last issue I opened about a freak PDF with a botched header, in this case PyPDF2 fails to get text from annoyingly many of the files I'm trying to process. Thanks for listening.

**Comment by zevav** [comment]
@chrisinmtown I ran into a similar issue today; my PDF and yours are "page extraction: not allowed" according to Adobe Reader.  :(

**Comment by chrisinmtown** [comment]
@zevav thanks for the comment but please let's not confuse issues. 

Protected files are a *whole different ball of wax* and I don't expect PyPDF2 to extract anything from such files given no password.  

The link I provided above yields a PDF that is *not* password protected. On this document Adobe Acrobat makes no complaint about extracting text, it happily saves-as plain text and the result is totally usable.

**Comment by zevav** [comment]
@chrisinmtown hey, sorry to send you in the wrong direction; in Acrobat on my machine that document *does* show (document info) as "page extraction not allowed."

**Comment by chrisinmtown** [comment]
Thanks for clarifying.  Now I'm concerned, I don't want to waste anyone's time here on non-issues!

I am using Adobe Acrobat XI on Win7_x64.  With this document open in Acrobat I pick File -> Properties, switch to the Security tab of the Document Properties dialog, and there I read "Security Method: No Security", and under the restrictions everything is allowed (Printing, Changing, Copying ...).

Could there possibly be a difference in behavior between Reader and Acrobat on this document?

**Comment by zevav** [comment]
Okay, my bad:  I wrote "Acrobat" but I meant "Reader."  [Here's a screenshot](https://www.dropbox.com/s/lstoatzgftm4i7j/Screenshot%202015-01-25%2010.45.39.png?dl=1) of your file's info in that, on OS X.10.

**Comment by chrisinmtown** [comment]
I see the exact same thing in the Win7 version of Acrobat Reader XI: Document Assembly and Page Extract Not Allowed; all the rest (Content Copying ..) are Allowed.  FWIW, PyPDF2 declares this document unprotected.

I'm starting to think the Properties window is reflecting features of Acrobat Reader rather than the document, do you agree? In my tests of Reader on other PDF documents, it invariably declares "Page Extract Not Allowed".  Reader by definition cannot extract pages, right?

Just to be clear, I am sticking to my position :) that the original document is a valid PDF, unprotected, with text content, and I really would like PyPDF2 to be extended so it can handle this doc.

**Comment by zevav** [comment]
Dang, you're right!  I didn't think to check a PDF that I know PyPDF2 can extract the text of; Reader *does* indeed show that property for all PDFs.  :(

What method in PyPDF2 tells you whether or not a document is protected?

**Comment by chrisinmtown** [comment]
The relevant method on PdfFileReader is getIsEncrypted()

**Comment by Rob1080** [comment]
I realise this is an old post,  did you ever find the reason for text not being extracted?

**Comment by SallyRagab** [comment]
I faced the same problem with PyPDF2 as well but I managed to extract the text finally using pdftotext. It's relatively easier to use too.

**Comment by warriorgithub** [comment]
pdftotext library is lit :)

**Comment by Bitseat** [comment]
pdfminer3 is the best. Handles all types of pdf and returns clean text. 
https://stackoverflow.com/a/56530666/8019569

**Comment by MartinThoma** [comment]
Sadly, the PDF mentioned above is no longer reachable. I think that #924 fixed the issue and hence I close this PR.

It might also be a duplicate of the underlying cause of #242 .

If you face the same issue, please open a new bug ticket and upload a PDF with the issue (to which you must have the copyright)
