### ISSUE TITLE
mergeRotatedAroundPointPage name & mergeScaledPage parameter changed without warning

### ISSUE THREAD

**Issue by stvsmth** [py-pdf/PyPDF2#174]
Commit 101b549bb80c4e5b8795eedf6ee025d628819f07 (between v1.22 and v1.23 tags), titled **Documentation Overhaul** [changed](https://github.com/mstamy2/PyPDF2/commit/101b549bb80c4e5b8795eedf6ee025d628819f07#diff-08aeee00f4d385622e62294b4ca25ba0R1984) the `PageObject` method named `mergeRotatedAroundPointPage` to `mergeRotatedTranslatedPage`. 

Further research also indicates a change in the method signature for `mergeScaledPage`. The parameter `factor` changed to `scale`. While not personally bitten by the changed parameter name, anyone passing parameters via keywords will have an issue.

Given the commit message, I'm not sure if this was intentional. 

There was no mention of either change in the CHANGELOG.

At a minimum, I think the CHANGELOG should be updated. It would be nice if you could update the v1.23 and v1.24 tags with the updated change log and perhaps even wrapper functions that raise deprecation warnings. I do not see any other use of deprecation warnings in this project, so I am not sure this is something you would want. Of course, 1.23 and 1.24 are out in the wild, which complicates things.

On the up-side, upgrading to v1.24 fixed an error for some poorly formed PDF file that choked v1.19. So thanks for that. And I got to practice with `git bisect`.

**Comment by smbolton** [comment]
Note that my PR #310 does not address the ``mergeScaledPage`` parameter name change, just the ``mergeRotatedAroundPointPage`` function name change.

**Comment by MartinThoma** [comment]
Thank you for your contribution :heart: 

This change happened 6 years ago. For the same reason why you started this PR, I will now close it: People got used to this API (name of the methods) and changing it would break things.

I do want to introduce several breaking changes with PyPDF2 2.0 - and I would love to get some ideas / feedback on that: https://github.com/py-pdf/PyPDF2/discussions/752
