### ISSUE TITLE
PdfReadError: EOF marker not found error when opening pdf files generated from selenium snapshot

### ISSUE THREAD

**Issue by lovesh** [py-pdf/PyPDF2#177]
I am using selenium and Ghost to capture screenshots as `pdf`. The code for saving screenshot is

```
driver.get('http://localhost/report/10?page=1')
driver.save_screenshot('page1.pdf')
```

Now i can open these files in a pdf viewer(I am using Okular) and they look fine. But when i try to open them using this code

```
from PyPDF2 import PdfFileReader
input1 = PdfFileReader(open("page1.pdf", "rb"))
```

It gives error `PdfReadError: EOF marker not found`. The reason i am trying to open this file using `PdfFileReader` is that i need to merge several pdfs into one and for that i need to open these pdfs. I found a github issue https://github.com/mstamy2/PyPDF2/issues/34 and it says it was resolved but i still face this issue. My pypdf version is 1.24

**Comment by abixadamj** [comment]
I want to say, that if I read PDF with PdfFileReader, then write with PdfFileWriter, and then read with FileReader once again, I've got:

input_file = PdfFileReader(open("/tmp/zakodowany.pdf", "rb"))
---------------------------------------------------------------------------
PdfReadError                              Traceback (most recent call last)
/home/adasiek/<ipython-input-12-cb4f4869d7a1> in <module>()
----> 1 input_file = PdfFileReader(open("/tmp/zakodowany.pdf", "rb"))

/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.pyc in __init__(self, stream, strict, warndest, overwriteWarnings)
   1063             stream = BytesIO(b_(fileobj.read()))
   1064             fileobj.close()
-> 1065         self.read(stream)
   1066         self.stream = stream
   1067 

/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.pyc in read(self, stream)
   1665         while line[:5] != b_("%%EOF"):
   1666             if stream.tell() < last1K:
-> 1667                 raise utils.PdfReadError("EOF marker not found")
   1668             line = self.readNextEndLine(stream)
   1669             if debug: print("  line:",line)

PdfReadError: EOF marker not found

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by mstrcnvs** [comment]
Hi there,

How this issue ended up?

I'm facing the exact same problem right now.

Thank you :)

**Comment by vivekpd15** [comment]
+1

**Comment by fractos** [comment]
I just hit this problem too. Please could this be fixed in the pip install version soon?

**Comment by beruic** [comment]
Again, this issue would be REALLY nice to have fixed in a pip release.

I'm getting a bunch of auto-generated PDFs from customers, where the `%%EOF` is not within the last 1 kb, so the fix in PR #321 should be applied.
Not that it is elegant, but the current code is not either, and it would get us onwards.

**Comment by kut** [comment]
same issue here, would be fixed by PR #321...

**Comment by myleshk** [comment]
Same issue, please fix.

**Comment by joseprieto** [comment]
I face the same issue! Anyone has found the way to solve it?

**Comment by myleshk** [comment]
I just use `pikepdf` to preprocess the PDF file.
```
from pikepdf import Pdf

def _fixFile(filename, input_base_dir):
    """
    Worker
    """
    file_basename = filename[:-4]
    original_input_file_path = path.join(input_base_dir, filename)
    tmp_output_file_path = path.join(
        input_base_dir, file_basename+".pdf.tmp"
    )
    final_input_file_path = path.join(
        input_base_dir, file_basename+".pdf.old"
    )

    pdf = Pdf.open(original_input_file_path)
    new_pdf = Pdf.new()
    for page_obj in pdf.pages:
        new_pdf.pages.append(page_obj)
    new_pdf.save(tmp_output_file_path)

    rename(original_input_file_path, final_input_file_path)
    rename(tmp_output_file_path, original_input_file_path)
    print(f"Fixed {filename}")
```

**Comment by guillaume-uH57J9** [comment]
Hi,
Same issue where with a PDF where %EOF is not within the last 1kb, there's actually about 9.5k of data after %EOF. 
The document is an invoice provided by a 3rd party, according to metadata it was generated by "dompdf 0.8.6 + CPDF".

It looks like a fix was submitted and a PR have been pending for some years, is this non-longer maintained?

**Comment by preetu098** [comment]
PyPDF2.utils.PdfReadError: EOF marker not found

show this issue

**Comment by preetu098** [comment]
please help

**Comment by MartinThoma** [comment]
Can somebody share a PDF that has this issue?

**Comment by guillaume-uH57J9** [comment]
Certainly @MartinThoma, you can download it from there : 
https://drop.infini.fr/r/_wVhZCtDBy#npqf9V4POgFy1bzo1FGs3zDdXF/c0IZW9Fti7R0jvEo=

Github throws this error when processing the file so I had to upload is somewhere else : "Something went really wrong, and we can't process  that file. "

Here's how I created the file, in case you want to recreate it locally : 
* Type "Hello world" in a text editor
* Print to PDF
* Add some bytes at the end of file file, using command `dd if=/dev/zero bs=1024 count=20 >> helloworld.pdf`

**Comment by guillaume-uH57J9** [comment]
Thanks for the merge!
