### ISSUE TITLE
pdf.py line 1667 asserts False if no xref table found, need better message

### ISSUE THREAD

**Issue by chrisinmtown** [py-pdf/PyPDF2#181]
I'm using version 1.23 of PyPDF2. Several of my PDF documents have caused execution to reach line 1667 of pdf.py which asserts False.  The comment immediately preceding is "# no ref table found at specified location".  Please consider revising so it raises an exception with a message, instead of just stopping cold.  Thanks.

**Comment by eshellman** [comment]
fixed in PR#155 version 1.24 should do it for you.

**Comment by fgeek** [comment]
@chrisinmtown Could you please test this again with your PDF and with PyPDF2 version 1.24, thank you?

**Comment by chrisinmtown** [comment]
I have upgraded to 1.24 and the problem has not been hitting me, so I believe the fix has helped me.

Very sorry that this bug report was so brief, clearly I should have included a link to the offending PDF, then both you and I could have verified the fix.  Dang users, who needs 'em  :/

**Comment by fgeek** [comment]
Thanks :)

**Comment by chrisinmtown** [comment]
Backfill: please download and test on the following file. PyPDF2 version 1.24 hits pdf.py:1674 "assert False" when I test it. Thanks.

    http://emma.msrb.org/MS36156-MS187837-MS610003.pdf

**Comment by MartinThoma** [comment]
I think think this issue was fixed. If you still encounter it, please share a Traceback with a recent PyPDF2 version + some example code. If you can, please also share the PDF.
