### ISSUE TITLE
TypeError: 'NumberObject' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by fgeek** [py-pdf/PyPDF2#185]
With following fuzzed sample file PyPDF2 version 1.24 crashes with TypeError. PyPDF2 should graceful exit instead. Fuzzed with [American fuzzy lop](http://lcamtuf.coredump.cx/afl/) and using [https://bitbucket.org/jwilk/python-afl](python-afl) project as instrumentation component.

http://bugs.fi/media/afl/pypdf2/pypdf2-afl-typeerror.pdf
39b0fa87f0ac47b5b1ee267bff4188d1dd150e91  pypdf2-afl-typeerror.pdf

```
Traceback (most recent call last):
  File "crasher.py", line 15, in <module>
    print "document has %d pages." % input1.getNumPages()
  File "/home/fgeek/utils/builds/python/2.7.9/lib/python2.7/site-packages/PyPDF2/pdf.py", line 983, in getNumPages
    self._flatten()
  File "/home/fgeek/utils/builds/python/2.7.9/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1281, in _flatten
    pages = catalog["/Pages"].getObject()
TypeError: 'NumberObject' object has no attribute '__getitem__'
```

**Comment by Wolfium** [comment]
A long time ago, but I am seeing this error when running in Windows, nor the case on Linux, same input PDF file ran under docker shared volume on host it works, when run in VSCode as local windows host it fails with this error.

I checked and same version installed with PIP.

Any help would be appreciated...

**Comment by MartinThoma** [comment]
Could somebody please add a minimal example what was done / lead to the crash? I guess simply reading the PDF with the PyPDF2 file reader?

**Comment by MartinThoma** [comment]
The linked PDF cannot be opened with Chromes PDF reader. That means it's severely broken. I'll close this ticket as I don't think there is anything we can do.
