### ISSUE TITLE
Enhance len(reader.pages) to report pages in encrypted PDF document

### ISSUE THREAD

**Issue by chrisinmtown** [py-pdf/PyPDF2#190]
I'm working with some PDF files for which the PyPDF2.PdfFileReader#getIsEncrypted() method returns True.  In these cases, the getNumPages() returns no information. This issue is to request that the method be enhanced so it returns the proper page count even if the file is encrypted.

Contrast this behavior with the Poppler library's pdfinfo command, which reports the encryption status yes/no and always yields the number of pages in the document. 

I'm using Python 2.7, PyPDF v1.24.

**Comment by MartinThoma** [comment]
It seems to me that this feature was added:

```python
    def _get_num_pages(self) -> int:
        """
        Calculate the number of pages in this PDF file.

        :return: number of pages
        :raises PdfReadError: if file is encrypted and restrictions prevent
            this action.
        """
        # Flattened pages will not work on an Encrypted PDF;
        # the PDF file's page count is used in this case. Otherwise,
        # the original method (flattened page count) is used.
        if self.is_encrypted:
            return self.trailer[TK.ROOT]["/Pages"]["/Count"]  # type: ignore
        else:
            if self.flattened_pages is None:
                self._flatten()
            return len(self.flattened_pages)  # type: ignore
```
