### ISSUE TITLE
PyPDF2.utils.PdfReadError: Unexpected destination '/__WKANCHOR_2'

### ISSUE THREAD

**Issue by hannal** [py-pdf/PyPDF2#193]
- PyPDF2 1.24

The exception occurs when building outline for a pdf generated by wkhtmltopdf. 

```python
from PyPDF2 import PdfFileMerger, PdfFileReader

merger = PdfFileMerger()
merger.append(PdfFileReader(file('test.pdf', 'rb')))  # Unexpected destination

_pdf = PdfFileReader(file('a.pdf', 'rb'))
_pdf.outlines  # same as the exception
```

I got a below error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kay/Workspace/.virtualenv/rsquare-doc/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1145, in <lambda>
    outlines = property(lambda self: self.getOutlines(), None, None)
  File "/Users/kay/Workspace/.virtualenv/rsquare-doc/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1180, in getOutlines
    outline = self._buildOutline(node)
  File "/Users/kay/Workspace/.virtualenv/rsquare-doc/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1224, in _buildOutline
    raise utils.PdfReadError("Unexpected destination %r" % dest)
PyPDF2.utils.PdfReadError: Unexpected destination '/__WKANCHOR_2'
```

Any help on this would be appreciated. Thank you.

**Comment by JosefKaser** [comment]
I had the same problem. For a quick and dirty fix I commented out the lines 1225 and 1226 in the file pdf.py of the package PyPDF2 which raise the exception:

        # if destination found, then create outline
        if dest:
            if isinstance(dest, ArrayObject):
                outline = self._buildDestination(title, dest)
            elif isinstance(dest, Str) and dest in self._namedDests:
                outline = self._namedDests[dest]
                outline[NameObject("/Title")] = title
            # else:
            #     raise utils.PdfReadError("Unexpected destination %r" % dest)
        return outline

**Comment by hannal** [comment]
Actually, I also bypass the issue with below codes like your fix. :)

```
           if isinstance(dest, ArrayObject):
                outline = self._buildDestination(title, dest)
            elif isinstance(dest, Str) and dest in self._namedDests:
                outline = self._namedDests[dest]
                outline[NameObject("/Title")] = title
            elif isinstance(dest, NameObject):
                pass
            else:
                raise utils.PdfReadError("Unexpected destination %r" % dest)
```

**Comment by MrCsabaToth** [comment]
+1 I have the same issue

**Comment by MrCsabaToth** [comment]
Commenting out the exception raise helped to me too, I tried to downgrade to pypdf2 1.23, that has the same issue.

**Comment by pedroteixeira** [comment]
Sadly, me too, split of wkhtmltopdf only worked with ghostscript or pdftk (pdftk has easier api)

**Comment by MrCsabaToth** [comment]
I'm looking at the PDF files, not all of them trigger this exception, although most of them have these WKANCHORs in them. So I have PDF which have WKANCHORs, but doesn't trip up pypdf2.

**Comment by MrCsabaToth** [comment]
I wonder if I can parameterize wkhtmltopdf in a way that it generates such pdfs which pypdf2 always accepts.

**Comment by MrCsabaToth** [comment]
I like hannal's workaround better than just simply comment out the raise.

**Comment by JGONGSQ** [comment]
I got the same problem and no solution for now.

**Comment by MrCsabaToth** [comment]
@JGONGSQ What do you mean no solution? It's certainly a hack, but there are some code modification proposals up there which work.

**Comment by JGONGSQ** [comment]
@MrCsabaToth Modify the package code is the last thing I'm going to do. Can we just fix that or its wkhtmltopdf's problem?

**Comment by hannal** [comment]
@JGONGSQ check out https://github.com/hannal/PyPDF2 . I forked PyPDF2 to bypass the problem.

**Comment by JGONGSQ** [comment]
@hannal  Thx, I finally changed the package code...

**Comment by MrCsabaToth** [comment]
@JGONGSQ I agree, it's a really dirty hack. I can imagine that other package generates invalid PDF, I don't know enough about the file format to judge that. One of the package needs to be fixed. I guess wkhtml2pdf is the bigger dog. I *really* don't like package code modification :P

**Comment by gone** [comment]
I'm hitting this one too - I'm going to switch to hannal's fork

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by aristotll** [comment]
I encounter the same question.

**Comment by Wendong-Wu** [comment]
Will this be fixed in the next release?

**Comment by StErMi** [comment]
When will this be fixed?

**Comment by ibalex** [comment]
Setting 'import_bookmarks=False', if the outline is not needed may fix your issue.
`merger.append(PdfFileReader(file('test.pdf', 'rb')), import_bookmarks=False)`

**Comment by fabio-santos-movile** [comment]
UP!

**Comment by josifoski** [comment]
Thank's to @ibalex
This is temporary workaround
Setting 'import_bookmarks=False' (if the outline is not needed) may fix your issue.  
merger.append(PdfFileReader(file('test.pdf', 'rb')), import_bookmarks=False)

**Comment by haroonkhan02** [comment]
Raise utils.PdfReadError (“ could not read malformed PDF File”) 
This error is striking everytime i run the simple pypdf2 code

**Comment by lee1043** [comment]
Had same issue and solution of @ibalex works. Thank you!

**Comment by manney** [comment]
Still getting this issue.  The workaround from @ibalex works for me.  :slightly_smiling_face: 

How is it that a bug reported in 2015 is still causing headaches?

**Comment by joelewis43** [comment]
I'm also still getting this issue. Is there any chance for a resolution or is the workaround from @ibalex the accepted solution?

**Comment by talhadn** [comment]
i am having the same issues

**Comment by retsyo** [comment]
I met similar case `PyPDF2.utils.PdfReadError: Unexpected destination '/__WKANCHOR_ea'` with latest cloned PyPDF2, while I try to use
```python
def copy_bookmarks(src, dest, outlines=None, parent=None):
    """Copy the bookmarks from src to dest.

    Args:
        src (PyPDF2.PdfFileReader): The source.
        dest (PyPDF2.PdfFileWriter): The destination.
        outlines (list of PyPDF2.generic.Destination): The outlines to be
            copied (for recursive calls). If None, then uses all elements
            returned by``src.getOutlines()``.
        parent (PyPDF2.generic.IndirectObject): The parent bookmark (if
            outlines are nested).
    """
    if outlines is None:
        outlines = src.getOutlines()
    for current, next in itertools.zip_longest(outlines, outlines[1:]):
        if is_destination(current):
            bookmark = dest.addBookmark(current.title,
                                        src.getDestinationPageNumber(current),
                                        parent=parent)
            if next and not is_destination(next):
                copy_bookmarks(src, dest, outlines=next, parent=bookmark)

```

**Comment by LamerLink** [comment]
Going off of the solution proposed by @hannal, if you don't want to overwrite the PyPDF2 source package, you can just copy the following.

I put it in another file name ``__pypdf2_fix`` personally, that way I can do ``from __pypdf2_fix import NewPdfFileReader as PdfFileReader, NewPdfFileMerger as PdfFileMerger`` on any scripts that need this fix.

```python
from PyPDF2 import PdfFileReader, PdfFileMerger
from PyPDF2.pdf import ArrayObject, NameObject
from PyPDF2.utils import isString
from PyPDF2.merger import _MergedPage
from io import BytesIO
from io import FileIO as file
StreamIO = BytesIO

class NewPdfFileReader(PdfFileReader):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
def _newBuildOutline(self, node):
    dest, title, outline = None, None, None
    
    if "/A" in node and "/Title" in node:
        # Action, section 8.5 (only type GoTo supported)
        title  = node["/Title"]
        action = node["/A"]
        if action["/S"] == "/GoTo":
            dest = action["/D"]
    elif "/Dest" in node and "/Title" in node:
        # Destination, section 8.2.1
        title = node["/Title"]
        dest  = node["/Dest"]
        
    # if destination found, then create outline
    if dest:
        if isinstance(dest, ArrayObject):
            outline = self._buildDestination(title, dest)
        elif isString(dest) and dest in self._namedDests:
            outline = self._namedDests[dest]
            outline[NameObject("/Title")] = title
        elif isinstance(dest, NameObject):
            pass
        else:
            raise utils.PdfReadError("Unexpected destination %r" % dest)
    return outline

NewPdfFileReader._buildOutline = _newBuildOutline

class NewPdfFileMerger(PdfFileMerger):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
def newMerge(self, position, fileobj, bookmark=None, pages=None, import_bookmarks=True):
        """
        Merges the pages from the given file into the output file at the
        specified page number.

        :param int position: The *page number* to insert this file. File will
            be inserted after the given number.

        :param fileobj: A File Object or an object that supports the standard read
            and seek methods similar to a File Object. Could also be a
            string representing a path to a PDF file.

        :param str bookmark: Optionally, you may specify a bookmark to be applied at
            the beginning of the included file by supplying the text of the bookmark.

        :param pages: can be a :ref:`Page Range <page-range>` or a ``(start, stop[, step])`` tuple
            to merge only the specified range of pages from the source
            document into the output document.

        :param bool import_bookmarks: You may prevent the source document's bookmarks
            from being imported by specifying this as ``False``.
        """

        # This parameter is passed to self.inputs.append and means
        # that the stream used was created in this method.
        my_file = False

        # If the fileobj parameter is a string, assume it is a path
        # and create a file object at that location. If it is a file,
        # copy the file's contents into a BytesIO (or StreamIO) stream object; if
        # it is a PdfFileReader, copy that reader's stream into a
        # BytesIO (or StreamIO) stream.
        # If fileobj is none of the above types, it is not modified
        decryption_key = None
        if isString(fileobj):
            fileobj = file(fileobj, 'rb')
            my_file = True
        elif isinstance(fileobj, file):
            fileobj.seek(0)
            filecontent = fileobj.read()
            fileobj = StreamIO(filecontent)
            my_file = True
        elif isinstance(fileobj, PdfFileReader):
            orig_tell = fileobj.stream.tell()
            fileobj.stream.seek(0)
            filecontent = StreamIO(fileobj.stream.read())
            fileobj.stream.seek(orig_tell) # reset the stream to its original location
            fileobj = filecontent
            if hasattr(fileobj, '_decryption_key'):
                decryption_key = fileobj._decryption_key
            my_file = True

        # Create a new PdfFileReader instance using the stream
        # (either file or BytesIO or StringIO) created above
        pdfr = NewPdfFileReader(fileobj, strict=self.strict)
        if decryption_key is not None:
            pdfr._decryption_key = decryption_key

        # Find the range of pages to merge.
        if pages == None:
            pages = (0, pdfr.getNumPages())
        elif isinstance(pages, PageRange):
            pages = pages.indices(pdfr.getNumPages())
        elif not isinstance(pages, tuple):
            raise TypeError('"pages" must be a tuple of (start, stop[, step])')

        srcpages = []
        if bookmark:
            bookmark = Bookmark(TextStringObject(bookmark), NumberObject(self.id_count), NameObject('/Fit'))

        outline = []
        if import_bookmarks:
            outline = pdfr.getOutlines()
            outline = self._trim_outline(pdfr, outline, pages)

        if bookmark:
            self.bookmarks += [bookmark, outline]
        else:
            self.bookmarks += outline

        dests = pdfr.namedDestinations
        dests = self._trim_dests(pdfr, dests, pages)
        self.named_dests += dests

        # Gather all the pages that are going to be merged
        for i in range(*pages):
            pg = pdfr.getPage(i)

            id = self.id_count
            self.id_count += 1

            mp = _MergedPage(pg, pdfr, id)

            srcpages.append(mp)

        self._associate_dests_to_pages(srcpages)
        self._associate_bookmarks_to_pages(srcpages)

        # Slice to insert the pages at the specified position
        self.pages[position:position] = srcpages

        # Keep track of our input files so we can close them later
        self.inputs.append((fileobj, pdfr, my_file))

NewPdfFileMerger.merge = newMerge
```

**Comment by singhabhishekiitkgp** [comment]
> Raise utils.PdfReadError (“ could not read malformed PDF File”)
> This error is striking everytime i run the simple pypdf2 code

did you get any solution? because I am facing the same problem.
PdfReadError                              Traceback (most recent call last)
<ipython-input-54-95de3aa8a98a> in <module>()
      1 merger = PyPDF2.PdfFileMerger()
----> 2 merger.append(PyPDF2.PdfFileReader(f),import_bookmarks=False)

/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py in __init__(self, stream, strict, warndest, overwriteWarnings)
   1082             stream = BytesIO(b_(fileobj.read()))
   1083             fileobj.close()
-> 1084         self.read(stream)
   1085         self.stream = stream
   1086 

/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py in read(self, stream)
   1695             if stream.tell() < last1K:
   1696                 raise utils.PdfReadError("EOF marker not found")
-> 1697             line = self.readNextEndLine(stream)
   1698             if debug: print("  line:",line)
   1699 

/usr/local/lib/python3.6/dist-packages/PyPDF2/pdf.py in readNextEndLine(self, stream)
   1935             # Prevent infinite loops in malformed PDFs
   1936             if stream.tell() == 0:
-> 1937                 raise utils.PdfReadError("Could not read malformed PDF file")
   1938             x = stream.read(1)
   1939             if debug: print(("  x:", x, "%x"%ord(x)))

PdfReadError: Could not read malformed PDF file

**Comment by jpkell05** [comment]
Another +1 for the solution by @ibalex! Worked in my case at least, which was merging some pdfs generated by wkhtmltopdf.

**Comment by qtwtp123** [comment]
I have same problem when merging pdfs. But I want to keep bookmark.
This is my solution to fix _buildOutline and _trim_outline.

Thanks for [this](https://stackoverflow.com/questions/39027586/how-create-a-table-of-contents-page-in-the-pdf-file-from-the-bookmarks-with-itex) to let me know PDF better.

1.  The first thing I want to fix is _build_outline
Thanks for @hannal for his bypass funciton
Here is my code in pdf.py 
```
if dest:
    if isinstance(dest, ArrayObject):
        outline = self._buildDestination(title, dest)
    elif isString(dest) and dest in self._namedDests:
        outline = self._namedDests[dest]
        outline[NameObject("/Title")] = title
    elif isinstance(dest,NameObject):
        outline=self._buildDestination(title,self.trailer['/Root']['/Dests'][dest]) 
    else:
        raise utils.PdfReadError("Unexpected destination %r" %dest)
```
The reason why i set 'self.trailer['/Root']['/Dests'][dest]' is because i need to get data when trim_outline.
self.trailer['/Root']['/Dests'][dest] for ['/__WKANCHOR_??'] would output something like [1, '/XYZ', 79.5, 813.5, 0].
The first element is page number.

2. The second thing I need to fix is _trim _outline
Here is my code in merger.py
```
if isinstance(o['/Page'],int):
    o[NameObject('/Page')]=pdf.getPage(o['/Page']).getObject()
    new_outline.append(o)
    prev_header_added=True
else:
    for j in range(*pages):
        if pdf.getPage(j).getObject() == o['/Page'].getObject():
            o[NameObject('/Page')] = o['/Page'].getObject()
            new_outline.append(o)
            prev_header_added = True
            break
```
The variable 'o' means outline here.
The original part is in elif. 
It's main purpose is to go through pages to check.
In 1. part , I get page number when building outline.
So if I get page number (integer) I can get data needed, else i go through pages. 

That's work for me. Maybe it could help.

**Comment by MartinThoma** [comment]
@hannal Would you mind to create a PR with your fix?

**Comment by Cyiming** [comment]
> I have same problem when merging pdfs. But I want to keep bookmark. This is my solution to fix _buildOutline and _trim_outline.
> 
> Thanks for [this](https://stackoverflow.com/questions/39027586/how-create-a-table-of-contents-page-in-the-pdf-file-from-the-bookmarks-with-itex) to let me know PDF better.
> 
> 1. The first thing I want to fix is _build_outline
>    Thanks for @hannal for his bypass funciton
>    Here is my code in pdf.py
> 
> ```
> if dest:
>     if isinstance(dest, ArrayObject):
>         outline = self._buildDestination(title, dest)
>     elif isString(dest) and dest in self._namedDests:
>         outline = self._namedDests[dest]
>         outline[NameObject("/Title")] = title
>     elif isinstance(dest,NameObject):
>         outline=self._buildDestination(title,self.trailer['/Root']['/Dests'][dest]) 
>     else:
>         raise utils.PdfReadError("Unexpected destination %r" %dest)
> ```
> 
> The reason why i set 'self.trailer['/Root']['/Dests'][dest]' is because i need to get data when trim_outline. self.trailer['/Root']['/Dests'][dest] for ['/__WKANCHOR_??'] would output something like [1, '/XYZ', 79.5, 813.5, 0]. The first element is page number.
> 
> 2. The second thing I need to fix is _trim _outline
>    Here is my code in merger.py
> 
> ```
> if isinstance(o['/Page'],int):
>     o[NameObject('/Page')]=pdf.getPage(o['/Page']).getObject()
>     new_outline.append(o)
>     prev_header_added=True
> else:
>     for j in range(*pages):
>         if pdf.getPage(j).getObject() == o['/Page'].getObject():
>             o[NameObject('/Page')] = o['/Page'].getObject()
>             new_outline.append(o)
>             prev_header_added = True
>             break
> ```
> 
> The original part is in else. It's main purpose is to go through pages to check. In 1. part , I get page number when building outline. So if I get page number (integer) I can get data needed, else i go through pages.
> 
> That's work for me. Maybe it could help.

Hello, I reported an error with your code：   
` if isinstance(o['/Page'], int):TypeError: list indices must be integers or slices, not str`

my code:
```
        for i, o in enumerate(outline):
            if isinstance(o['/Page'], int):
                o[NameObject('/Page')] = pdf.getPage(o['/Page']).getObject()
                new_outline.append(o)
                prev_header_added = True
            else:
                for j in range(*pages):
                    if pdf.getPage(j).getObject() == o['/Page'].getObject():
                        o[NameObject('/Page')] = o['/Page'].getObject()
                        new_outline.append(o)
                        prev_header_added = True
                        break
        return new_outline
```
I print o :
```
{'/Title': '到底好在哪儿？', '/Page': 0, '/Type': '/XYZ', '/Left': 4.5, '/Top': 842, '/Zoom': 0}
[{'/Title': '到底优秀在什么地方，体验好在什么地方？', '/Page': 0, '/Type': '/XYZ', '/Left': 4.5, '/Top': 807.5, '/Zoom': 0}]
```

**Comment by MartinThoma** [comment]
Is this related to #284

**Comment by mtd91429** [comment]
Is anyone able to provide an example PDF which generates this issue? It's hard to understand why this bug is occurring without an example to tinker with.

**Comment by LamerLink** [comment]
I‘ll look through my archive tonight. The issue has something to do with xref tables being created improperly (not by PyPDF2), so when they’re read it causes an error. 

Some software, such as Acrobat, will repair this semi-silently; after opening the poorly-formed PDF, it’ll ask you if you want to save changes on closing even if nothing was changed).

**Comment by LamerLink** [comment]
So you can look at the pdf used for the unexpected destination test actually. https://corpora.tika.apache.org/base/docs/govdocs1/913/913678.pdf

It raises the same exception with a different bad destination, `Unexpected destination '/1'`.

**Comment by mtd91429** [comment]
Thanks - I see how that one is broken. It looks like there was a Named Destination ("/1") that was ultimately removed from the Name Dictionary. I'll have to assume that's the same issue that occurred in the '_WKANCHOR_2' issue. There is a missing name reference. For clarification, see my comment from today (July-12-2022) on PDF specifications. 

In this case, I wonder if it would be better to fix it by not throwing an error but issuing a user warning that the bookmark uses a named destination that is not defined. One could still keep the outline entry's title and location with document outline, continue to process the file. This would make the program much more flexibile. I also think this is pertinent to some of the changes I made in #1076 and should be accounted for before it is merged. Thoughts @MartinThoma?

**Comment by MartinThoma** [comment]
## MCVE

```python
from PyPDF2 import PdfReader
reader = PdfReader("913678.pdf")
reader.outlines
```

Expected:

```
[
    {"/Title": ""},
    [
        {
            "/Title": "Report for 2002AZ3B: Microbial Mediated Mobilization of Arsenic from Drinking Water Treatment Residuals in Landfills"
        }
    ]
]
```

In Chrome:

![image](https://user-images.githubusercontent.com/1658117/180592996-54493dee-40cd-42c4-8ed8-0c60a819c052.png)


Current:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 685, in outlines
    return self._get_outlines()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 717, in _get_outlines
    outline = self._build_outline(node)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 848, in _build_outline
    raise PdfReadError(f"Unexpected destination {dest!r}")
PyPDF2.errors.PdfReadError: Unexpected destination '/1'
```

**Comment by MartinThoma** [comment]
Thanks to everybody involved in this over the past 7 years!

@mtd91429 developed a clean solution to the issue :tada: 

I will make a release to PyPI on Sunday which contains this fix.
