### ISSUE TITLE
[documentacion] Broken links to online demonstrations

### ISSUE THREAD

**Issue by PabloCastellano** [py-pdf/PyPDF2#206]
In the "Online demonstrations of PyPDF2" [paragraph](http://mstamy2.github.io/PyPDF2/#online) these two links are broken:
- http://host02.phaseit.net:8086/PyPDF2/validate.py
- http://host02.phaseit.net:8086/PyPDF2/validator_FAQ

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com
