### ISSUE TITLE
DCT Filter

### ISSUE THREAD

**Issue by claird** [py-pdf/PyPDF2#21]
PyPDF2 currently lacks a filter for DCT compression (true?  Even as maintainers, we sometimes forget everything there is to know about PyPDF2).  How important is it that we add this?  There certainly are instances "in the wild" of PDF which use DCT compression; should we care?

[See also internal Issue756.]

**Comment by sylvainpelissier** [comment]
I have added the DCT test case in this [pull request](https://github.com/mstamy2/PyPDF2/pull/237). It simply extract the raw data. If you save it as it is in a jpeg file it will produce a valid image.
