### ISSUE TITLE
Implement Encryption Version 4

### ISSUE THREAD

**Issue by speedplane** [py-pdf/PyPDF2#226]
The PDF decryption is only partially implemented in PyPDF2. I recently found a [PDF I have been processing](https://www.sugarsync.com/pf/D62078_93519013_6655606) which has been encrypted using algorithm 4.

There is a very clear line in `pdf.py` around line 1967 that states:

```
raise NotImplementedError("only algorithm code 1 and 2 are supported")
```

I'm opening up this issue to hopefully motivate some way of solving it.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaiksihwar@gmail.com

**Comment by nitd24** [comment]
+1 on this issue

**Comment by idogrosberg** [comment]
+1

**Comment by ganeshtata** [comment]
+1 on this issue. Has anybody made any progress on this?

**Comment by unitedkartik** [comment]
+ 1 . Any solution yet?

**Comment by MartinThoma** [comment]
If anybody has a pr, I could merge it :-)

**Comment by MartinThoma** [comment]
Maybe #749 helps?

**Comment by MartinThoma** [comment]
This issue was solved 🎉
