### ISSUE TITLE
Unsorted name trees causing broken links

### ISSUE THREAD

**Issue by vasekp** [py-pdf/PyPDF2#229]
Using PyPDF2 1.25.1, I merged PDF 1.5 files with hyperlinks. The links and their targets are preserved but `evince` could not reach the target anyway. A closer inspection revealed the reason to be that the `/Dests` name tree was written in a non-sorted order to the output (the ordering was correct in the source files). Section 3.8.5 of PDF 1.5 specification lists ordering of keys in a name tree as a requirement.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaiksihwar@gmail.com

**Comment by MartinThoma** [comment]
Do you have a minimal example (code + pdf(s)) that show the issue?

**Comment by MartinThoma** [comment]
Without examples, I doubt we can work on this one
