### ISSUE TITLE
Add table extraction capabilities

### ISSUE THREAD

**Issue by bonsonsm** [py-pdf/PyPDF2#231]
Hello,
I am converting a pdf file into a text file. In the extracted text file, I am unable to know where the table starts, however I am able to extract the text of the table as is, but I want to know where the table starts and ends so I could do some post processing on it.

Below is my code:

```python
def extractTextFromPDF(strDownloadDirectory, fileName, txtFilePath):
        filePathName = strDownloadDirectory + fileName
        pdfFileObj = open(filePathName, 'rb')
        pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
        intPages = pdfReader.getNumPages()
        print(intPages)
        strText = ''
        print(fileName)
        fileName =fileName[0:len(fileName)-4]
        txtFilePath = txtFilePath +fileName  + '.txt'
        target_file = open(txtFilePath, "w" , encoding='utf-8')
        for i in range(0,intPages):
            objPDFObj = pdfReader.getPage(i)
            strText =  objPDFObj.extractText().rstrip()
            strText = " ".join(strText.replace(u"\xa0", " ").strip().split())
            print(strText)
        target_file.write(strText)
        target_file.close()
```

Kindly suggest.

**Comment by mstamy2** [comment]
PyPDF2's text extraction capabilities are somewhat primitive at the moment, though I want to make enhancing them a priority.

Consider [PDFMiner](http://www.unixuser.org/~euske/python/pdfminer/) or [PDFbox](https://pdfbox.apache.org/) for your immediate needs; they feature much more sophisticated text extraction resources.

It's not simple to recognize a table structure in PDF, but these libraries might be able to help.

**Comment by sils** [comment]
@mstamy2 any progress on this? I guess getting all text and it's position might be sufficient to get most usecases covered already.

**Comment by sils** [comment]
CC @sims1253

**Comment by MartinThoma** [comment]
I've just noticed "TABLE 10.29 Standard layout attributes" with

![image](https://user-images.githubusercontent.com/1658117/174232527-e889ff51-7f11-4dba-a4c4-40c1066e6a35.png)

**Comment by MartinThoma** [comment]
I'm closing this for the moment as it distracts from other topics that seem more important at the moment.

If anybody has an idea how to approach this in a reasonable way: I'm open for discussions and I can re-open :-)

For people looking for solutions: The best I've got for you is https://pypi.org/project/camelot-py/ or developing something on your own, e.g. using a layout-preserving extraction (e.g. pdftotext -layout) + some heuristics.

**Comment by pubpub-zz** [comment]
@MartinThoma 
Perhaps should you open a discussion listing all those features which are left on slide for the moment in order to find them directly

**Comment by MartinThoma** [comment]
Good idea @pubpub-zz :+1: See https://github.com/py-pdf/PyPDF2/discussions/1181
