### ISSUE TITLE
Cannot `extract_text` from weasyprint generated PDF

### ISSUE THREAD

**Issue by mattjmorrison-imt** [py-pdf/PyPDF2#242]
Generating a PDF with the following code ends up not returning anything from `extractText`. 

``` python
"""
PyPDF2==2.1.0
WeasyPrint==55.0
"""

from io import BytesIO
from PyPDF2 import PdfReader

# Create example
from weasyprint import HTML
stream = BytesIO()
HTML(string="""
<html>
<body>
<div>Hello World</div>
</body>
</html>
""").write_pdf(stream)
stream.seek(0)

# Try to read "Hello World"
reader = PdfReader(stream)
print(reader.pages[0].extract_text())
```

In this issue: Kozea/WeasyPrint/issues/290 @liZe points out that other tools are able to extract the text.

**Comment by afedosenko** [comment]
pypdf2==1.26.0
weasyprint==53.2



In these versions, the text is also not extracted for the example above.

**Comment by liZe** [comment]
> In these versions, the text is also not extracted for the example above.

It doesn’t work because PyPDF2 doesn’t use the `/Encoding` and/or the `/ToUnicode` information included in embedded fonts. As far as I can tell, there’s no easy fix :/, it will probably require a certain amount of work.

**Comment by MartinThoma** [comment]
PyPDF2 now uses `/Encoding` and `/ToUnicode`. Sadly, this issue is still open.

**Comment by liZe** [comment]
> PyPDF2 now uses `/Encoding` and `/ToUnicode`. Sadly, this issue is still open.

I can make the script work by adding this code [in _extract_text](https://github.com/py-pdf/PyPDF2/blob/babe32e471c6c0d6ee8dd356432dded225fe69a9/PyPDF2/_page.py#L1223-L1227):
```py
if isinstance(op, bytes):
    process_operation(b"Tj", [op.decode('utf-16be')])
```

Maybe this case is not supported because WeasyPrint uses 2-byte codes for its strings. This code is probably a dirty workaround, but you’ll find the correct fix faster than me 😁.

(We get the right text, so `/Encoding` and `/ToUnicode` seem to work correctly as we always use custom encodings in WeasyPrint. 👏🎉)

**Comment by MartinThoma** [comment]
@liZe Very nice! Thanks for sharing!

@pubpub-zz You're the expert here. Do you think adding it like this is ok?

**Comment by pubpub-zz** [comment]
the proble; is a little more tricky.
Under analysis

**Comment by pubpub-zz** [comment]
@liZe, can you retest with the latest version and give feed-backs

**Comment by liZe** [comment]
> @liZe, can you retest with the latest version and give feed-backs

👏 it works 👏

**Comment by pubpub-zz** [comment]
@MartinThoma
can you close it then

**Comment by MartinThoma** [comment]
Very nice! Amazing work @pubpub-zz and thank you for confirming @liZe :hugs:
