### ISSUE TITLE
extractText() doesn't work on Chinese PDF

### ISSUE THREAD

**Issue by zxteloiv** [py-pdf/PyPDF2#252]
As I have tested, pure English content in a PDF can be extracted without problem.
But nothing readable could be extracted for a Chinese page.

I guess it's caused by the encoding.
I tried to modify the following line to below
https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/utils.py#L246

``` python
def u_(s):
    if sys.version_info[0] < 3:
        return unicode(s, encoding='utf-8')
    else:
        return s
```

But it doesn't work.

My environment:
- Python 2.7.10
- OS X El Capitan
- PyPDF2 version 1.25.1

Thank you.

**Comment by joewong826** [comment]
I have the same problem too. It spitted out total gibberish when it came to Chinese characters.

**Comment by gustavkkk** [comment]
extractText() function needs some modification. Main problem is from handling ByteStringObjects. Is there somebody who solved this?
https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/pdf.py
    def extractText(self):
        """
        Locate all text drawing commands, in the order they are provided in the
        content stream, and extract the text.  This works well for some PDF
        files, but poorly for others, depending on the generator used.  This will
        be refined in the future.  Do not rely on the order of text coming out of
        this function, as it will change if this function is made more
        sophisticated.

        :return: a unicode string object.
        """
        # Note: we check all strings are TextStringObjects.  ByteStringObjects
        # are strings where the byte->string encoding was unknown, so adding
        # them to the text here would be gibberish.
