### ISSUE TITLE
Last page of file not recognized due to having same object number as an old /XRef

### ISSUE THREAD

**Issue by jeffrey-easyesi** [py-pdf/PyPDF2#265]
We recently ran into a PDF file that has three pages, of which PyPDF2 only recognizes the first two. The relevant pieces of the file look like

```
%PDF-1.5
...
3 0 obj << /Type /Pages /Count 1 /Kids [4 0 R] >> endobj
...
23 0 obj << /Type /XRef ... >> stream ... endstream endobj
startxref
135096
%%EOF
...
3 0 obj << /Type /Pages /Count 3 /Kids [4 0 R 45 0 R 23 0 R] >> endobj
...
23 0 obj << /Type /Page ... >> endobj
...
63 0 obj << /Type /XRef ... /Prev 135096 >> stream ... endstream endobj
startxref
349145
%%EOF
```

While reading the xref chain, PyPDF2 caches the earlier /XRef under object ID `23 0`, so `_flatten` sees the /XRef instead of the /Page and skips it.

Removing https://github.com/mstamy2/PyPDF2/blob/5bbd5aff8cfe245a61b8a4ace2d06d78eac1fa9c/PyPDF2/pdf.py#L1811 fixes this: all three pages show up.

**Comment by mstamy2** [comment]
I'm glad you found the hotfix.

When writing an incremental update, I don't think an application should reuse the object number of a previous Xref stream (this implies that it is being overwritten).

That said, it's questionable how much this matters. Xrefs generally aren't accessed via indirect reference, so is there a reason to cache them at all?

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/PyPDF2/issues/364 might be related

**Comment by MartinThoma** [comment]
Without an example file, I doubt we can work on this
