### ISSUE TITLE
Cannot read certain PDF file (tolerance issue?)

### ISSUE THREAD

**Issue by justhalf** [py-pdf/PyPDF2#28]
PyPDF2 can't read some files which can be read by pyPdf.

Usually these PDFs contains ^M characters in the first line, just after the comment, like this one: http://books.nips.cc/papers/files/nips24/NIPS2011_0622.pdf

Also I noticed that the function readNonWhitespace in utils.py is performing exactly the same function as skipOverWhitespace. I suppose readNonWhitespace should read _non whitespace_ characters?

**Comment by ganeshtata** [comment]
Could anyone figure out a solution for this issue?

**Comment by datomnurdin** [comment]
any solution so far?

**Comment by MartinThoma** [comment]
Can anybody share such a PDF file?

**Comment by justhalf** [comment]
Personally I no longer work on PDF files, and so I can't answer that question anymore. But if other users experienced similar problems, hopefully they can procure such problematic files!

**Comment by MartinThoma** [comment]
Many things have changed. I cannot reproduce it without a pdf.

Hopefully it was solved. If it wasn't, please let me know
