### ISSUE TITLE
Read from StringIO objects as files

### ISSUE THREAD

**Issue by mmangione** [py-pdf/PyPDF2#281]
In a server environment, we rarely serialize data to the hard drive. We use StringIO objects instead since they have all of the same filelike properties.

Please simply broaden the types of objects that you recognize as files to

```
if isinstance(fileobj, file) or isinstance(fileobj, StringIO)
```

I'll submit a pull request for this. It's about 3 or 4 lines that need to be changed with no alterations to the code afterwards - since they are treated just like files.

**Comment by jbarlow83** [comment]
@mmangione A better test would be something like

```python
hasattr(fileobj, 'read') and hasattr(fileobj, 'seek') and not issubclass(fileobj.__class__, io.TextIOBase)
```

in other words check for a duck-typed object that can read and seek (excluding pipes) while excluding text strings, and allowing bytestrings.

The test as you wrote is broken in Python3 since it would exclude `io.BytesIO`.

**Comment by mmangione** [comment]
@jbarlow83 
Ah! Excellent change! I like yours much better. :+1:

**Comment by oscardssmith** [comment]
How hard would it be to remove the seek dependency?. It would be quite nice to be able to print PDF's to stdout.

**Comment by jbarlow83** [comment]
I actually don't known if PyPDF2 seeks when writing a PDF. Clearly it does
when reading.

In practice any reader needs to jump to the offset table at the end of the
PDF as a first step, unless it's a linearized PDF which PyPDF2 can't
produce. That's probably a big effort.

**Comment by oscardssmith** [comment]
It either seeks when writing, or checks to make sure the object can seek when writing, as writing to sys.stdout fails. That should probably be a separate request though.

**Comment by MartinThoma** [comment]
I think https://pypdf2.readthedocs.io/en/latest/user/streaming-data.html covers this.

If it doesn't, I'll reopen :-)
