### ISSUE TITLE
ENH: Support reading link annotations

### ISSUE THREAD

**Issue by tiarno** [py-pdf/PyPDF2#284]
I convert an html file to pdf with wkhtmltopdf and cannot find the named destinations in using PyPDF2. 

The links in the pdf work and the destinations exist, but the structure is different from what I'm used to. Here is a link:

```
11 0 obj
<<
/Type /Annot
/Subtype /Link
/Rect [32.8200000  767.929999  51.5700000  779.179999 ]
/Border [0 0 0]
/Dest /file#3a##2fmytesting.htm#23myanchor
>>
```

And the destinations seem to be a bare list like this:

```
12 0 obj
<<
/__WKANCHOR_2 8 0 R
/__WKANCHOR_4 9 0 R
/file#3a#2fmytesting.htm#23myanchor 10 0 R
>>
endobj
```

Is there a way to find the destinations with PyPDF2? 
The `namedDestinations` property returns an empty dict. 
I've tried find to find the info from the resolvedObjects dict but so far with no luck.

thanks.

**Comment by MichaelKim0407** [comment]
Please have a look at my patch: https://github.com/MichaelKim0407/PyPDF2/commit/3415d60c15dad470e36c9092129d3d4a621dc65e

It probably only works with PDFs generated using `wkhtmltopdf` (haven't tested with other PDFs), however that's only what I need

**Comment by tiarno** [comment]
thanks, that looks good but I'm sorry it will be awhile before I can test it out. The pdfs generated by wkhtmltopdf are the only kind I had trouble parsing. Thanks for your work and I'll let you know once I'm able to try it out.

**Comment by MartinThoma** [comment]
## MCVE: Code + PDF

Example file: [wiki-pdf.pdf](https://github.com/py-pdf/PyPDF2/files/9078505/wiki-pdf.pdf)

```python
>>> from PyPDF2 import PdfReader
>>> reader = PdfReader("wiki-pdf.pdf")
>>> reader.named_destinations
{}
```

Expected non-empty dict

**Comment by MartinThoma** [comment]
```
/Type /Annot
/Subtype /Link
```

is not a named destination, but a link annotation (page 622 of the 1.7 standard - "Link Annotations")

A named destination is `/Names` or `/Dests`.

**Comment by MartinThoma** [comment]
Number of files with at least one annotations in my big dataset:

* /Link: 2694x
* /Widget: 431x
* /Popup: 189x
* /FreeText: 85x
* /Text: 77x
* /Square: 47x
* /Stamp: 40x
* /Highlight: 22x
* /Line: 22x
* /DGAP:RedaxBox: 3x
* /Circle: 2x
* /FileAttachment: 2x
* /StrikeOut: 2x
* /Underline: 2x
* /Ink: 1x
* /Caret: 1x

**Comment by pubpub-zz** [comment]
> ```
> /Type /Annot
> /Subtype /Link
> ```
> 
> is not a named destination, but a link annotation (page 622 of the 1.7 standard - "Link Annotations")
> 
> A named destination is `/Names` or `/Dests`.

@MartinThoma or anyone else has found how to build link annotation with adobe reader?

**Comment by MartinThoma** [comment]
I want to give it a try tomorrow by looking at some of those examples :-)

**Comment by MartinThoma** [comment]
See add_link in writer - should be deprecated

**Comment by pubpub-zz** [comment]
I've got it : the /Link are the actions/links but which can not be produced by adobe reader but by a pdf editor (or PyPDF2 😊)
@MartinThoma , can you provide a pointer about your latest comment about add_link. Did not understand.

**Comment by MartinThoma** [comment]
https://corpora.tika.apache.org/base/docs/govdocs1/980/980183.pdf (`pdf/01d5ad62eade10147b9154503a8e6f22.pdf` on my machine) has link annotations:

```python
from PyPDF2 import PdfReader

reader = PdfReader("pdf/01f642dc8d1b844d3eff872480a2961c.pdf")
reader.pages[0].annotations[0].get_object()
```

Gives:

```
{
    "/Type": "/Annot",
    "/Subtype": "/Link",
    "/Rect": [
        218.52008,
        436.17654,
        363.42554,
        451.94431
    ],
    "/Border": [0, 0, 0],
    "/H": "/I",
    "/A": IndirectObject(885, 0, 140373925315440),
    "/StructParent": 1
}
```

So on the first page there is a link annotation. 

```
>>> reader.pages[0].annotations[0].get_object()["/A"]
{'/S': '/URI', '/URI': 'http://ricegaas.dna.affrc.go.jp/'}
```

> can you provide a pointer about your latest comment about add_link

@pubpub-zz I'll make a PR today :-)

**Comment by MartinThoma** [comment]
@pubpub-zz This is what I meant https://github.com/py-pdf/PyPDF2/pull/1189 - the `writer.add_link` is not necessary any longer. It's better to use `writer.add_annotation(AnnotationBuilder.link(...))`.
