### ISSUE TITLE
Unable to find 'endstream' marker after stream at byte 0x1047a.

### ISSUE THREAD

**Issue by vincent-prz** [py-pdf/PyPDF2#301]
Hello,

When executing this piece of code:

```python
merger = PdfFileMerger(strict=False)
merger.append(some_file)

with BytesIO() as output_io:
    merger.write(output_io)
```
I get the following error: Unable to find 'endstream' marker after stream at byte 0x1047a.

I saw the issue https://github.com/mstamy2/PyPDF2/issues/167 which seemed similar, but the cause is not the same, since the file I am trying to merge has a size of only 70kB. Any help regarding this issue?

PS: I am using version 1.25.1. I tried to upgrade to 1.26.0, I experienced the same issue.

**Comment by bhaskar2500** [comment]
Use PyPDF2 not PyPdf..

**Comment by Heisenberg815** [comment]
@bhaskar2500 I am using PyPDF2. Anyway, thanks for your insight..

**Comment by quantus** [comment]
I ran into the same error message when opening some invalid PDF files and had to write some ugly code that tries to deal with the invalid content. My code can be found in pull request #250, so you may try if it is of any help.

**Comment by 14vv1A0516** [comment]
Even I got same problem while writing into a location using output.write() method.
please help me

**Comment by akshatgoyalalgo** [comment]
I replaced 
 `if end == b_("endstream"):`
with
`if end == b_("endstream") or b_("EOF") in end:`

in PyPDF2/generic.py.
Worked for me.

**Comment by TZanke** [comment]
@MartinThoma looks like a pdf cut off the end for unknown reason. PyPDF fails finding the end marker of the pdf standard. The fix by @akshatgoyalalgo takes a EOF as a endstream marker instead. But this may only work if the pdf is missing some bits and bytes at the end. A file missing 50% isn't fixable this way, isnt it? Or maybe i am totally wrong.

As far i can see in our code, we resave the pdf to fix it with some external command line tool. (there are a lot of PyPDF2 issues we fix by resaving a foreign pdf).

Luckily we have a issue in our ticket system with a example file send to us by a customer, without any privacy data, so i happily can share at least this one.
[Example_2019-10-25_11-32-10.pdf](https://github.com/py-pdf/PyPDF2/files/8450923/Example_2019-10-25_11-32-10.pdf)

Output years ago:
Unable to find 'endstream' marker after stream at byte 0x11440.

**Comment by pubpub-zz** [comment]
@TZanke 
I've worked on some code to cope with invalid length. can you tell me if the results below looks seems good (results hard to interprete):
[ttt.pdf](https://github.com/py-pdf/PyPDF2/files/8598746/ttt.pdf)

**Comment by TZanke** [comment]
@pubpub-zz i really don't know from a technical point of view. If i run a file diff on the original file and the new file, its i huge difference. But what i can see, it's displayed correctly. 

 If the change goes into a release i could upgrade and see if production systems have any problems with pdf's in the future.

I hope this is the answer you did expect. :)

**Comment by pubpub-zz** [comment]
This change will be on 2.0.0 branch, If you want to test it before you just need to replace readFromStream in DictionaryObject  (generic.py):
    #ppZZ
    @staticmethod
    def readFromStream(stream, pdf):
        def getNextObjPos(p,p1,remGens,pdf):
            l = pdf.xref[remGens[0]]
            for o in l:
                if p1 > l[o] and p < l[o]:
                    p1=l[o]
            if len(remGens) == 1:
                return p1
            else:
                return getNextObjPos(p,p1,remGens[1:],pdf)                
                        
        def readUnsizedFromSteam(stream,pdf):
            # we are just pointing at beginning of the stream
            eon = getNextObjPos(stream.tell(),2**32,[g for g in pdf.xref],pdf)-1
            curr = stream.tell()
            rw = stream.read(eon - stream.tell())
            p = rw.find(b_("endstream"))
            if p <0:
                raise PdfReadError(f"Unable to find 'endstream' marker for obj starting at {curr}.")
            stream.seek(curr + p+ 9)  
            return rw[:p-1]
            
        tmp = stream.read(2)
        if tmp != b_("<<"):
            raise PdfReadError(
                "Dictionary read error at byte %s: stream must begin with '<<'"
                % utils.hexStr(stream.tell())
            )
        data = {}
        while True:
            tok = readNonWhitespace(stream)
            if tok == b_("\x00"):
                continue
            elif tok == b_("%"):
                stream.seek(-1, 1)
                skipOverComment(stream)
                continue
            if not tok:
                raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)

            if tok == b_(">"):
                stream.read(1)
                break
            stream.seek(-1, 1)
            key = readObject(stream, pdf)
            tok = readNonWhitespace(stream)
            stream.seek(-1, 1)
            value = readObject(stream, pdf)
            if not data.get(key):
                data[key] = value
            elif pdf.strict:
                # multiple definitions of key not permitted
                raise PdfReadError(
                    "Multiple definitions in dictionary at byte %s for key %s"
                    % (utils.hexStr(stream.tell()), key)
                )
            else:
                warnings.warn(
                    "Multiple definitions in dictionary at byte %s for key %s"
                    % (utils.hexStr(stream.tell()), key),
                    PdfReadWarning,
                )

        pos = stream.tell()
        s = readNonWhitespace(stream)
        if s == b_("s") and stream.read(5) == b_("tream"):
            eol = stream.read(1)
            # odd PDF file output has spaces after 'stream' keyword but before EOL.
            # patch provided by Danial Sandler
            while eol == b_(" "):
                eol = stream.read(1)
            if eol not in (b_("\n"), b_("\r")):
                raise PdfStreamError("Stream data must be followed by a newline")
            if eol == b_("\r"):
                # read \n after
                if stream.read(1) != b_("\n"):
                    stream.seek(-1, 1)
            # this is a stream object, not a dictionary
            if SA.LENGTH not in data:
                raise PdfStreamError("Stream length not defined")
            length = data[SA.LENGTH]
            if isinstance(length, IndirectObject):
                t = stream.tell()
                length = pdf.getObject(length)
                stream.seek(t, 0)
            pstart = stream.tell()
            data["__streamdata__"] = stream.read(length)
            e = readNonWhitespace(stream)
            ndstream = stream.read(8)
            if (e + ndstream) != b_("endstream"):
                # (sigh) - the odd PDF file has a length that is too long, so
                # we need to read backwards to find the "endstream" ending.
                # ReportLab (unknown version) generates files with this bug,
                # and Python users into PDF files tend to be our audience.
                # we need to do this to correct the streamdata and chop off
                # an extra character.
                pos = stream.tell()
                stream.seek(-10, 1)
                end = stream.read(9)
                if end == b_("endstream"):
                    # we found it by looking back one character further.
                    data["__streamdata__"] = data["__streamdata__"][:-1]
                elif not pdf.strict:
                    stream.seek(pstart,0)
                    data["__streamdata__"] = readUnsizedFromSteam(stream, pdf)
                    pos=stream.tell()
                else:
                    stream.seek(pos, 0)
                    raise PdfReadError(
                        "Unable to find 'endstream' marker after stream at byte %s."
                        % utils.hexStr(stream.tell())
                    )
        else:
            stream.seek(pos, 0)
        if "__streamdata__" in data:
            return StreamObject.initializeFromDictionary(data)
        else:
            retval = DictionaryObject()
            retval.update(data)
            return retval
