### ISSUE TITLE
page property of Destination class is wrong type

### ISSUE THREAD

**Issue by jvalenzuela** [py-pdf/PyPDF2#304]
Documentation states page is a read-only property containing the page number as an integer. It actually returns an indirect reference to the page object.

[https://pythonhosted.org/PyPDF2/Destination.html](url)

**Comment by MartinThoma** [comment]
Thank you for reporting!

This got fixed with https://github.com/py-pdf/PyPDF2/pull/426 - the new docs are at https://pypdf2.readthedocs.io/en/latest/
