### ISSUE TITLE
Could not read PDF file without xref table

### ISSUE THREAD

**Issue by rgaiacs** [py-pdf/PyPDF2#309]
From [this answer on StackOverflow](http://stackoverflow.com/a/17280876/1802726) the "minimal" PDF is

~~~
$ cat /tmp/minimal.pdf 
%PDF-1.0
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj 2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj 3 0 obj<</Type/Page/MediaBox[0 0 3 3]>>endobj
trailer<</Size 4/Root 1 0 R>>
~~~

I can read `/tmp/minimal.pdf` with Evince and Chrome built-in PDF reader but PyPDF2 gives me

~~~
>>> import PyPDF2
>>> PyPDF2.__version__
'1.26.0'
>>> PyPDF2.PdfFileReader("/tmp/f.pdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raniere/anaconda3/envs/fat/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/raniere/anaconda3/envs/fat/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1697, in read
    line = self.readNextEndLine(stream)
  File "/home/raniere/anaconda3/envs/fat/lib/python3.5/site-packages/PyPDF2/pdf.py", line 1937, in readNextEndLine
    raise utils.PdfReadError("Could not read malformed PDF file")
PyPDF2.utils.PdfReadError: Could not read malformed PDF file
~~~

**Comment by haroonkhan02** [comment]
Same error on a PyPdf2 simple code . Please help Asap

**Comment by ztravis** [comment]
Not the maintainer, but IMO I think it's pretty reasonable to fail on that PDF... it's missing a necessary component (the xref table). It would be nice if this library had the capability to rebuild damaged/missing xref data (or generally be more accommodating to malformed input) but the whole intent of that SO post is to cut away parts until the PDF is unopenable, and well, the PDF is unopenable!

**Comment by pubpub-zz** [comment]
I agree with @ztravis : the file does not respect at least 2 rules (end marker, missing startxref)
just adding at the end
```
startxref 999999 
%%EOF

```
makes the file readable. isn't this acceptable ?
for me this issue should be closed as non relevant

**Comment by MartinThoma** [comment]
Yes, let's close it. We have enough issues with real PDF files. We don't need to deal with hand-crafted broken ones as long as they don't represent a bigger group of PDFs in the wild.

**Comment by aditya-wns** [comment]
My PDF has startxref at end however still get the error pypdf.errors.PdfReadError: Broken xref table.
please let me know if there is solution.

**Comment by pubpub-zz** [comment]
A. Can you read the pdf with acrobat reader if not, it is more than probable we can not propose something
B. Please send the file. If you want to keep privacy send it by mail to @MartinThoma

**Comment by aditya-wns** [comment]
Cannot use solution A due because we saw lot of such cases and not possible to fix it manually every time.
so i have emailed you pdf file.

Thank you for your time. I appreciate it.
