### ISSUE TITLE
mergePage function not working

### ISSUE THREAD

**Issue by Avinash-Raj** [py-pdf/PyPDF2#311]
This piece of code fails to merge two pages from two pdfs into one pdf with one page..

```Python
from PyPDF2 import PdfReader,PdfWriter

f = "pdf/0a30d2ffe683080b9613b6b30c2689a4.pdf"
k = "pdf/00c2c8e1dbdeac6f5ab2b36626170dbe.pdf"

reader1 = PdfReader(f)
reader2 = PdfReader(k)
writer = PdfWriter()

# Merge two pages
page = reader1.pages[0]
page.merge_page(reader2.pages[0])
writer.add_page(page)

# Write results
with open("join.pdf", "wb") as fh:
    writer.write(fh)
```

I got only one page from file1 as output.. Seems like it's not actually merging.

**Comment by jcjones1515** [comment]
@Avinash-Raj, I think I'm seeing something similar -- did you ever get to the bottom of it?

**Comment by aryabartar** [comment]
I have the same issue, Not working for me.

**Comment by snmhas** [comment]
The function is not working for me. I have the same issue.

**Comment by MartinThoma** [comment]
Do you have examples for two pdf files that fail? Or does it fail for all PDFs?

**Comment by MartinThoma** [comment]
I think I know what was going on: If there is a full-size image merged on top of another page (e.g. because it was a scanned PDF), you will not see the page below. However, merging itself works as expected. I just verified it.
