### ISSUE TITLE
/Filter is not found in /Image

### ISSUE THREAD

**Issue by ololoe** [py-pdf/PyPDF2#323]
I'm using code from here http://stackoverflow.com/a/37055040 

    xObject = xObject['/Resources']['/XObject'].getObject()
    for name in xObject:
        obj = xObject[name]
        if obj['/Subtype'] == '/Image':

Now obj looks like this:

            {'/BitsPerComponent': 8,
             '/ColorSpace': '/DeviceGray',
             '/HDPI': 300,
             '/Height': 480,
             '/Subtype': '/Image',
             '/VDPI': 300,
             '/Width': 640}

There is no /Filter key although it's in the PDF.

**Comment by sylvainpelissier** [comment]
What is your question exactly ?

**Comment by ololoe** [comment]
> There is no /Filter key although it's in the PDF.
