### ISSUE TITLE
Dictionary with undefined indirect object and direct object for same key fails

### ISSUE THREAD

**Issue by rwirth** [py-pdf/PyPDF2#325]
I have a PDF file with a funny-looking page dict (produced using pdfLaTeX):

    <<
    /Type /Page
    % [...]
    /Group << /S /Transparency /I true /CS /DeviceRGB>>
    /Parent 61 0 R
    /Group 60 0 R % obj 60 is not defined
    >>

The file is displayed just fine and running `pdfinfo` on it works without issues. When reading, PyPDF2 (strict mode) bails out with 

    PyPDF2.utils.PdfReadError: Multiple definitions in dictionary at byte 0x1559 for key /Group

The PDF 1.7 reference is not totally clear on this situation because on the one hand it states that [3.2.6]

> A dictionary entry whose value is null (see Section 3.2.8, “Null Object”) is equivalent to an absent entry.

and [3.2.7]

> An indirect reference to an undefined object is not an error; it is simply treated as
a reference to the null object.

On the other hand it says that

> No two entries in the same dictionary should have the same key. If a key does
appear more than once, its value is undefined.

One way of reading this is that the key referencing the nonexistent object should be treated as if it was absent from the dictionary, which is IMO the most sensible interpretation.

Also, the current implementation always keeps the first value so that the outcome (in nonstrict mode) depends on the order of the entries and one might end up with the indirect reference although there is a (valid) direct object present. This is also connected to issue #236.

**Comment by MartinThoma** [comment]
Can you share a PDF that causes the issue + code to show the issue?

**Comment by MartinThoma** [comment]
I guess this was an issue with a non-conformant PDF. As we don't have a good way to verify the issue / any solution without an example PDF file, I'll close this. Please let me know if you have one / a potential solution

**Comment by pubpub-zz** [comment]
attaching the test file from @rwirth (for local ref)
[multipledefs.pdf](https://github.com/py-pdf/PyPDF2/files/9176644/multipledefs.pdf)

I've checked the file with latest version and only a warning is reported. I've created a PR to check that
