### ISSUE TITLE
Range object fails when slice is one page long

### ISSUE THREAD

**Issue by parkerhancock** [py-pdf/PyPDF2#344]
I have an application that does numerous repeated slices out of very large PDF documents. This is based on a beginning page and ending page, which neatly work with the Page Ranges concept. The only problem is that occasionally a sub-document will be a single page long. When the range is generated with:

`range = PageRange('20:20')`

a valid PageRange is created, but any subsequent PDF's created with that range will be a 306 byte unreadable file. The problem goes away if you simply use:

`range = PageRange('20')`

but, I think it makes more sense to have Page Range figure out that a range of '20:20' should be the same as '20' rather than having to deal with the special case in my code base.

Thanks!

**Comment by MartinThoma** [comment]
Can you share a PDF + minimal complete code that shows the issue?

**Comment by MartinThoma** [comment]
I think the PageRange behaves just as expected:

```python
>>> from PyPDF2 import PageRange
>>> PageRange('20:20')._slice
slice(20, 20, None)
>>> PageRange('20')._slice
slice(20, 21, None)
```

It's the same as with:

```python
>>> l[slice(1,2, None)]
[2]
>>> l[slice(1,1, None)]
[]

# which is just:
>>> l[1:2]
[2]
>>> l[1:1]
[]
```
