### ISSUE TITLE
Read page chokes on optimized pdfs in python 3

### ISSUE THREAD

**Issue by jkterry1** [py-pdf/PyPDF2#356]
In updated Ubuntu 16.04.2 with python 3.5, using the most recent available version of this package in updated pip3, I can't read text out of optimized pdf that can be read by normal pdf reading programs. page = pdf.getPage(page_num) returns an object with abnormally little text and page.extractText() on that object returns ''. Optimized pdfs are a real thing that need to be handled because google docs is now enabling it by default for pdf downloads from it in some cases (ie the original source of this). If you have any questions or want me to test anything related to this, please tell me. 

Small edit: I can't 100% confirm that the choke is caused by the attached file being an optimized pdf, but given the lacking information in the page object and how optimized pdfs work it makes sense, and I can't find any other difference between this and functional pdfs that would call this. 

Sample pdf: https://drive.google.com/open?id=0B_UFqdcYpJsZOG14WkFiM18wOVNzS0x2WFhMTVM0NUdCODJ3

**Comment by MartinThoma** [comment]
@jkterry1 Would you mind to upload such a PDF here? The sample PDF you've shared 4 years ago is no longer available, but I'd like to check if the issue still exists.

**Comment by MartinThoma** [comment]
I guess the issue is gone. Please let me know if that is not the case.
