### ISSUE TITLE
assert xrefstream["/Type"] == "/XRef"

### ISSUE THREAD

**Issue by phoccavalcante** [py-pdf/PyPDF2#357]
I cant read one PDF file because /Type == /Page and I cant understand the reason.  

`<class 'PyPDF2.generic.DictionaryObject'> {'/Parent': IndirectObject(1, 0), '/Contents': IndirectObject(4, 0), '/Type': '/Page', '/Resources': Indirec
tObject(2, 0)}`

Follow the file: http://communy.com.br/static/cobranca.pdf

Please, can anybody help me?

**Comment by guysoft** [comment]
I am getting the same issue with another PDF. That can be causing this?

**Comment by guysoft** [comment]
Workaround:
Repair the file with ghostscript

**Comment by AzizieAbuduaini** [comment]
I got this error when I try to read pdf from s3. later I found that there is some unexpected unicode character apostrophe. What i did is to replace apostrophe with "’" then read it works fine.

`text = text.replace("'", "’")` 

not sure apostrophe cause this issue but it works for me. Please try this approach and let me know it works or not.

**Comment by MartinThoma** [comment]
Can somebody create a minimal Python script that shows the issue with the shared PDF?

**Comment by MartinThoma** [comment]
The comment by @AzizieAbuduaini indicates that it might be related to #384

**Comment by MartinThoma** [comment]
As here is not PDF to check, I assume that #924 has fixed this issue. I'll release the new `PyPDF2==2.1.0` today.

Please ping me if you still encounter this issue with 2.1.0 or later.
