### ISSUE TITLE
extractText returns only empty lines for some files

### ISSUE THREAD

**Issue by hoenie-ams** [py-pdf/PyPDF2#362]
I am working on a script that "reads" PDF files and and then automatically renames the files it recognizes from a dictionary. PyPDF2 however only returns empty lines for some PDFs, while working fine for others. The code for reading the files:

```
import PyPDF2

# File name
file = 'sample.pdf'

# Open File
with open(file, "rb") as f:
    # Read in file
    pdfReader = PyPDF2.PdfFileReader(f)

    # Check number of pages
    number_of_pages = pdfReader.numPages
    print(number_of_pages)

    # Get first page
    pageObj = pdfReader.getPage(0)

    # Extract text from page 1
    text = pageObj.extractText()        

print(text)
```
It does get the number of pages correctly, so it is able to open the PDF.

If I replace the print(text) by repr(text) for files it doesn't read, I get something like:

`"'\\n\\n\\n\\n\\n\\n\\n\\nn\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n'"`

Weirdly enough, when I enhance (OCR) the files with Adobe, the script performs slightly worse. It Recognized 140 out of 800 files and after enhancing just 110.

The PDFs are machine readable/searchable, because I am able to copy/paste text to Notepad. I tested some files with "pdfminer" and it does show some text, but also throws in a lot of errors. If possible I like to keep working with PyPDF2.

Specifications of the software I am using:
Windows: 10.0.15063
Python: 3.6.1
PyPDF: 1.26.0
Adobe version: 17.009.20058

Anyone any suggestions? Your help is very much appreciated!

**Comment by datatalking** [comment]
Some PDF documents are not set up to be able to have this data pulled off.  PDF isn't always doable and working on a Windows machine is only going to increase your errors.

**Comment by samsong8610** [comment]
I have a similar issue when extracting text from a pdf in Chinese.

**Comment by davidbtg** [comment]
I have a similar issue when extracting text from an OCR'd pdf.

**Comment by khand420** [comment]
#pip install slate3k

import slate3k as slate
with open('J1.pdf', 'rb') as f:
    text = slate.PDF(f)
print(text)

**Comment by MartinThoma** [comment]
@hoenie-ams Do you have an example PDF? Maybe even one that we can add to our test suite?

**Comment by hoenie-ams** [comment]
> @hoenie-ams Do you have an example PDF? Maybe even one that we can add to our test suite?

No sorry, that was for a project I was working on years ago and I don't have any access to those documents anymore...

**Comment by MartinThoma** [comment]
As this is impossible to know if it was fixed in between / investigate the issue, I will close it.

To everybody: Please feel free to open a new issue with the necessary details! (I've added a issue template)

**Comment by Dobrosvet** [comment]
In my case, the reason was that I saved several pages from the original PDF file through printing to a file. There were 10 pages from the original and all were blank.

When I checked the same pages in the original, the text returned correctly, meaning it was there originally. However, when printing to a file, it turns into a vector.

Use or find the original file or solve the OCR problem.

I think in such cases you need to add an error output. "There are no text blocks in the file / empty. You may see the text, but it's vector-based, and you can't extract it without other methods like OCR."

**Comment by stefan6419846** [comment]
> In my case, the reason was that I saved several pages from the original PDF file through printing to a file. There were 10 pages from the original and all were blank.

This is a known limitation of some printers, especially Microsoft Print to PDF.

> I think in such cases you need to add an error output. "There are no text blocks in the file / empty. You may see the text, but it's vector-based, and you can't extract it without other methods like OCR."

I see no value in spamming the user with such messages. *pypdf* is a library which provides the basic functionality. If you discover that the stripped returned text is empty, you can always handle this yourself by calling an OCR library for example and emit messages accordingly. AFAIK there is no easy way to detect vectorized character commands reliably without doing pattern matching, which basically resolves to using OCR.
