### ISSUE TITLE
getFormTextFields throws exception if there are no fields

### ISSUE THREAD

**Issue by sr105** [py-pdf/PyPDF2#363]
If `getFields()` returns None, the generator expression will throw an exception because of `for field in None`.

Not sure what the solution should be. Probably one of these:

- getFields() should return an empty dict instead of None
- getFormTextFields() should test the result of getFields() and return None if there are no fields
https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/pdf.py#L1346

```
    def getFormTextFields(self):
        ''' Retrieves form fields from the document with textual data (inputs, dropdowns)
        '''
        # Retrieve document form fields
        formfields = self.getFields()
        return dict(
            (formfields[field]['/T'], formfields[field].get('/V')) for field in formfields \
                if formfields[field].get('/FT') == '/Tx'
)
```

**Comment by oscardssmith** [comment]
Empty dict is a better solution as it creates consistency rather than dealing with inconsistency

**Comment by MartinThoma** [comment]
I think this issue was solved:

```python
from PyPDF2 import PdfReader

reader = PdfReader("crazyones.pdf")
print(reader.get_form_text_fields())
```

prints an empty dict for me :-)
