### ISSUE TITLE
getNumPages is wrong

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/PyPDF2#364]
The reported number of pages by 

```python
from PyPDF2 import PdfReader

reader = PdfReader("example.pdf")
count = len(reader.pages)  # wrong result
```

is wrong. I have a PDF which has 45 pages (shown in Google Chrome and Atril and Master PDF editor) which has 45 pages, but PyPDF returns 50 pages.

**Comment by Fritte** [comment]
Can you give an example PDF where this is the case?

**Comment by MartinThoma** [comment]
I'm sorry, I can't share that PDF. I found it by running multiple programs - including `pdftotext -f [page] -l [page]` on every page

**Comment by Fritte** [comment]
Okay, I understand. I have recently processed a lot of documents(>1000) and I would have break for sure if I had encountered this issue.

**Comment by MartinThoma** [comment]
@Fritte For me it was one of several thousand pdfs.

**Comment by pmourelle** [comment]
So... is anybody working on this? Is pyPDF abandoned? Last release is pretty old.

**Comment by oscardssmith** [comment]
This is a really hard issue to debug without a testcase. there is currently a group working on `PyPDF3` which is a fork, so if you have an example PDF  for this issue that would be great.

**Comment by sylvainpelissier** [comment]
Are you sure there is a group working on PyPDF3 ? Last [commit](https://github.com/mstamy2/PyPDF2/commits/master) was on  Oct 13, 2016 for PyPDF3 and Apr 2, 2018 for PyPDF2.

**Comment by chukrobertson** [comment]
```
from PyPDF2 import PdfFileReader

infile = "path/to/pdf"

# Get number of pages from pdf infile
pdf = PdfFileReader(open(infile,'rb'))
numPages = pdf.getNumPages()
print(numPages)
```

**Comment by MartinThoma** [comment]
I just ran the following script on 22k PDF documents:

```
from rich.progress import track
from pathlib import Path
from PyPDF2 import PdfReader
import fitz



def verify(path: str) -> bool:
    try:
        reader = PdfReader(path)
        pypdf2_count = len(reader.pages)
    except Exception as e:
        print(f"Exception for {path}: {e}")
        return False
    
    doc = fitz.open(path)
    fitz_count = doc.page_count
    
    if pypdf2_count != fitz_count:
        print(f"{path}: pypdf2={pypdf2_count} vs fitz={fitz_count}")
        return False

    return True


def main():
    root = Path("pdf")
    paths = sorted(list(root.glob("*.pdf")))

    for path in track(paths):
        verify(path)

if __name__ == "__main__":
    main()
```

Either the issue is gone or it is super rare. I cannot reproduce it. It was very likely a very broken document.
