### ISSUE TITLE
addBookmark fails when bookmark contains non-ascii characters

### ISSUE THREAD

**Issue by rwirth** [py-pdf/PyPDF2#368]
Adding a bookmark to a PDF using the `PdfFileWriter` class raises a unicode-conversion error on python 2.7 when the bookmark title contains non-ascii characters. The offending line is

    dest = Destination(NameObject("/"+title + " bookmark"), pageRef, NameObject(fit), *zoomArgs)

Apart from the name being against the PDF spec (contains unescaped whitespace and other illegal characters, depending on the content of `title`), `dest` is only used to extract an array object identfying the bookmark target so that the name itself is never referenced. I've fixed the problem by passing a null object

    dest = Destination(NullObject(), pageRef, NameObject(fit), *zoomArgs)

**Comment by MartinThoma** [comment]
Can you share a PDF + minimal complete code that shows the issue?

**Comment by MartinThoma** [comment]
It seems to work now:

```python
from PyPDF2 import PdfReader, PdfWriter

reader = PdfReader("example.pdf")
writer = PdfWriter()
page = reader.pages[0]
writer.insert_page(page, 0)
writer.add_bookmark(
        "A booЖkmark", 0, None, (255, 0, 15), True, True, "/FitBV", 10
    )

with open("out.pdf", "wb") as fp:
    writer.write(fp)
```
