### ISSUE TITLE
508 compliant

### ISSUE THREAD

**Issue by taoxu2016** [py-pdf/PyPDF2#371]
Merged PDF file is not 508 compliant.

**Comment by MartinThoma** [comment]
What is 508? Why would you expect them to be compliant?

**Comment by taoxu2016** [comment]
Section 508 of the Rehabilitation Act (29 U.S.C. § 794d), as amended by the Workforce Investment Act of 1998 (P.L. 105-220) requires federal agencies to develop, procure, maintain and use information and communications technology (ICT) that is accessible to people with disabilities - regardless of whether or not they work for the federal government. The US Access Board established the Section 508 standards that implement the law and provides the requirements for accessibility.

**Comment by MartinThoma** [comment]
Gotcha! Thanks for the explanation!

Why is the merged PDF not complient? How can a PDF be compliant?

**Comment by mstamy2** [comment]
While accessibility is always important to consider, the sample PDFs are collected for test purposes rather than for human reading. They represent unique structures or are cases that PyPDF2 failed to parse in the past. Many aren't even fully PDF compliant.
