### ISSUE TITLE
PyPDF2 doesn't read Cyrillic letters

### ISSUE THREAD

**Issue by ArtyomKaltovich** [py-pdf/PyPDF2#375]
Hello, all.
When I tried to read this file http://rec.gov.by/sites/default/files/pdf/Elections-PRB2015-itog1.pdf
I got only digits, but no letters.
I used following code:

```python
import PyPDF2

reader = PyPDF2.PdfFileReader("Elections-PRB2015-itog1.pdf")
page = reader.pages[0]
print(page.extract_text())
```

Is it my mistake or bug?

**Comment by ildarcheg** [comment]
Have the same issue reading http://council.gov.ru/media/files/2vOAaTSYRa8ZWgI90Eyvox26Z3Gff5kE.pdf

**Comment by SlavaSTiwari** [comment]
Any solutions to this issue?
Please do share.

**Comment by MartinThoma** [comment]
#464 might help

**Comment by MartinThoma** [comment]
Using PyPDF2==2.4.0, it seems to work. I'm closing this now - please let me know if you encounter issues with the latest version of PyPDF2.
