### ISSUE TITLE
ENH: Confining user selection to text blocks

### ISSUE THREAD

**Issue by dmalan** [py-pdf/PyPDF2#376]
We're currently using PyPDF2 to "concatenate" two PDFs side by side so that, for instance, two 6.5"x8.5" PDFs (e.g., `left.pdf` and `right.pdf`) become one 11"x8.5" PDF (e.g., `new.pdf`), as with the code below:

```py
from copy import copy
from PyPDF2 import PdfFileReader, PdfFileWriter

new_pdf = PdfFileWriter()
with open("left.pdf", "rb") as left_file, open("right.pdf", "rb") as right_file:

    left_pdf = PdfFileReader(left_file)
    right_pdf = PdfFileReader(right_file)

    left_page = copy(left_pdf.getPage(0))
    right_page = copy(right_pdf.getPage(0))

    left_page.mergeTranslatedPage(right_page, left_page.mediaBox[2], 0, expand=True)

    new_pdf.addPage(left_page)

    with open("new.pdf", "wb") as new_file:
        new_pdf.write(new_file)
```

The result looks great:

![screen shot 2017-11-08 at 12 03 48 pm](https://user-images.githubusercontent.com/788678/32562535-ea8832d0-c47c-11e7-998e-4703663fb566.png)

But highlighting/selecting text tends to behave suboptimally, at least in Preview on macOS. For instance, trying to highlight just the lefthand text, as by clicking just to the left of the top-left `1` and dragging downward, yields:

![new](https://user-images.githubusercontent.com/788678/32562673-39532622-c47d-11e7-80ef-b8acdadfae17.png)

Ideally, though, it'd be possible to highlight only the left side's content, as though it were a true column of text.

This might just be a shortcoming of Preview (or a challenge with PDFs themselves), but might there nonetheless be something we could do differently with our usage of PyPDF2 to (try to) avoid this behavior? 

For context, we're generating `left.pdf` and `right.pdf` from `.txt` files using [WeasyPrint](https://github.com/Kozea/WeasyPrint) (and [Pygments](http://pygments.org/) for line numbers and, in other scenarios, syntax highlighting), so we do have control over the raw input, if hinting the input somehow might help. The overall workflow is currently: 2 text files --> Pygments --> 2 HTML files --> WeasyPrint --> 2 PDF files --> PyPDF2 --> 1 PDF file.

(We're seeing this behavior with PyPDF2 1.26.0 on Ubuntu 16.04.)

Many thanks!

**Comment by MartinThoma** [comment]
@dmalan Thank you for sharing this idea with images :heart: 

I'm sorry nobody responded to it so far. I would like to offer this, but I have no clue how to do it.

**Comment by MartinThoma** [comment]
As this feature request didn't receive an update for a long time, I'm closing it.

I'm linking it in https://github.com/py-pdf/PyPDF2/discussions/1181 so that we don't forget about it. Please feel free to add more information here (PDFs that use it; other projects that implement it; explanations how it would improve PyPDF2). If we get closer to implementing it / have less open topics, I will re-open it :-)
