### ISSUE TITLE
PdfReadError: Could not read Boolean object

### ISSUE THREAD

**Issue by tataganesh** [py-pdf/PyPDF2#377]
I am getting the following error for certain PDFs. Due to the confidential nature of these documents, I can't share them, but I can try and provide information which can help solve this problem.
Stacktrace - 
```
    inputpdf = PdfFileReader(open(pdfpath, "rb"), strict=False)
  File "/home/tata/.virtualenvs/obu/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/tata/.virtualenvs/obu/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1732, in read
    num = readObject(stream, self)
  File "/home/tata/.virtualenvs/obu/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 74, in readObject
    return BooleanObject.readFromStream(stream)
  File "/home/tata/.virtualenvs/obu/local/lib/python2.7/site-packages/PyPDF2/generic.py", line 137, in readFromStream
    raise utils.PdfReadError('Could not read Boolean object')
PdfReadError: Could not read Boolean object
```
The exception seems to be raised from the following function, in **generic.py**:

```python
    def readFromStream(stream):
        word = stream.read(4)
        if word == b_("true"):
            return BooleanObject(True)
        elif word == b_("fals"):
            stream.read(1)
            return BooleanObject(False)
        else:
            raise utils.PdfReadError('Could not read Boolean object')
```
Printing the variable `word` yields **trai**. Can anyone suggest a solution for this issue?

**Comment by ganeshtata** [comment]
It seems as if all these pdfs are encrypted in some way. Using the solution cited in this issue https://github.com/mstamy2/PyPDF2/issues/53 , 
That is, using the following command - 
`qpdf --password= --decrypt input.pdf output.pdf`
and then reading **output.pdf** worked for me. I am not sure as to how I can determine beforehand, whether a pdf is encrypted ( or in this particular state ) or not.

**Comment by hvbtup** [comment]
I had the same error for a signed document (Austrian "Amtssignatur"). The file contained the sequence

    xref
    trailer

I think this violates the PDF 1.7 specification which says that a cross reference section (marked by the xref) consist of one or more subsection, but here we have zero subsections.
Anyway, all the browsers and Adobe Reader render the document without an error.

The signed PDF obviously uses the "incremental update" feature of the PDF format.

**Comment by hvbtup** [comment]
@ganeshtata , please reopen the issue.

**Comment by MartinThoma** [comment]
#1015 could fix this issue

**Comment by MartinThoma** [comment]
As there is no pdf, we can not confirm that it's solved. I assume it is and hence I'll close the issue.

Please let me know if you still encounter the same issue with the latest PyPDF2 version (and please attach the pdf, if possible)

**Comment by isriam** [comment]
i am able to reproduce this issue with a pdf and pypdf.  what information would help to provide?

**Comment by pubpub-zz** [comment]
@isriam 
Please create a new issue. It will be easier to track
