### ISSUE TITLE
PyPDF2 can't decrypt PDF files with Acrobat 6.0 or higher password security compatibility

### ISSUE THREAD

**Issue by apaksoy** [py-pdf/PyPDF2#378]
Hi,

I get the "NotImplementedError: only algorithm code 1 and 2 are supported" error when I try the .decrypt() method on a PDF file saved with password security compatible with Acrobat 6.0 or higher.  

Below is the code I used for decryption trials. Also below are the links to four different versions of the same file saved with the specified compatibilities in their filenames as examples. All have the same password 'password' (without the quotes). 

I tried this with other PDF files and got the same result. That is, no error when saved with Acrobat 5.0 password security compatibility and always an error when saved with Acrobat 6.0 or higher password security compatibility. 

I used Adobe Acrobat Pro X to save a file with different password security compatibilities. I have PyPDF2 1.26.0 installed on Python 3.6.3 on mac OS 10.13.1. Thank you.

```
from PyPDF2 import PdfReader

filenames = [
    "test_file_acrobat_5.pdf",
    "test_file_acrobat_6.pdf",
    "test_file_acrobat_7.pdf",
    "test_file_acrobat_10.pdf",
]

for filename in filenames:
    reader = PdfReader(filename)
    try:
        # print decryption outcome as 1 if successful and 0 otherwise
        print(filename, reader.decrypt("password"))
    except NotImplementedError as errMsg:
        print(filename, "can not be decrypted on error message", errMsg)

```

[test_file_acrobat_5.pdf](https://github.com/mstamy2/PyPDF2/files/1468054/test_file_acrobat_5.pdf)
[test_file_acrobat_6.pdf](https://github.com/mstamy2/PyPDF2/files/1468055/test_file_acrobat_6.pdf)
[test_file_acrobat_7.pdf](https://github.com/mstamy2/PyPDF2/files/1468056/test_file_acrobat_7.pdf)
[test_file_acrobat_10.pdf](https://github.com/mstamy2/PyPDF2/files/1468057/test_file_acrobat_10.pdf)

**Comment by ganeshtata** [comment]
Possible duplicate https://github.com/mstamy2/PyPDF2/issues/53?

**Comment by apaksoy** [comment]
I am not sure why but [#53](https://github.com/mstamy2/PyPDF2/issues/53) seems to have been closed. This problem, however, still continues.

**Comment by ganeshtata** [comment]
@apaksoy It seems as if no permanent fix has been made for this, but one of the solutions ( which suggests the use of the command-line utility **qpdf** ), worked fine for me. Could you try the same for your failed cases?

**Comment by apaksoy** [comment]
I will be away for about a week. Will try and post here when I return.

**Comment by maxiplux** [comment]
hello everybody , any news about this issue ?

**Comment by maxiplux** [comment]
my friend add this line to your code inputpdf.decrypt('').
 inputpdf = PdfFileReader(open(full_file_name, "rb"))
inputpdf.decrypt('')
 for index,temp_tracking_number in enumerate(self.additional_tracking_codes):
                        output = PdfFileWriter()
                        output.addPage(inputpdf.getPage(index))
                        with open(str(temp_tracking_number) + ".pdf")) , "wb") as outputStream:
                            output.write(outputStream)

**Comment by apaksoy** [comment]
@ganeshtata  Thank you for the suggestion but qpdf but does not work for me because I am looking for a solution within PyPDF2.

@maxiplux   Thx but I am not exactly sure what you are suggesting as new. As I mentioned in my original post, the code I posted already works for PDF files with Acrobat 5.0 password security compatibility (or PDF files created via PyPDF2).  

I did not paste the part of the code that copies the pages to a new PDF file and writes it to disk in the original post because it makes no difference if a file can not be decrypted at the first place. Can you  pls also properly mark your code, i.e. use the grave accent ` in triple form, when you include code in your messages here?

**Comment by ganeshtata** [comment]
@apaksoy The problem is, PyPDF2 doesn't support certain encryption algorithms, yet. This https://github.com/mstamy2/PyPDF2/issues/226 indicates that decryption for some encryption algorithms is yet to be implemented.  I know you are looking for a solution within PyPDF2, but in case you ever plan to venture out for a similar library, you can take a look at [pikepdf](https://pypi.python.org/pypi/pikepdf/0.1rc4), a python library that uses qpdf.

**Comment by Fabian1337** [comment]
any update on this ?
i am not able to move with my system to qpdf so i am looking for some python based solution :/

**Comment by KrisLloyd** [comment]
I would also like updates regarding this issue

**Comment by c0nb4** [comment]
Work around for me was using PyMuPDF. Depending on the use case I either used it directly or saved the file again and the reopend it with the regular framework.

**Comment by Fabian1337** [comment]
@c0nb4 since PyMuPDF is based on MuPDF its under AGPL license and if you use it inside your project that you are distributing... you have to distibute as AGPL aswell or buy a license.

**Comment by dkhaitan82** [comment]
PyPDF can be used to open encrypted files (Created by Acrobat 6.0). Below is the simple code:
Output file is no longer password protected. 
```
    with Pdf.open(v_in_file,password=v_password) as pdf:
        pdf.save(v_out_file)
```

**Comment by manohar9600** [comment]
Thanks bro, it worked.
I opened pdf using pikepdf and saved it. Reopened using PyPDF2.

**Comment by Sibgha360** [comment]
> PikePDF can be used to open encrypted files (Created by Acrobat 6.0). Below is the simple code: Output file is no longer password protected.
> 
> ```
> from pikepdf import Pdf
>     with Pdf.open(v_in_file,password=v_password) as pdf:
>         pdf.save(v_out_file)
> ```

Mine wasn't password-protected so removing the second argument worked.

**Comment by MartinThoma** [comment]
Might be fixed with #749

**Comment by MartinThoma** [comment]
Running the example from above, I get:

```
test_file_acrobat_5.pdf PasswordType.OWNER_PASSWORD
test_file_acrobat_6.pdf PasswordType.OWNER_PASSWORD
test_file_acrobat_7.pdf PasswordType.OWNER_PASSWORD
test_file_acrobat_10.pdf PasswordType.NOT_DECRYPTED
```

**Comment by MartinThoma** [comment]
@exiledkingcc The `test_file_acrobat_10.pdf` still seems to fail. Do you have an idea why? I can decrypt it with `"password"` in my PDF reader. So it's definitely not a wrong password issue.

**Comment by exiledkingcc** [comment]
it failed at `verify_perms`, which can be ignored. 
i checked qpdf, it gnores if verify_perms failed.
