### ISSUE TITLE
getOutlines() returns repeated items

### ISSUE THREAD

**Issue by aalvrz** [py-pdf/PyPDF2#381]
When obtaining the outline of a PDF file:

```python
with open(file_path, 'rb') as pdf_file:
    pdf_reader = PyPDF2.PdfFileReader(pdf_file)
    outlines = pdf_reader.getOutlines()
```

The method returns repeated items in the list. For example:

```python
[
{'/Title': 'Working with a virtual environment', '/Page': IndirectObject(327, 0), '/Type': '/XYZ', '/Left': <PyPDF2.generic.NullObject object at 0x7f06aba3f278>, '/Top': <PyPDF2.generic.NullObject object at 0x7f06aba3f2b0>, '/Zoom': <PyPDF2.generic.NullObject object at 0x7f06aba3f2e8>}, 

{'/Title': 'Working with a virtual environment', '/Page': IndirectObject(327, 0), '/Type': '/XYZ', '/Left': <PyPDF2.generic.NullObject object at 0x7f06aba3f278>, '/Top': <PyPDF2.generic.NullObject object at 0x7f06aba3f2b0>, '/Zoom': <PyPDF2.generic.NullObject object at 0x7f06aba3f2e8>}, 

# ...

]
```

The 1st item should actually be another one with `Title` of `Introduction`:

**Comment by MartinThoma** [comment]
Could you share a pdf that causes these issues?

**Comment by mtd91429** [comment]
Without a PDF to test and compare, I can only guess. However, I believe that this issue is related to #1121 and is fixed by PR #1128

**Comment by MartinThoma** [comment]
Yes, it looks like that to me as well. Thank you for the hint :hugs: 

I'm closing this issue now as I assume that `PyPDF2==2.6.0` has fixed this issue. Please let me know if you see it again with the latest PyPDF2 version.

**Comment by jayantsolanki** [comment]
> Could you share a pdf that causes these issues?

I am very sorry, I missed this. issue happened when I was interning somewhere. I don't have access to that pdf anymore (was proprietary). [#1121](https://github.com/py-pdf/PyPDF2/issues/1121) seems to tackle the similar issue. By the way, hugely appreciate the development done by you guys and keeping PyPDF alive. PyPDF2 for me has been a very versatile tool. I referenced your work in one of our paper [How SAS® and Python Enhance PDF](https://www.sas.com/content/dam/SAS/support/en/sas-global-forum-proceedings/2019/3009-2019.pdf)
