### ISSUE TITLE
PyPDF2 does not add links

### ISSUE THREAD

**Issue by jazeera11** [py-pdf/PyPDF2#383]
I am working with version 1.26 of the package. I am trying to modify links by removing and adding links in a PDF document but for version 1,5 (Acrobat ver 6) it does not add links at all. Anything that is Version 1.3 or lower it works just fine. I have seen folks post issues connected with version but nothing related to Links & URIs. Is there a workaround solution?

**Comment by jazeera11** [comment]
I must correct some of the things I have stated. The PDF documents I have tested were both derived from MS Word 2013 and the PDF versions were 1.5. but only one converts very easily with modified links/URI but the other one does not.. I am only able to remove the links but not Add new links.

**Comment by MartinThoma** [comment]
Would https://github.com/py-pdf/PyPDF2/pull/269 solve this issue?

**Comment by MartinThoma** [comment]
I assume that this issue is solved. If anybody encounters this issue again with the latest PyPDF2 version, please let me know.
