### ISSUE TITLE
InvalidOperation: Invalid Literal for Decimal '0.0000-74251147' 

### ISSUE THREAD

**Issue by jcampbell05** [py-pdf/PyPDF2#386]
It seems some PDFs can have invalid references such as this. I'm not sure how this happens as this is a PDF a user has uploaded to our service.

Ghostscript when it encounters this reference, treats the value as if it was "0.0". Even though it maybe wrong (it warns us though). It would be nice if PYPDF2 could do this too.

Let me know where I can patch this.

<img width="716" alt="screen shot 2018-01-03 at 19 28 59" src="https://user-images.githubusercontent.com/1484989/34536299-9d3b8d6c-f0bc-11e7-87f2-093929e4cc3a.png">

**Comment by ktowen** [comment]
Any news on this?
