### ISSUE TITLE
IndirectObject has no len()

### ISSUE THREAD

**Issue by TZanke** [py-pdf/PyPDF2#399]
Trying to extract the text from a PDF failed with `PyPDF2==2.4.2`

## MCVE: Code + PDF

The PDF: [`pdf/1d652bd0d8c958b28b6b5a0e53cfe66e.pdf`](https://corpora.tika.apache.org/base/docs/govdocs1/976/976970.pdf)

```
>>> from PyPDF2 import PdfReader
>>> reader = PdfReader('pdf/1d652bd0d8c958b28b6b5a0e53cfe66e.pdf')
>>> reader.pages[1].extract_text()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 1316, in extract_text
    return self._extract_text(self, self.pdf, space_width, PG.CONTENTS)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_page.py", line 1138, in _extract_text
    content = ContentStream(content, pdf, "bytes")
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1191, in __init__
    stream_data = stream.get_data()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1157, in get_data
    decoded._data = decode_stream_data(self)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/filters.py", line 508, in decode_stream_data
    if len(filters) and not isinstance(filters[0], NameObject):
TypeError: object of type 'IndirectObject' has no len()
```

**Comment by kickhad** [comment]
Was this ever resolved?

**Comment by lovelysusie** [comment]
Hi, I also got the same issue, can someone help to investigate? Many thanks!

**Comment by ThisIsVenkatesh** [comment]
I too have the same issue. Can someone please help on this?

**Comment by MartinThoma** [comment]
Please share the code that caused the issue (minimal but complete). as well as the pdf

**Comment by TZanke** [comment]
Cannot find any ticket related to this issue on our side. So this trace is the only code i can share. Its to old to find it in any server-logs as well. Maybe one of the others can help?

Side note: The issue may still exist, but we fixed the issue probably by any command line pdf resave. Dont like to disable this in production just to find the issue again. ;)

**Comment by MartinThoma** [comment]
I will close this for the moment:

**@everybody: Please let me know if you have this issue!** Share at least the version of PyPDF2 you're using and - if possible - also the PDF!

**Comment by MartinThoma** [comment]
I found a minimal example and added it to the first post.

**Comment by MartinThoma** [comment]
Another example: https://corpora.tika.apache.org/base/docs/govdocs1/976/976970.pdf

**Comment by MartinThoma** [comment]
@TZanke Thank you for pointing out the issue - I've just fixed it and will release a new version tomorrow.

If you want, I can add you as a contributor: https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by TZanke** [comment]
Thank you, but right now i don't need to be mentioned. Thank you for the fix!
