### ISSUE TITLE
PyPDF2.utils.PdfReadError: file has not been decrypted

### ISSUE THREAD

**Issue by manish59** [py-pdf/PyPDF2#416]
I was trying to read the fileds in a pdf form. The Pypdf2 is kicking me with this error. I tired to see if it is encrypted using pypdf2.isencrypted but it is giving me that it is not encrypted. please let me know if any one know this

## MCVE

File: https://www.fda.gov/downloads/AboutFDA/ReportsManualsForms/Forms/UCM074728.pdf

```python
from PyPDF2 import PdfFileReader

reader = PdfFileReader("FDA-1572_508_R6_FINAL.pdf")
fields = reader.get_form_text_fields()
print(fields)
```

**Comment by oscardssmith** [comment]
Can you provide a copy of your pdf and the code you are using? Both of these will be very helpful for troubleshooting

**Comment by manish59** [comment]
https://www.fda.gov/downloads/AboutFDA/ReportsManualsForms/Forms/UCM074728.pdf

**Comment by MartinThoma** [comment]
Note to myself: The file is NOT encrypted. PyPDF2 only thinks it is.

**Comment by pubpub-zz** [comment]
If you open the document with acrobat reader and look at the protections/permissions, you will note that there is some permission removed (eg assembling). When you set the permissions like that, the file has an admin password and if you want to open it as a user you use an empty password : this is typically the case of the pdf reference https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf
If you check with acrobat reader you will get:
![image](https://user-images.githubusercontent.com/4083478/173235513-ae0b6211-266d-4807-adaa-d3b3d94373a1.png)

I've tried the open your file with "" password but the encryption but AES-128 seems to not be supported yet  by PYPDF2😌

**Comment by bchandos** [comment]
Is it confirmed that PyPDF2 does not support AES-128 encryption? I have an AES encrypted PDF files generated by Acrobat Sign (that unfortunately I cannot share) that will not decrypt. The PDF document linked above initially exhibits the same behavior, but after using the "trick" in [issue 652](https://github.com/py-pdf/PyPDF2/issues/652) of accessing `len(reader.pages)` to force decryption, it appears to work.

However, the "trick" doesn't work on my file - I cannot compel PyPDF2 to read or merge it.

The other differences between the example file above and my file, as reported by `pdfinfo`:
My file is v1.7 (vs. 1.6)
My file has encryption protecting change and addNotes (vs. change)

```
$ python -m platform
Linux-5.17.6-300.mbp.fc33.x86_64-x86_64-with-glibc2.35

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.3.1
```
Here's what I mean, which is hopefully more clear:

```
​Python 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyPDF2 import PdfReader
>>>
>>> reader1 = PdfReader("FDA-1572_508_R6_FINAL.pdf")
>>> reader2 = PdfReader("my-file.pdf")
>>> reader1.metadata
Traceback (most recent call last):
  <snip>
PyPDF2.errors.PdfReadError: file has not been decrypted
>>> reader2.metadata
Traceback (most recent call last):
  <snip>
PyPDF2.errors.PdfReadError: file has not been decrypted
>>> len(reader1.pages)
2
>>> reader1.metadata
{'/Author': 'PSC Publishing Services', '/CreationDate': "D:20130522104413-04'00'", '/Creator': 'PScript5.dll Version 5.2.2', '/ModDate': "D:20190405072352-04'00'", '/Producer': 'Acrobat Distiller 9.0.0 (Windows)', '/Subject': 'Statement of Investigator', '/Title': 'FORM FDA 1572'}
>>> len(reader2.pages)
Traceback (most recent call last):
  <snip>
PyPDF2.errors.PdfReadError: file has not been decrypted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  <snip>
PyPDF2.errors.PdfReadError: File has not been decrypted
>>> reader2.metadata
Traceback (most recent call last):
  <snip>
PyPDF2.errors.PdfReadError: file has not been decrypted
>>>
```

**Comment by MartinThoma** [comment]
> Is it confirmed that PyPDF2 does not support AES-128 encryption?

`PyPDF2>=2.3.1` does support AES-128 and AES-256 decryption (not encryption though).

**Comment by bchandos** [comment]
Thank you for confirming. As noted above, I do have an AES-encrypted file that fails to decrypt on 2.3.1. Unfortunately I can't share it and I can't find any Linux application that will generate and equivalent example file (PDF 1.7, AES-128bit). If I do, I will create a new issue.

**Comment by MartinThoma** [comment]
There are several aspects to encryption in PDF and I cannot claim that I understand all of them.

* One is the encryption algorithm. PyPDF2 only supported RC4 for a while, but with 2.3.1 also supports AES-128 and AES-256 for decryption.
* The Revision `/R` of the standard security handler. PyPDF2 supports 2-5, but there is 6 as well which will be added with https://github.com/py-pdf/PyPDF2/pull/1015
* There are also Crypt filters

The PDF 1.7 reference has the details in Chapter 3 "Password Algorithms"

@exiledkingcc is the expert on those topics :-)

**Comment by exiledkingcc** [comment]
empty password encryped pdf, like #652.
my last commmit of #1015 will fix this.

**Comment by stefan6419846** [comment]
This is FDA Form 1572, originally published by the U.S. FDA. Uploaded here because the FDA download URL is no longer reliable enough for CI: [issue_416.pdf](https://github.com/user-attachments/files/31998867/issue_416.pdf)
