### ISSUE TITLE
Unable to Install PyPDF2 of Rapberppy Pi3 for Python3.4

### ISSUE THREAD

**Issue by mystic12** [py-pdf/PyPDF2#417]
I have been able to install PyPDF2 for Python 2.7 on  my Pi3, but not for Python 3.4, which I need to use.  I'm a hardware person, so excuse my limited Python & Pi3 experience.  Here is what the Pi3 screen says:
pi@raspberrypi:~ $ pip install PyPDF2
Requirement already satisfied (use --upgrade to upgrade): PyPDF2 in /usr/local/lib/python2.7/dist-packages
Cleaning up...

pi@raspberrypi:~ $ pip3 install PyPDF2
Downloading/unpacking PyPDF2
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement PyPDF2
Cleaning up...
No distributions at all found for PyPDF2
Storing debug log for failure in /home/pi/.pip/pip.log

Thank you!
Patrick

**Comment by MartinThoma** [comment]
Could you please try that again?

**Comment by MartinThoma** [comment]
Python 3.6+ is now recommended :-)
