### ISSUE TITLE
PyPDF2 is not format aware 

### ISSUE THREAD

**Issue by SharmileeS** [py-pdf/PyPDF2#42]
I am not able to read text which proper formatting and spaces are not handled during extraction:

PreemptiveInformationExtractionusingUnrestrictedRelationDiscoveryYusukeShinyamaSatoshiSekineNewYorkUniversity715,Broadway,7thFloorNewYork,NY,10003fyusuke,sekineg@cs.nyu.eduAbstractWearetryingtoextendtheboundaryofInformationExtraction(IE)systems.Ex-istingIEsystemsrequirealotoftimeandhumanefforttotuneforanewscenario.

Is it true that pypdf2 is not format aware as given here: http://victorwyee.com/python/convert-pdf-to-text-pypdf-pdfminer-first-impression/

**Comment by jgyllinsky** [comment]
This issue is still a problem in May 2017. Version was pypdf2-1.26.0 as installed via pip on Ubuntu 16.04 lts.

**Comment by attibalazs** [comment]
I am facing similar issues when extract text from a lot of research papers from arxiv.org

> Thisnoteismotivatedbythecelebratedoneandtwomutualfundtheorems[3].
> ThesebuildontheworkofMarkowitzin[2]andtellusthat,intheMarkowitz
> marketmodelwithnorestrictionsonshortselling,aninvestorwhoisonly
> interestedintheoptimalinvestmentproblemscansafelyignoreallbutatwo-
> dimensionalsubspaceofthespaceofportfolios.Butwhatifone'sinterests
> aremorebroadrangingthantheseoptimalinvestmentproblems?Arethere

**Comment by jgyllinsky** [comment]
If someone knows how to get spaces (' '), from PyPDF2 that would be very helpful. @attibalazs please let me know if you resolve this.

**Comment by attibalazs** [comment]
i switched to using pdfminer, i installed the version for python 3.6 pdfminer.six

**Comment by MartinThoma** [comment]
#924 improved the situation a lot. As here is no PDF linked / uploaded, I assume the upcoming release (2.1.0) will fix the issue.
