### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect data check

### ISSUE THREAD

**Issue by zegrep** [py-pdf/PyPDF2#422]
We have do deal with a huge amount of broken PDF files. The creator is "jsPDF 1.x-master". These files are not totally corrupted. It would be nice to get the readable content.
I found a solution on [stackoverflow](https://stackoverflow.com/questions/26794514/how-to-extract-data-from-corrupted-gzip-files-in-python) and it works fine for our needs.

**PyPDF2/filters.py**
```python
    def decompress(data):
        try:
            return zlib.decompress(data)
        except zlib.error:
            return decompress_corrupted(data)

    def decompress_corrupted(data):
        d = zlib.decompressobj(zlib.MAX_WBITS | 32)
        f = StringIO(data)
        result_str = b''
        buffer = f.read(1)
        try:
            while buffer:
                result_str += d.decompress(buffer)
                buffer = f.read(1)
        except zlib.error:
            pass
        return result_str
```

**Comment by zegrep** [comment]
[corrupted.pdf](https://github.com/mstamy2/PyPDF2/files/2053349/corrupted.pdf)

**Comment by zegrep** [comment]
[zen_of_python_corrupted.pdf](https://github.com/mstamy2/PyPDF2/files/2053709/zen_of_python_corrupted.pdf)

**Comment by Pragabhava** [comment]
This solution worked for me while facing an `Error -5 while decompressing data: incomplete or truncated stream` due to improper end of line handling in stream (`\r\n` vs. `n`).

**Comment by Pragabhava** [comment]
This fix helped me deal with an `Error -5 while decompressing data: incomplete or truncated stream` for what I think is an improper end of line handling of a byte stream (Windows `\r\n` vs. Linux `\n`). I only had to replace `f = StringIO(data)` for `f = BytesIO(data)`

**Comment by MartinThoma** [comment]
It seems as if this issue is gone with `PyPDF2==2.3.0`:

```
>>> from PyPDF2 import PdfReader
>>> reader = PdfReader("zen_of_python_corrupted.pdf")
>>> reader.metadata
{'/Producer': 'GPL Ghostscript 9.18', '/CreationDate': "D:20180530133107+02'00'", '/ModDate': "D:20180530133107+02'00'", '/Title': 'zen_of_python.txt', '/Author': '', '/Creator': 'a2ps version 4.14'}
```

Thank you for reporting it!
