### ISSUE TITLE
PDF Watermarks losing functionality

### ISSUE THREAD

**Issue by paul-apacio** [py-pdf/PyPDF2#431]
I have two pdf pages.  One has a design, the other is blank, but has a PDF watermark set with Adobe Acrobat to display on screen, but not when printed.   If I merge these two pages together it seems to lose whatever it is that makes that watermark disappear, and the watermark stays on top of the image when printed.  
If I open the generated file up in Adobe Acrobat, it recognises that a watermark is on the file, and even displays the watermark's appearance settings as being not on print, but still the watermark appears, unless I reset the watermark value for Show when printing, and hit okay.  It seems like some tiny value is getting mangled on merge, but acrobat still vaguely recognises it in the outputted file.

Does anyone have an idea why this might be happening, and if there is a way to fix this programmatically?  Unfortunately my users can't be opening and editing the files to turn the watermark off.

**Comment by MartinThoma** [comment]
Do you have example code + pdf(s)?

**Comment by MartinThoma** [comment]
#508 might be related

**Comment by MartinThoma** [comment]
I cannot reproduce this issue. I can open this issue again, if anybody can share an example PDF document or more information. Please also let me know if the problem still occurs with the latest PyPDF2 version.
