### ISSUE TITLE
The function `readUntilRegex` fails to read number at the end of the stream.

### ISSUE THREAD

**Issue by jorgeecardona** [py-pdf/PyPDF2#435]
Hi,

I am working with a PDF file (sadly I can't share it with you) that contains an Object (a length) and this one is at the end of the stream. 

A BytesIO object is created with the data of the stream, the call to `read(16)` in utls.py:128 fails since there are only 5 bytes left. It fails in the sense that the second call returns an empty object bytes and the conditional fails. 

The parameter `ignore_eof` is not set when the method is called from `NumberObject.readFromStream` and this raises an Exception that is detected by the line 1631 in pdf.py and later turns into a NullObject.

There is a comment in pdf.py inside the except block: `# Replace with null. Hopefully it's nothing important.`

In my case is a Length that is needed later in a read, is important so turning to Null is not useful.

Why is the parameter ignore_eof in method readUntilRegex not set to True? 
The current implementation is simply not capable of checking the last element of the stream, it would always fail by default. 

Multiple intermediate buffers are created, in case the stream of the file is used it makes sense to set that parameter to false, but with all the streams in a separate buffer of smaller length it is more than possible to have an important piece of data at the end of the stream.

I will push that change into my own fork, but I am not aware if you can do it as well, can that change break something?

Bye.

**Comment by MartinThoma** [comment]
Do you have an example code + PDF?

**Comment by MartinThoma** [comment]
I'm closing this for the moment. If anybody has example code + a PDF to show the issue, please leave a comment :-)
