### ISSUE TITLE
New release to pypi

### ISSUE THREAD

**Issue by md384** [py-pdf/PyPDF2#445]
Is there going to be a new release to pypi anytime soon? The last one was in May 2016 but there have been multiple improvements since then (in particular, #294).

Thank you.

**Comment by alexis-via** [comment]
That would be really great ! Just make a release of the current git master branch, no extra work needed.

**Comment by claird** [comment]
Yes and no.

I've created a PyPDF4, and plan all further work--and I plan a LOT of
work--there.  Let's expect a PyPI release *of PyPDF4* within the next
week.  Fair?

Cameron Laird, vice president
We make computers work for people.

**Comment by claird** [comment]
Is there a better way to post progress updates than <URL:
https://twitter.com/Pdf4Py >?

Cameron Laird, vice president
We make computers work for people.

**Comment by xilopaint** [comment]
> Is there a better way to post progress updates than <URL:
> https://twitter.com/Pdf4Py >?

Twitter is great to me.

**Comment by darkdragon-001** [comment]
Looking forward to see #337 published!

**Comment by MartinThoma** [comment]
There just was a new release :-)

**Comment by MartinThoma** [comment]
H
