### ISSUE TITLE
No module named 'PyPDF2'

### ISSUE THREAD

**Issue by KugelschreiberY** [py-pdf/PyPDF2#456]
Hi there,

I tried to install PyPDF2 via pip using python 3.6 on MacOS with the command:
`pip3 install PyPDF2`
Unfortunately when trying to import PyPDF2, it get a ModuleNotFoundError. 

Through my search, I also stumbled over some dependency to pdfmerge, but installing it just threw another error. Regarding to other people who had the same problem, setuptools has to be updated.
But running
`pip3 install --upgrade setuptools`
did not help. I hope this is the right place to report/ask for help. 
Thanks!

**Comment by KugelschreiberY** [comment]
Still cannot get it work with python 3.6, using python 2.7 works like a charm.

**Comment by jugmac00** [comment]
On Ubuntu 18.04 with Python 3.6.7 there seems to be no issue.

`~/Projects/test_pypdf2$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyPDF2
>>> dir(PyPDF2)
['PageRange', 'PdfFileMerger', 'PdfFileReader', 'PdfFileWriter', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'filters', 'generic', 'merger', 'pagerange', 'parse_filename_page_ranges', 'pdf', 'utils']
>>> PyPDF2.PdfFileMerger
<class 'PyPDF2.merger.PdfFileMerger'>
>>>`

**Comment by KrisLloyd** [comment]
Not a "proper" fix for your problem, but you can clone the PyPDF2 github repo into your working directory for whichever python script you're working on, then do an import.

In your project directory:
<Project Directory>
    yourScript.py
    PyPDF2
        pdf.py
        ...
 
In yourScript.py:
`import PyPDF2.pdf
from PyPDF2.pdf import PdfFileReader`

If you have things organized like this, it should work perfectly.

**Comment by jriley-asm** [comment]
I think this is still broken

**Comment by MartinThoma** [comment]
Hm, I wonder if it is related to PyPDF2 using distutils?

**Comment by MartinThoma** [comment]
I just installed PyPDF2 on a mac via pip. Works fine.

**Comment by Atharva-Weginwar** [comment]
I am getting the same issue on Mac OS. I have tried installing PyPDF2 using pip and pip3 both its showing requirements are satisfied still when i am trying to run the app.py via streamlit, It throws the error " Model not found: PyPDF2"

**Comment by pubpub-zz** [comment]
pypdf2 is deprecated, replaced by pypdf.

**Comment by Atharva-Weginwar** [comment]
Is there any other pip command to install pypdf as pip install pypdf is not working at my end.

**Comment by pubpub-zz** [comment]
pypdf is available on pypi.org so you should not meet an issue to install it if your python/network configuration is correct. as an alternative you should download manually the whl file from https://pypi.org/project/pypdf/#files and then pass the whl file as argument after pip install
