### ISSUE TITLE
PdfReadError: Illegal character in Name Object

### ISSUE THREAD

**Issue by JamieJang** [py-pdf/PyPDF2#457]
I have tried merge 2 pdf.
These pdf written by Korean or Chinese, so I call them by PdfFileReader with strict=False options.

But when I try merge two pdf, <PdfReadError: Illegal character in Name Object> error is raised.

```python
input_file = PdfFileReader(open(pdfPath,"rb"),strict=False)
size = input_file.getPage(0).mediaBox
page_cnt = input_file.getNumPages()
output_file = PdfFileWriter()
can = canvas.Canvas("coord.pdf")

...(make canvas)

can.save()
stamp = PdfFileReader(open("coord.pdf","rb"),strict=False)

input_page.mergePage(stamp.getPage(0))

...

with open(outputPath, 'wb') as outputStream:
            output_file.write(outputStream)     <---- raise error here
```

**Comment by mati1994** [comment]
have you solved this problem?

**Comment by MartinThoma** [comment]
As this issue has neither a traceback nor an example PDF and the code is not complete (e.g. it's missing imports), I cannot reproduce the issue.

As PyPDF2 has changed a lot, I assume the issue was resolved. If you still get the issue with a recent version of PyPDF2, please let me know.
