### ISSUE TITLE
Why does PdfFileWriter forget changes I made to a document?

### ISSUE THREAD

**Issue by solarjoe** [py-pdf/PyPDF2#459]
I am trying to modify text in a PDF file. The text can be in an object of type `Tj` or `BDC`. I find the correct objects and if I read them directly after changing them they show the updated values.

But if I pass the complete page to PdfFileWriter the change is lost. I might be updating a copy and not the real object. I checked the `id()` and it was different. Does someone have an idea how to fix this?

`content = ContentStream(content_object, source)` does not seem to be the problem. I run that twice and content has the same `id()`. But when I loop over content.operations the ìd of `operands` and `operator` are different.

Any idea how to fix this?

```python
from PyPDF2 import PdfFileReader, PdfFileWriter
from PyPDF2.pdf import ContentStream
from PyPDF2.generic import TextStringObject, NameObject
from PyPDF2.utils import b_

source = PdfFileReader(open('some.pdf', "rb"))
output = PdfFileWriter()

for page_idx in range(0, 1):

    # Get the current page and it's contents
    page = source.getPage(page_idx)

    content_object = page["/Contents"].getObject()
    content = ContentStream(content_object, source)

    for operands, operator in content.operations:

        if operator == b_("BDC"):

            operands[1][NameObject('/Contents')] = TextStringObject('xyz')

        if operator == b_("Tj"):

            operands[0] = TextStringObject('xyz')

    output.addPage(page)


# Write the stream
outputStream = open("output.pdf", "wb")
output.write(outputStream)
outputStream.close()
```

Discussion [on stackoverflow](https://stackoverflow.com/questions/52499339/pypdf2-why-does-pdffilewriter-forget-changes-i-made-to-a-document)

**Comment by MartinThoma** [comment]
It seems like this issue was solved - thanks for sharing the answer on Stackoverflow! https://stackoverflow.com/a/52587747/562769
