### ISSUE TITLE
*TypeError: 'NoneType' object is not subscriptable* When Adding Scaled Page

### ISSUE THREAD

**Issue by HexerTPB** [py-pdf/PyPDF2#460]
I have this script to take samplepdf.pdf and shrink every page down by 0.5:
```python
from PyPDF2 import PdfFileWriter, PdfFileReader

output = PdfFileWriter()
input1 = PdfFileReader(open("samplepdf.pdf", "rb"))

for x in range(input1.getNumPages()):
	output.addPage(input1.getPage(x).scaleBy(0.5))
	
outputStream = open("samplepdf-output.pdf", "wb")
output.write(outputStream)
```

And I get this error:
```
Traceback (most recent call last):
  File "pdf.py", line 7, in <module>
    output.addPage(input1.getPage(x).scaleBy(0.5))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyPDF2\pdf.py", line 138, in addPage
    self._addPage(page, list.append)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyPDF2\pdf.py", line 123, in _addPage
    assert page["/Type"] == "/Page"
TypeError: 'NoneType' object is not subscriptable
```

Heres the [pdf file I used](http://www.africau.edu/images/default/sample.pdf)

**Comment by himanshudabas** [comment]
Instead of using this
> ```python
> for x in range(input1.getNumPages()):
>     output.addPage(input1.getPage(x).scaleBy(0.5))
> ```
use the following :
```python
for x in range(input1.getNumPages()):
    input_page = input1.getPage(x)
    input_page.scaleBy(0.5)
    output.addPage(input_page)
```
I think this happens because `scaleBy` function is 'in place', I faced the same issue with `mergePage` function.

**Comment by MartinThoma** [comment]
@himanshudabas is absolutely right.

However, I think keeping it in-place and returning `self` might be valuable to allow method chaining. Let's discuss this here: https://github.com/py-pdf/PyPDF2/discussions/786
