### ISSUE TITLE
[_showwarning]: in cx_Freeze environment stderr is None

### ISSUE THREAD

**Issue by spSerg** [py-pdf/PyPDF2#461]
https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/pdf.py#L1133

When I use PuPDF2 with cx_Freeze, any encounter error will stop PDF operation.

Please, Insert additional check for None file in _showwarning replacement:
```python
            def _showwarning(message, category, filename, lineno, file=warndest, line=None):
                if file is None:
                    file = sys.stderr
                try:
                    if file is not None: #Add This check
                        file.write(formatWarning(message, category, filename, lineno, line))
                except IOError:
                    pass
```

**Comment by MartinThoma** [comment]
Thank you for reporting a problem! 

The warnings manipulation is no longer part of PyPDF2. So this issue should no longer exist.
