### ISSUE TITLE
extractText number problem

### ISSUE THREAD

**Issue by JodeZer** [py-pdf/PyPDF2#466]
![image](https://user-images.githubusercontent.com/9582429/48066342-47fa4580-e208-11e8-885b-da38012c3402.png)
![image](https://user-images.githubusercontent.com/9582429/48066388-66604100-e208-11e8-9afe-0c243c402b4a.png)

When l extractText from this page, the number on 1 line just combined together.

This is because:
https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/pdf.py#L2685-L2686

l thought in this source code, that line can add a "\n" remark also.

So do you mind me open a pr to solve this?

**Comment by MartinThoma** [comment]
This was done in multiple PRs, including https://github.com/py-pdf/PyPDF2/pull/334
