### ISSUE TITLE
(optionally) Splitting text blocks using <space> would make this more useable

### ISSUE THREAD

**Issue by papadeltasierra** [py-pdf/PyPDF2#487]
I've been investigating using your package to extract some data from PDF files (the data happens to be in a table in case that matters) but I often get output like this:
`12345678901234.567.8900`
The data is actually a number of distinct values:
`123 456 7890 123 4.5 67.89 00`
With no way to know the where the breaks should be, the output is unusable.  But if you optionally added a space where there is no existing/natural whitespace between the values (or blocks of text), they would be separated and the usable.
So perhaps you could add an option to extractText() to do this?

**Comment by MartinThoma** [comment]
Was done in the last release :-)
