### ISSUE TITLE
Python 3 doesn't support negative seeks

### ISSUE THREAD

**Issue by webisteme** [py-pdf/PyPDF2#489]
When opening a pdf file in Python 3.7 I get the following error:
```
>> PdfFileReader(open('/file.pdf'))
>> UnsupportedOperation: can't do nonzero end-relative seeks
```
The reason is Python 3 no longer supports negative seeks. To fix the issue I had to set the mode to 'rb':
```
>> PdfFileReader(open('/file.pdf', mode="rb"))
```
This may be worth noting in the documentation.

**Comment by Dakotapa** [comment]
Thank you! This worked

**Comment by snehal1989** [comment]
thanks this worked

**Comment by basawanayya** [comment]
**Thanks**

**Comment by SherifBassiouni** [comment]
Hello,
I can't read a PDF that is in Arabic. 
file = PyPDF2.PdfFileReader(open('P07.pdf',mode='rb', encoding="UTF-8"))
I get the following message: binary mode doesn't take an encoding argument
Do you have any idea how to fix this?
Thanks :)

**Comment by basawanayya** [comment]
sorry, i don't know

**Comment by gothill** [comment]
@SherifBassiouni You're opening a file in bytes mode, which assumes the file you are opening is bytes, i.e. _not encoded_, so try removing the encoding argument.

**Comment by SherifBassiouni** [comment]
> @SherifBassiouni You're opening a file in binary mode, which assumes the file you are opening is in bytes, i.e. _not encoded_, so try removing the encoding argument.

Thanks for your reply. 
I tried your suggestion and got the following error:
UnsupportedOperation: can't do nonzero end-relative seeks

**Comment by faisalaltqiqi** [comment]
> Hello,
> I can't read a PDF that is in Arabic.
> file = PyPDF2.PdfFileReader(open('P07.pdf',mode='rb', encoding="UTF-8"))
> I get the following message: binary mode doesn't take an encoding argument
> Do you have any idea how to fix this?
> Thanks :)

Dear 
I have the same problem
Did you come up with a solution?

**Comment by faisalaltqiqi** [comment]
> Hello,
> I can't read a PDF that is in Arabic.
> file = PyPDF2.PdfFileReader(open('P07.pdf',mode='rb', encoding="UTF-8"))
> I get the following message: binary mode doesn't take an encoding argument
> Do you have any idea how to fix this?
> Thanks :)

Dear 
I have the same problem
Did you come up with a solution?

**Comment by SherifBassiouni** [comment]
Hello Faisal, 

**There is another Python library called (fitz) that allows you to extract text from PDF files. 
here is the code:**
>>import fitz
>>doc = fitz.open("your_file.pdf")
>>txt = doc.getPageText(0)
>>txt

The only problem is that it prints the words in reverse order. for example, if you PDF file has the word "فيصل" in it, it will be printed as "لصيف".

**to get around this problem you can add the following code:**

>>txt2 = txt.split(" ")
>>for word in txt2:
    >>print(word)

Good luck

**Comment by SherifBassiouni** [comment]
> > Hello,
> > I can't read a PDF that is in Arabic.
> > file = PyPDF2.PdfFileReader(open('P07.pdf',mode='rb', encoding="UTF-8"))
> > I get the following message: binary mode doesn't take an encoding argument
> > Do you have any idea how to fix this?
> > Thanks :)
> 
> Dear
> I have the same problem
> Did you come up with a solution?



 Hello Faisal,

**There is another Python library called (fitz) that allows you to extract text from PDF files.
here is the code:**

>>import fitz
>>doc = fitz.open("your_file.pdf")
>>txt = doc.getPageText(0)
>>txt

The only problem is that it prints the words in reverse order. for example, if your PDF file has the word "فيصل" in it, it will be printed as "لصيف".

**to get around this problem you can add the following code:**

>>txt2 = txt.split(" ")
>>for word in txt2:
>>print(word)

Good luck

**Comment by faisalaltqiqi** [comment]
packet = io.BytesIO()
text=("12345فيصل")
can = canvas.Canvas(packet, pagesize=letter )
can.drawString(250, 603, text)
can.save()


packet.seek(0)
new_pdf = PdfFileReader(packet)
#(open('P07.pdf',mode='rb', encoding="UTF-8"))
with   open("test.pdf",mode='rd',encoding='utf-8') as op:


output = PdfFileWriter()

page = existing_pdf.getPage(0)
page2 = new_pdf.getPage(0)
page.mergePage(page2)
output.addPage(page)

with open("New.pdf" ,'wb',encoding='utf-8') as out:
     output.write(out)

#outputStream = open("New.pdf" , "wb")
     #output.write(outputStream)
     out.close()

‫في الأربعاء، 29 أبريل 2020 في 11:27 م تمت كتابة ما يلي بواسطة ‪Sherif
Bassiouni‬‏ <‪notifications@github.com‬‏>:‬

**Comment by faisalaltqiqi** [comment]
> > > Hello,
> > > I can't read a PDF that is in Arabic.
> > > file = PyPDF2.PdfFileReader(open('P07.pdf',mode='rb', encoding="UTF-8"))
> > > I get the following message: binary mode doesn't take an encoding argument
> > > Do you have any idea how to fix this?
> > > Thanks :)
> > 
> > 
> > Dear
> > I have the same problem
> > Did you come up with a solution?
> 
> Hello Faisal,
> 
> **There is another Python library called (fitz) that allows you to extract text from PDF files. here is the code:**
> 
> > > import fitz
> > > doc = fitz.open("your_file.pdf")
> > > txt = doc.getPageText(0)
> > > txt
> 
> The only problem is that it prints the words in reverse order. for example, if your PDF file has the word "فيصل" in it, it will be printed as "لصيف".
> 
> **to get around this problem you can add the following code:**
> 
> > > txt2 = txt.split(" ")
> > > for word in txt2:
> > > print(word)
> 
> Good luck

Can you contact me?
(faisalsrpg@gmail.com)

**Comment by nduprincekc** [comment]
**```
PdfFileReader(open('/file.pdf', mode="rb"))

This is the correct debug
```**

> When opening a pdf file in Python 3.7 I get the following error:
> 
> ```
> >> PdfFileReader(open('/file.pdf'))
> >> UnsupportedOperation: can't do nonzero end-relative seeks
> ```
> 
> The reason is Python 3 no longer supports negative seeks. To fix the issue I had to set the mode to 'rb':
> 
> ```
> >> PdfFileReader(open('/file.pdf', mode="rb"))
> ```
> 
> This may be worth noting in the documentation.

PdfFileReader(open('/file.pdf', mode="rb"))

**Comment by MartinThoma** [comment]
Do you have a file that leads to this bug?

**Comment by MartinThoma** [comment]
I think this is just a wrong usage of PyPDF2.

## Wrong

```python
reader = PdfFileReader(open("example.pdf"))
``

## Correct - Option 1

```python
reader = PdfFileReader("example.pdf")
```

## Correct - Option 2

```python
fh = open("example.pdf", "rb")   # mind the "rb"!
reader = PdfFileReader(fh)
# do your stuff
fh.close()
```
