### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EvanMata** [py-pdf/PyPDF2#496]
Is there a license type that PyPDF2 is licensed under? Examples: MIT license, GNU License, BSD 3 etc. As an example:
https://github.com/pandas-dev/pandas/blob/master/LICENSE
You do have a license statement, but they specify a BSD 3 License, which lets me (or others) know how we can use that software. I'm interested in using pypdf2 to process pdfs as part of a much larger commercial product, but without a license type I cannot figure out whether pypdf2 would be allowed for those purposes (and hence might use other software).  
Unsure if this is the appropriate page to post this as well.

**Comment by kurtmckee** [comment]
PyPDF2 is licensed under a BSD 3-clause license.

**Comment by guysoft** [comment]
That is not what the LICENSE says:
https://github.com/mstamy2/PyPDF2/blob/master/LICENSE

**Comment by guysoft** [comment]
LICENSE:
https://github.com/mstamy2/PyPDF2/blob/mastaer/LICENSE
BSD 3-clause license:
https://opensource.org/licenses/BSD-3-Clause

This issue can be closed
