### ISSUE TITLE
Getting KeyError: '/Kids' for getNumPages

### ISSUE THREAD

**Issue by bikashgupta11** [py-pdf/PyPDF2#500]
For a specific PDF, its giving error **KeyError: '/Kids'**

## Code

```python
from PyPDF2 import PdfFileReader

reader = PdfFileReader("example.pdf")
reader.getNumPages()
```

## Traceback

> Stacktrace
pageNum = src_pdf.getNumPages()
  File "C:\Miniconda3\envs\1\lib\site-packages\PyPDF2\pdf.py", line 1155, in getNumPages
    self._flatten()
  File "C:\Miniconda3\envs\1\lib\site-packages\PyPDF2\pdf.py", line 1520, in _flatten
    self._flatten(page.getObject(), inherit, **addt)
  File "C:\Miniconda3\envs\1\lib\site-packages\PyPDF2\pdf.py", line 1516, in _flatten
    for page in pages["/Kids"]:
  File "C:\Miniconda3\envs\1\lib\site-packages\PyPDF2\generic.py", line 516, in __getitem__
    return dict.__getitem__(self, key).getObject()
KeyError: '/Kids'

Document Info

![image](https://user-images.githubusercontent.com/4414427/56783223-477e5700-6808-11e9-9410-d95b571c5330.png)

**Comment by bikashgupta11** [comment]
Analysis:-
IndirectObject of Kids has type "Pages" not "Page". Hence its recursively trying to flatten Pages however its not getting the Kids attribute. Also as it does not have "Page" object hence flattenPages length is not appended.

Now the PDF Version is 1.0(Acrobat 1.x). If I save the same PDF with different name then its version its getting change and its working.

![image](https://user-images.githubusercontent.com/4414427/56960190-a4ae3b80-6b6d-11e9-9ce8-37ee1ba62d9e.png)

![image](https://user-images.githubusercontent.com/4414427/56960218-b55eb180-6b6d-11e9-8d32-78eff7fcbfbe.png)

**Comment by MartinThoma** [comment]
I realize it's been a long time, but ... Do you happen to have the PDF that causes / caused those issues? Could you share it?

**Comment by Ontheroad123** [comment]
> As too much has changed since this was last encountered and there is no example PDF, I'll close this.
> 
> If anybody sees this issue again with a recent PyPDF2 version, please let me know!

I have meet 'KeyError: '/Kids'' error,  PyPDF2=='3.0.1',
[Taylor’s Differential Diagnosis Manual_ Symptoms and Signs in the Time-Limited Encounter.pdf](https://github.com/py-pdf/pypdf/files/11503757/Taylor.s.Differential.Diagnosis.Manual_.Symptoms.and.Signs.in.the.Time-Limited.Encounter.pdf)

**Comment by pubpub-zz** [comment]
The PDF is not compliant with the Standard : **/Type** field is missing on the Pages Nodes and on the Page Objects. However the document can be opened by Acrobat Reader. Page objects are now considered also if **/Contents** is present (although not or if **/Kids** is not present

**Comment by MartinThoma** [comment]
I've just merged the fix by @pubpub-zz (thank you again :hugs: )

The fix will be part of pypdf > 3.8.1.

**Comment by pachhaipurna** [comment]
@MartinThoma  I am having this /Kids Type error in my pdf file, I tried to create a new pdf file based on Page number after updating some attributes, If I create individually it is working fine. But When I tried to combine multiple page at once, the Attributes are not updating.

**Comment by pubpub-zz** [comment]
@pachhaipurna 
Please create a new issue with all data (version, code +pdf, error reported )
Like this we can not analyse the issue
