### ISSUE TITLE
Unbound & undocumented instance methods in pdf.py (getRectangle, setRectangle, deleteRectangle, createRectangleAccessor)

### ISSUE THREAD

**Issue by vinay-deshmukh** [py-pdf/PyPDF2#517]
I was reading the source code of  PdfFileReader class [PyPDF2/pdf.py](https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/pdf.py)
and have found some methods which look like they were meant to be defined within a class, since they take `self` as a parameter. I initially thought they were somehow accidentally unindented from the PdfFileReader class, but on further searching, I found that these methods aren't even documented on the [documentation site](https://pythonhosted.org/PyPDF2/).

Given below, are permalinks to the offending functions.

https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/pdf.py#L2119

https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/pdf.py#L2135

https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/pdf.py#L2141

https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/pdf.py#L2145

Maybe these methods were to be removed, and weren't. 

Anyways, I thought to make an issue since this doesn't seem an intentional feature.

**Comment by MartinThoma** [comment]
Thank you - I will keep that in mind for PyPDF2 2.0 : https://github.com/py-pdf/PyPDF2/discussions/752

**Comment by MartinThoma** [comment]
They are used for `createRectangleAccessor` of the `Page` object. We have four types of rectangles:

* CropBox
* BleedBox
* TrimBox
* ArtBox

Those methods should be private (have a leading `_`, hence `_getRectangle`, `_setRectangle`, ...). But the fact that the first argument is called `self` is fine.
