### ISSUE TITLE
Encryption uses outdated RC4 - Upgrade to AES?

### ISSUE THREAD

**Issue by cristianocca** [py-pdf/PyPDF2#528]
Looks like PyPDF2 is still using RC4 to encrypt PDF files. Would it be possible to upgrade to AES ? RC4 is totally broken.

Is there any reason it hasn't been implemented yet?

Source: https://www.pdflib.com/pdf-knowledge-base/pdf-password-security/encryption/

**Comment by cristianocca** [comment]
Bump, any news? Any alternative PDF library?

**Comment by xilopaint** [comment]
Any news here? I have security alerts on this:

https://github.com/xilopaint/alfred-pdf-tools/security/code-scanning/1

https://github.com/xilopaint/alfred-pdf-tools/security/code-scanning/2

**Comment by MartinThoma** [comment]
@xilopaint I guess both pages are private?

![image](https://user-images.githubusercontent.com/1658117/173499847-97aedf29-d85a-416c-a5e5-a3e84e99b1a9.png)

**Comment by MartinThoma** [comment]
PyPDF2==2.3.0 will be about #749 :-)

**Comment by xilopaint** [comment]
> @xilopaint I guess both pages are private?

Oh, I guess there's no way to make it public. You can read the issue description here with a recomendation:

https://codeql.github.com/codeql-query-help/python/py-weak-sensitive-data-hashing/

**Comment by MartinThoma** [comment]
On which lines do you have the security alerts? I wonder if your alerts are actually about PyPDF2 as I doubt an automatic scanner would recognize that.

Could it be that you use md5 in those lines?

**Comment by MartinThoma** [comment]
This is a false-positive of the tool. That md5 will never go away because it's part of the PDF specifications. That is just how this (outdated, but potentially still used) algorithm works. Removing it would mean removing the possibility to decrypt those PDFs.

**Comment by MartinThoma** [comment]
Those lines will never go away. The security alerts are wrong.
