### ISSUE TITLE
Eliminating a bookmark influences the topology of preceeding bookmarks

### ISSUE THREAD

**Issue by strickon** [py-pdf/PyPDF2#531]
So if you try to add a bunch of book marks as     

A
-B
--C
D

it works

But if you eliminate D, you end up with
B
-C

It appears that if your top level bookmarks are only a single bookmark, it removes that top level.

My work around was to create a single dummy bookmark at the root level and then add everything to that.

```python
   output = PdfFileWriter()
    p="input.pdf"
    pdf = PdfFileReader(open(p, 'rb'))
    output.appendPagesFromReader(pdf)
    bookmarkA = output.addBookmark("A", 0)
    bookmarkB = output.addBookmark("B", 0, bookmarkA)
    bookmarkC = output.addBookmark("C", 0, bookmarkB)
    bookmarkD = output.addBookmark("D", 0) #comment this line to see the error
    pdfOutput = open('test.pdf', 'wb')
    output.write(pdfOutput)
```

**Comment by pubpub-zz** [comment]
I've just did the test using issue_604.pdf without issue:

```
import PyPDF2
r=PyPDF2.PdfFileReader("resources/issue-604.pdf")
w=PyPDF2.PdfFileWriter()
w.appendPagesFromReader(r)
ba = w.addBookmark("A", 0);
bb = w.addBookmark("B", 0,ba)
bc = w.addBookmark("C", 0,ba)
bd = w.addBookmark("D",0)
w.write(open('tstwith.pdf','wb'))
w=PyPDF2.PdfFileWriter()
w.appendPagesFromReader(r)
ba = w.addBookmark("A", 0);
bb = w.addBookmark("B", 0,ba)
bc = w.addBookmark("C", 0,ba)
#bd = w.addBookmark("D",0)
w.write(open('tstwithout.pdf','wb'))
```

@strickon, can you confirm you still have the issue with the latest version ? if it may be linked with the input pdf, can you provide it

**Comment by MartinThoma** [comment]
Looks fine to me as well:

![image](https://user-images.githubusercontent.com/1658117/178109584-1fa933f9-7a4d-4861-8240-186fa42d25b7.png)

I'll close this issue now as the problem seems to be solved. Please let me know if you still encounter this problem with the latest PyPDF2 version.
