### ISSUE TITLE
PyPDF2 can't read French Accented Characters (œ)

### ISSUE THREAD

**Issue by hamzaAmier** [py-pdf/PyPDF2#532]
hello,
I'm working for text mining project using PyPDF2 and i'm facing problem to extract this character "œ" (it's french character)  . the method "extract Text ()" of a page object can't detect it at all.

Thank you for your help.

**Comment by MartinThoma** [comment]
I think #464 might solve this

**Comment by MartinThoma** [comment]
Duplicates #524
