### ISSUE TITLE
Bitmap PNGs are not decoded

### ISSUE THREAD

**Issue by chrisegner** [py-pdf/PyPDF2#535]
The current implementation of FlateDecode.decode assumes the PNG is encoded with `BitsPerComponent == 8`.  This is not valid for bitmap PNGs.  In this case, each row is still prefixed with the filter byte then followed by the bits, padded out to the final byte.

Pull request coming shortly.

**Comment by jansindl3r** [comment]
it is so dead here, nobody merges. Does anyone know about an active fork? :(

**Comment by zoj613** [comment]
> it is so dead here, nobody merges. Does anyone know about an active fork? :(
https://github.com/claird/PyPDF4

**Comment by MartinThoma** [comment]
@jansindl3r @zoj613 I just became the maintainer of PyPDF2 this month - and we did merge quite a lot! Things are moving in the right direction, but it will take time to clean up things. Be a bit more patient :pray: 

I don't think PyPDF4 is the way to go. It doesn't have enough community support. Now that I clean things up in PyPDF2, I guess it will outpace PyPDF4 quickly (if it hasn't already; you have to judge)

**Comment by zoj613** [comment]
@MartinThoma thanks a lot for the effort. This is great to hear. I would be happy to contribute where I can, though I must say I know very little about the structure of pdf files.

**Comment by MartinThoma** [comment]
Does anybody have a PDF + Python code that shows the issue described here?

**Comment by MartinThoma** [comment]
Sorry for the long wait - the support for BitsPerComponent was added, along with the support of indexed color spaces :tada: 

I will probably release `PyPDF==2.5.0` on Sunday (10.07.2022).

Thanks to everybody :heart:

**Comment by zoj613** [comment]
Thank you for the hard work @MartinThoma
