### ISSUE TITLE
pageObj.extractText()  does not work

### ISSUE THREAD

**Issue by gus999** [py-pdf/PyPDF2#543]
Hi there, I am trying to use PyPDF2 but pageObj.extractText()  cannot be called . Please advise on this matter

```pycon
 >>> import PyPDF2 (works)
   >>> pdfFileObj = open('meetingminutes.pdf', 'rb') (works)
   >>> pdfReader = PyPDF2.PdfFileReader(pdfFileObj) (works)
>>> print ('pdfReader.numPages) (works)
   19
 >>> pageObj = pdfReader.getPage(0) (works)
 >>> pageObj.extractText() (doesn't work)
```

**Comment by bmaca** [comment]
@gus999 Are you seeing any errors?

**Comment by gus999** [comment]
Hi, 

get the following error:
NameError: name 'pdfReader' is not defined

also, VSC intellisense does not recognize it either.

**Comment by HirsuteJim** [comment]
What is the PDF format version of the PDF file you are working with? (1.4, 1.5, 1.7, 2.0???)

**Comment by gus999** [comment]
Hi Jim, 

It's a 1.6 version. Also, I tried with 1.4v with same result. Does PyPDF2 work only with a particular version?

**Comment by hbaqueiro** [comment]
I had this strange behavior as well and I've seen a lot of people complaining about this. At first, I expected that it was a problem in my code, but when I tried with the provided pdf files in this repository, it worked like a charm. Here is my code:
```
from PyPDF2 import PdfFileReader

input_pdf = PdfFileReader(open("SF424_page2.pdf", "rb"))
thispage = input_pdf.getPage(0)
print(thispage.extractText())
```
**Important**: this seems no happen only with version **1.4** (and maybe 1.6... I had no example here to test). I've tested up to four documents in each version and here are my results:
```
version   Document1     Document2        Document3     Document4
1.7         works
1.5         works         works
1.4         empty     works (nospace)      empty         empty
1.3         works         works
```
Just one 1.4 document worked but `nospacebetweenwords`. @HirsuteJim @bmaca I hope this helps. Empty means a certain number of "\n" (not shown in print), which may vary.

**Comment by drecryptos** [comment]
> Hi there, I am trying to use PyPDF2 but pageObj.extractText() cannot be called . Please advise on this matter
> 
> > > > import PyPDF2 (works)
> > > > pdfFileObj = open('meetingminutes.pdf', 'rb') (works)
> > > > pdfReader = PyPDF2.PdfFileReader(pdfFileObj) (works)
> > > > print ('pdfReader.numPages) (works)
> > > > 19
> > > > pageObj = pdfReader.getPage(0) (works)
> > > > pageObj.extractText() (doesn't work)

print(pageObj.extractText())

**Comment by ramacpr** [comment]
Is there a resolution for this issue? I too see similar issues. The result of extractText() of pypdf2 is different for different versions of .pdf and for different .pdf files.

**Comment by MartinThoma** [comment]
@ramacpr @drecryptos @hbaqueiro @gus999 PyPDF2 recently improved text textraction capabilities quite a lot. I guess that the issue was solved. For this reason I will close it.

If you feel that this is still a problem, please add a Traceback and/or (preferably and) a PDF that causes the issue.
