### ISSUE TITLE
.extractText() sees hyphen / dash ( - ) as a line break

### ISSUE THREAD

**Issue by ha1f3mpty** [py-pdf/PyPDF2#544]
I have been seeing that .extractText() starts a new line when it sees the hyphen/dash ( - ) character.

This is how the text looks in a PDF reader
`The enslavement of the small, power-enhancing Mini-Cons has long been a major goal of the Decepticons, and the Mini-Cons are seen`

This is how the text looks after running through .extractText()
```
The enslavement of the small, power
-
enhancing Mini
-
Cons has long been a major goal of the 
Decepticons, and the Mini
-
Cons are seen
```

Am I missing some argument that needs to be passed along so this behavior doesn't occur or was this functionality put in to catch hyphenated words that line wrap? If the latter, is there a way to disable that?

Thanks in advance

**Comment by MartinThoma** [comment]
@ha1f3mpty Do you have an example PDF that shows this behavior?

**Comment by MartinThoma** [comment]
Without an example PDF, this will be too hard to work on. For this reason I'll close it.

If anybody can share an example, I can reopen the issue :-)
