### ISSUE TITLE
Hello, 

### ISSUE THREAD

**Issue by faisalaltqiqi** [py-pdf/PyPDF2#548]
Hello,
I can't read a PDF that is in Arabic. 
file = PyPDF2.PdfFileReader(open('P07.pdf',mode='rb', encoding="UTF-8"))
I get the following message: binary mode doesn't take an encoding argument
Do you have any idea how to fix this?
Thanks :)

_Originally posted by @SherifBassiouni in https://github.com/mstamy2/PyPDF2/issues/489#issuecomment-619627375_

Dear 
I have the same problem
Did you come up with a solution?

**Comment by Bomberus** [comment]
Hi, this is not a pypdf2 issue. 
It makes no sense to specify encoding when you are reading the files in binary mode. Because they are already in binary form.

Why not read the file directly? 
```python
with open('P07.pdf',mode='rb') as file:
  pdf= PyPDF2.PdfFileReader(file.read()) 
```
