### ISSUE TITLE
Could not parse papers in IEEE and NeurIPS format

### ISSUE THREAD

**Issue by icmpnorequest** [py-pdf/PyPDF2#553]
Hi team,

I tried to parse papers in IEEE and NeurIPS formats to rename the paper, but return None. Any ideas to solve? Thanks in advance.

**Comment by MartinThoma** [comment]
Do you maybe have example PDFs which we are allowed to add to our testing resources?

**Comment by MartinThoma** [comment]
Or at least a direct link to one PDF that causes issues + example code?

**Comment by MartinThoma** [comment]
https://www.amity.edu/aiit/icrito2018/ieee-format.pdf seems to work fine

**Comment by MartinThoma** [comment]
https://papers.nips.cc/paper/2020/file/38a8e18d75e95ca619af8df0da1417f2-Paper.pdf seems to work fine as well.
