### ISSUE TITLE
PdfFileWriter object has no attribute stream

### ISSUE THREAD

**Issue by boskowski** [py-pdf/PyPDF2#555]
As described [here](https://stackoverflow.com/questions/40168027/pypdf2-pdffilewriter-has-no-attribute-stream), there's a bug in PyPDF2 that - in my case - appear sometimes when repeatedly writing extracted page objects to different io.BytesIO streams.

This can be fixed with
```
--- PyPDF2/pdf.py	
+++ PyPDF2/pdf.py
@@ -572,7 +527,7 @@
                     self._sweepIndirectReferences(externMap, realdata)
                     return data
             else:
-                if data.pdf.stream.closed:
+                if hasattr(data.pdf, 'stream') and data.pdf.stream.closed:
                     raise ValueError("I/O operation on closed file: {}".format(data.pdf.stream.name))
                 newobj = externMap.get(data.pdf, {}).get(data.generation, {}).get(data.idnum, None)
                 if newobj == None:
```

**Comment by MartinThoma** [comment]
Thank you for your contribution!

I wish I had seen it earlier ... but in the end I came up with the same solution: https://github.com/py-pdf/PyPDF2/issues/670
