### ISSUE TITLE
readFromStream(stream, pdf) receives NONE and pdf.strict fails

### ISSUE THREAD

**Issue by emelenas** [py-pdf/PyPDF2#563]
As stated in the title, pdf.strict in readFromStream (at line 582 in generic.py) raises an AttributeError because the parameter pdf as received is None.

Going back, this comes from ContentStream.__parseContentStream at file pdf.py line 2706 though the call operands.append(readObject(stream, None)). readObject in turn calls DictionaryObject.readFromStream at line 66 of generic.py

Thus, it is an explicit call with None as an argument that causes the exception. The starting call with None is done at an else clause after some checks on the stream, so maybe there is a missing check.

Anyhow if None is to be passed as argument pdf, I believe a check should be in order down the line to avoid exceptions.

I changed the call to

operands.append(readObject(stream, **self.pdf**)) 

and apparently no harm is done (aside from avoiding the exception).

**Comment by MartinThoma** [comment]
Can you share a minimal complete example (including the code you've written + the PDF file you've used)?

**Comment by MartinThoma** [comment]
It seems like this part no longer exists. Maybe it was solved with #924 .
