### ISSUE TITLE
PdfReadWarning: Superfluous whitespace found in object header b'1' b'0' [pdf.py:1666]

### ISSUE THREAD

**Issue by kalkovid19** [py-pdf/PyPDF2#576]
Hi  all,
I coverting pdf file to text for processing. code was workig fine an drecently it started giving errors like below and not text extraction
PdfReadWarning: Superfluous whitespace found in object header b'1' b'0' [pdf.py:1666]

## MCVE

```python
from PyPDF2 import PdfReader

reader = PdfReader("TN_24.08.2020.pdf")
text = reader.pages[0].extract_text()
assert "Directorate" in text, text
```

my pdf file and process code are attached
[pdf2txt.py.txt](https://github.com/mstamy2/PyPDF2/files/5119008/pdf2txt.py.txt)
[TN_24.08.2020.pdf](https://github.com/mstamy2/PyPDF2/files/5119011/TN_24.08.2020.pdf)

Thanks in advance

**Comment by luke4u** [comment]
got the same issue. Can any please advise how to resolve it?

**Comment by Grazx** [comment]
Well I had the same problem, since I was trying to stamp a template PDF (made by me), on an existing one. 
The solution:
I use Foxit Phatom converted my file from PDF_1.4 to PDF_1.7 and the error "PdfReadWarning:" stopped showing.

Hope it helps.

**Comment by lmw0320** [comment]
> 



> Well I had the same problem, since I was trying to stamp a template PDF (made by me), on an existing one. The solution: I used Foxit Phatom to convert my Template file from PDF_1.4 to PDF_1.7 and the error "PdfReadWarning:" stopped showing.
> 
> Hope it helps.
> 
> EDIT: I forgot to mention I also use the "PDF Optimizer" option in Phantom to "flatten" text and objects (more on that in https://www.foxitsoftware.com/blog/pdf-toolkit-pdf-optimizer/)

Hi, for I have plenty of pdffiles, I want to find out all the content in pdffiles, but your solution can not be used as normal operation. Do you have any better code solution instead of treating the file be hand. Thanks

**Comment by MartinThoma** [comment]
Could somebody add a minimal Python script that shows the issue with the given files?

**Comment by JGMSPY** [comment]
Here is the code that gave me the subjected problem. I more or less randomly added a pdf file with 4 pages. I also got the error when using a single-paged PDF-file, and where the resulting file was OK.

from PyPDF2 import PdfFileReader, PdfFileWriter,PdfFileMerger

template = PdfFileReader(open('C:\APPS\PythonHelp.pdf','rb'))
watermark = PdfFileReader(open("C:\APPS\FactuurModelIkke.pdf", 'rb'))
output = PdfFileWriter()

for i in range(template.getNumPages()):
   page = template.getPage(i)
   page.mergePage(watermark.getPage(0))
   output.addPage(page)
file = open('C:\APPS\DeZZPer\Verzonden_Facturen\waterMarked_PDF.pdf', 'wb')
output.write(file)

[FactuurModelIkke.pdf](https://github.com/py-pdf/PyPDF2/files/8497174/FactuurModelIkke.pdf)
[PythonHelp.pdf](https://github.com/py-pdf/PyPDF2/files/8497170/PythonHelp.pdf)

Hope you can solve this.

**Comment by Rapid1898-code** [comment]
Hello - i have the same problem.
When anybody find a solution for that - this would be great.

**Comment by MartinThoma** [comment]
@Rapid1898-code "me too" comments don't provide any value. They distract and prevent devs from working on the issue.

If you want to help, please provide a full minimal example:

* code
* pdf
* traceback
* environment (python version, py-pdf version)

**Comment by prz38573485** [comment]
I met the same issue. 
`PdfReadWarning: Superfluous whitespace found in object header b'225' b'0' [_reader.py:891]`

**Comment by JGMSPY** [comment]
All,
With great help from samples I managed to get the routine working without problems. This was my first Python experience and I learned a lot. Thanks you.

**Comment by MartinThoma** [comment]
I just checked with the current `main` branch and the minimal example from the first post - the issue is still there.

**Comment by MartinThoma** [comment]
I've just executed the MCVE example from the first post with the latest version of PyPDF2. Seems to work :tada:
