### ISSUE TITLE
With Python 3.8.0, setting warndest doesn't seem to have any effect

### ISSUE THREAD

**Issue by ndw** [py-pdf/PyPDF2#580]
Consider:
```
        with open(filename, "rb") as fn:
            with open("/dev/null", "w") as errors:
                pdf = PdfFileReader(fn, warndest=errors)
            self.pages = pdf.numPages
```
For the particular PDF file I'm processing, this prints a warning on stderr.

I did a little digging in `pdf.py` and it appears that the redeclaration of `_showwarning` in `__init__` for the `PdfFileReader` class isn't working as a closure as apparently expected. If I print `warndest` before the redeclaration, it shows a file: `TextIOWrapper`. If I print `file` inside `_showwarning`, it shows `None`.

**Comment by rufatpro** [comment]
I have exactly the same problem.

**Comment by rufatpro** [comment]
This will fix the problem in file pdf.py in function:
            `def _showwarning(message, category, filename, lineno, file=warndest, line=None):`
add first line
                `file = file if file else warndest`
before:
                if file is None:

**Comment by ndw** [comment]
Thanks for the fix @rufatpro . I hadn't found the time to go back and dig into it further.

**Comment by MartinThoma** [comment]
The warndest part was removed a while ago. For this reason I don't think this issue can occur with a recent PyPDF2 version.
