### ISSUE TITLE
Infinite loop with malformed PDF

### ISSUE THREAD

**Issue by Google-Autofuzz** [py-pdf/PyPDF2#582]
When running the following code with the latest pypi version of PyPDF2 on the attached input results of in 100% CPU consumption for an arbitrary long time:

```python

import sys
import PyPDF2

pdf = PyPDF2.PdfFileReader(sys.argv[1], strict=False, warndest=None,
                        overwriteWarnings=False)

pdf.getDocumentInfo()
pdf.getFields()
pdf.getNamedDestinations()
pdf.getNumPages()
pdf.getOutlines()
pdf.getPageLayout()
pdf.getPageMode()
pdf.getXmpMetadata()
```

[test.pdf](https://github.com/mstamy2/PyPDF2/files/5536876/test.pdf)

**Comment by MartinThoma** [comment]
There no longer is an infinite loop in `PyPDF2==1.27.8`.

The PDF is also hopelessly broken:

```console
$ cat issue-582.pdf 
ang��H
%s/I\ʱ\\\\\\\\\\\\\\\\\\\\\\\\\[\\𝟖\\\
%EO-254536430
%%EOFF�	g
e�
%%EOF%                         
```

**Comment by MartinThoma** [comment]
Reported publicly via https://github.com/py-pdf/pypdf/security/advisories/GHSA-jrm6-h9cq-8gqw
