### ISSUE TITLE
KeyError on malformed PDF

### ISSUE THREAD

**Issue by Google-Autofuzz** [py-pdf/PyPDF2#583]
When running the following code with the latest pypi version of PyPDF2 on the attached input results in an unexpected `KeyError`.

edit: Updated to reflect the `PyPDF2==2.4.2` version.

## MCVE: Code + PDF

PDF file: [test.pdf](https://github.com/mstamy2/PyPDF2/files/5536911/test.pdf)

```python
import sys
from PyPDF2 import PdfReader

reader = PdfReader(sys.argv[1], strict=False)

reader.metadata
reader.get_fields()
reader.named_destinations
len(reader.pages)
reader.outlines
reader.page_layout
reader.page_mode
reader.xmp_metadata
```

## Traceback

```python
$ python pypdf2_repro.py test.pdf
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    reader.get_fields()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 482, in get_fields
    catalog = cast(DictionaryObject, self.trailer[TK.ROOT])
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 663, in __getitem__
    return dict.__getitem__(self, key).get_object()
KeyError: '/Root'
```

**Comment by MartinThoma** [comment]
I can confirm this wit `PyPDF2==1.27.7`:

```python
Traceback (most recent call last):
  File "/home/moose/foo.py", line 8, in <module>
    pdf.getFields()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1331, in getFields
    catalog = self.trailer[TK.ROOT]
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 539, in __getitem__
    return dict.__getitem__(self, key).getObject()
KeyError: '/Root'
```

According to "TABLE 3.13 Entries in the file trailer dictionary" of the PDF 1.7 Specifications, the "/Root" key is required in the trailer. So I can confirm that the PDF is malformed.

**Comment by MartinThoma** [comment]
I've just updated the example and confirmed that it still happens.

**Comment by DL6ER** [comment]
Some more examples where this is happening when accessing, e.g., `pdfreader.numPages`:

- [qp.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/08_ConvexOptimization/17_convexopt/latex/qp.pdf)
- [convexf_def.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/08_ConvexOptimization/16_convexity/latex/convexf_def.pdf)
- [lr_nn.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/05_NeuralNetworks/09_perceptron/latex/lr_nn.pdf)
- [NAG.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/04_GradientDescent/GD/latex/NAG.pdf)
- [biastrick.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/09_SupportVectorMachines/22_multiclasssvm/latex/biastrick.pdf)
- [pla_nn.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/05_NeuralNetworks/09_perceptron/latex/pla_nn.pdf)
- [pca_procedure.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/07_DimemsionalityReduction/27_pca/latex/pca_procedure.pdf)
- [softmax_nn.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/05_NeuralNetworks/13_softmax/latex/softmax_nn.pdf)
- [pca_var0.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/07_DimemsionalityReduction/27_pca/latex/pca_var0.pdf)
- [move2trash.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/move2trash.pdf)
- [normballs.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/08_ConvexOptimization/16_convexity/latex/normballs.pdf)
- [scores.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/09_SupportVectorMachines/22_multiclasssvm/latex/scores.pdf)
- [pla_nn2.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/05_NeuralNetworks/09_perceptron/pla_nn2.pdf)
- [first_order.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/08_ConvexOptimization/16_convexity/latex/first_order.pdf)
- [lda6.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/07_DimemsionalityReduction/29_lda/latex/lda6.pdf)
- [planting.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/08_ConvexOptimization/17_convexopt/latex/planting.pdf)
- [max_point.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/08_ConvexOptimization/16_convexity/latex/max_point.pdf)
- [mlp_notation.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/05_NeuralNetworks/14_mlp/latex/mlp_notation.pdf)
- [pla_nn_a.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/05_NeuralNetworks/09_perceptron/latex/pla_nn_a.pdf)
- [lda2.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/07_DimemsionalityReduction/29_lda/latex/lda2.pdf)

They all seem to be broken, however, there is one

- [yaleb_exs.pdf](https://github.com/tnd79bk/EbookMLCB/blob/2441571df00c59c57b431c74ef4000faaa795a52/Chapters/figs/07_DimemsionalityReduction/28_pca2/latex/yaleb_exs.pdf)

which can at least be opened in a normal PDF viewer (but it seems to be empty).

**Comment by pubpub-zz** [comment]
those files are deeply damaged and cannot be opend with acrobat reader (even yaleb_exs ???)
PyPDF2 can not be expecting to read them.  

@MartinThoma , this issue should be closed

**Comment by pubpub-zz** [comment]
+1? (to get below 60😎)

**Comment by MartinThoma** [comment]
I just tried to open those files. Yes, my PDF Viewer can open some of them (not all), but all of them had just a blank page. The only thing that sometimes changed was the dimension of that blank page.

I'll close this for the moment as we have more important issues to work on that driving robustness up that much.

**Comment by MartinThoma** [comment]
I've linked it in https://github.com/py-pdf/PyPDF2/discussions/1210 as we might want to throw PdfReadError instead of the KeyError.
