### ISSUE TITLE
Unexpected xml.parsers.expat.ExpatError on malformed PDF

### ISSUE THREAD

**Issue by Google-Autofuzz** [py-pdf/PyPDF2#585]
When running the following code with the latest pypi version of PyPDF2 on the attached input results in an unexpected `xml.parsers.expat.ExpatError`:

## MCVE: Code + PDF

Example document: [test.pdf](https://github.com/mstamy2/PyPDF2/files/5536984/test.pdf)

```python
from PyPDF2 import PdfReader

reader = PdfReader("test.pdf")
reader.xmp_metadata
```

## Traceback

```python
Traceback (most recent call last):
  File "foo.py", line 5, in <module>
    reader.xmp_metadata
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 318, in xmp_metadata
    return self.trailer[TK.ROOT].xmp_metadata  # type: ignore
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 671, in xmp_metadata
    metadata = XmpInformation(metadata)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/xmp.py", line 206, in __init__
    doc_root: Document = parseString(self.stream.get_data())
  File "/home/moose/.pyenv/versions/3.6.15/lib/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/home/moose/.pyenv/versions/3.6.15/lib/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/home/moose/.pyenv/versions/3.6.15/lib/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 53, column 15
```

## Environment

```
$ python -c "import PyPDF2; print(PyPDF2.__version__)"
2.3.1-dev
```

**Comment by guillaume-uH57J9** [comment]
I have encountered a similar error with a real-world PDF when calling getXmpMetadata().
My PDF cannot be shared as it contains personal information, but this issue already has a test PDF. 

PyPDF version 1.26.0-4
python version 3.9.2-3
Debian version 11.0 (testing)

Error message:

> ExpatError('not well-formed (invalid token): line 5, column 87')

**Comment by MartinThoma** [comment]
@guillaume-uH57J9 Could you please share a full traceback? Do you have an example PDF?

**Comment by MartinThoma** [comment]
@guillaume-uH57J9 Thank you :pray: I've completely missed that :sweat_smile: 

Sadly, the issue still occurs with the latest version of PyPDF2. It looks to me as if the included XML of the PDF document is broken. We might never be able to read the content, but we should raise a warning / a PyPDF2 expection that is more explicit.

**Comment by guillaume-uH57J9** [comment]
@MartinThoma Yes, it would be better to either have a warning and return None, or through an exception at the PyPDF2 level. 

Expat is kind of an implementation details, so exposing expat exceptions is not ideal. At the moment, if you want to safely use PyPDF2, you have to import expat in order to catch that specific exception. 

As an side, help(PyPDF2.PdfFileReader.xmpMetadata) does not mention any exception at the moment, so you wouldn't know to catch any exception until you stumble upon this. If an exception is raised, it would be better to document it.

**Comment by MartinThoma** [comment]
@guillaume-uH57J9 What do you think about https://github.com/py-pdf/PyPDF2/pull/1030 ?
