### ISSUE TITLE
PdfReadError: Unsupported PNG filter 4

### ISSUE THREAD

**Issue by odiebojangles** [py-pdf/PyPDF2#587]
I have had this issue crop up recently when attempting to use PdfFileReader(). There doesn't appear to be anything special about the PDF's that are causing the issue, but it can be resolved by saving the PDF as a lower quality and attempting to read it again.

**Comment by MartinThoma** [comment]
Do you have an example PDF + code that shows the issue?

**Comment by MartinThoma** [comment]
This issue contains too little information to work on it. It could also be solved by https://github.com/py-pdf/PyPDF2/commit/f776f54c673674c31e81b8c4dba88f60e51c1006
