### ISSUE TITLE
extract arabic text from pdf

### ISSUE THREAD

**Issue by dihia-lanasri** [py-pdf/PyPDF2#591]
Hello;

I have a pdf in arabic language text. I need to extract its text. but I obtain something like:
f˘£˘∏˘≤â GCh∫ GCeù¢, b˘Éa˘∏˘á J†°˘Ée˘æ«á eø h’já Gdû°∏∞ fëƒ
fl«˘ª˘Éä Gd˘ÓL˘ÄÚ Gdü°˘ëôGhjÚ eƒL¡á d∏û°©  

How can I decode it?  utf-8 doesn't work.

**Comment by Anas-jaf** [comment]
this is not utf-8
did you figured work around ?

**Comment by MartinThoma** [comment]
#464 might help to solve this

**Comment by pubpub-zz** [comment]
@dihia-lanasri ,

can you provide a pdf to evaluate extraction. thanks

**Comment by MartinThoma** [comment]
@pubpub-zz I've added one in https://github.com/py-pdf/PyPDF2/pull/954 :-)

**Comment by pubpub-zz** [comment]
Under analysis

**Comment by pubpub-zz** [comment]
@dihia-lanasri , some work has been done about text extraction but arabic being written right to left make me difficult to evaluate. can you give your feed backs?
