### ISSUE TITLE
Overlapping text and images losing color in newly created pdf

### ISSUE THREAD

**Issue by Teut2711** [py-pdf/PyPDF2#592]
I tried to create a new pdf by looping through a number of pdfs , picking out pages from them and putting them to an instance of the PdfWriter class.
However the equations and the text are all broken up in the new pdf. 

Currently for the writing purposes if I can just put the page as a image in the new pdf , it would be great.

Any tips on how to do this would be great!

New Pdf
![image](https://user-images.githubusercontent.com/40588378/101293953-1bc3af80-383a-11eb-91af-58f988534ddc.png)

Old Pdf
![image](https://user-images.githubusercontent.com/40588378/101293958-25e5ae00-383a-11eb-8e2e-d827723f8380.png)

**Comment by MartinThoma** [comment]
Do you have example code + PDFs that show this issue?

**Comment by MartinThoma** [comment]
As this lacks usable examples, nobody will be able to verify this issue. Hence I close it. Please let me know if you have this issue as well with the latest PyPDF2 version.

**Comment by Teut2711** [comment]
Sorry.  I don't even remember now what I was working on and I am no longer working on it now. Yes, closing this issue will be better.

**Comment by moda20** [comment]
@MartinThoma This is still an issue 

```
from PyPDF2 import PdfReader, PdfWriter

def rewrite(input_file):
    pdf_reader = PdfReader(input_file)
    total_pages = len(pdf_reader.pages)
    new_file = f"{input_file[:-4]}_rewritten.pdf"
    with open(new_file, "wb") as old_file:
        pdf_writer = PdfWriter()
        for page in range(0, total_pages):
            pdf_writer.add_page(pdf_reader.pages[page])
        pdf_writer.write(old_file)
    return true
```

using the pdf from this [link](https://dq06ugkuram52.cloudfront.net/files/12652377/33146778.pdf) (public pdf), and when reading and writing the same file, we do still lose the colors and default to grayscale 

```
rewrite('<local pdf path>')
```

@Teut2711 were you able to get over this issue somehow ?

**Comment by stefan6419846** [comment]
@moda20 PyPDF2 is deprecated in favor of *pypdf*. Please open a new issue with all details if this problem still persists with *pypdf*.

**Comment by moda20** [comment]
@stefan6419846 No it seems pypdf doesn't have this issue anymore. Thanks
