### ISSUE TITLE
PdfFileMerger can NOT handle encrypted PDFs

### ISSUE THREAD

**Issue by gaborpelesz** [py-pdf/PyPDF2#594]
Pull request for fixing some of the problems: #593

## Problem 1:
The merger cannot handle decrypted PDF files when the PDF is provided via a PdfFileReader object, althought the logic is (somewhat) implemented.

### Understanding the problem and a solution:
The code below in theory handles the transfer of the decryption key of the original object, however, the previous line completely overwrites the original file object which eliminates its decryption key attribute.
```python
...
fileobj = filecontent
if hasattr(fileobj, '_decryption_key'):
    decryption_key = fileobj._decryption_key
```
As a solution the attribute extraction needs to be placed before the overwriting procedure.
```python
...
if hasattr(fileobj, '_decryption_key'):
    decryption_key = fileobj._decryption_key
fileobj = filecontent
```

## Problem 2:
Although if you give the merger a PDF encrypted with an empty password, it handles it well UNTIL you specify the pages explicitly as a tuple.

### Understanding the problem and a solution:
That is because when no pages were provided OR the pages were provided with a `PageRange` object, the method `getNumPages()` runs both times to handle the specific case.
```python
if pages == None:
    pages = (0, pdfr.getNumPages())
elif isinstance(pages, PageRange):
    pages = pages.indices(pdfr.getNumPages())
```
The `getNumPages()` method (interestingly) tries a decryption with an empty password that is why it works in those cases.

A solution is to try explicitly a decryption with an empty password if the PDF is encrypted and no decryption key was provided.
```python
if decryption_key is not None:
    pdfr._decryption_key = decryption_key
    elif pdfr.isEncrypted:
        # if the file is encrypted at least try 
        # the decryption with an empty password
        pdfr.decrypt('')
```

**Comment by MartinThoma** [comment]
Thank you for explaining this in such detail! Back when you wrote it, I wasn't the maintainer - but when I see such bug tickets, I will try to answer very quickly in future :heart:

**Comment by MartinThoma** [comment]
The places look different now, but are still recognizable:

Problem 1:

```python
            if hasattr(fileobj, "_decryption_key"):
                decryption_key = fileobj._decryption_key
```

Problem 2:

```python
        if pages is None:
            pages = (0, len(reader.pages))
        elif isinstance(pages, PageRange):
            pages = pages.indices(len(reader.pages))
```

I believe both issues were solved, but I want to test it.

**Comment by MartinThoma** [comment]
I think this issue was solved. At least `test_merge` seems to cover it: https://github.com/py-pdf/PyPDF2/blob/main/tests/test_merger.py#L37-L38
