### ISSUE TITLE
extract_text doesn't extract ligatures correctly

### ISSUE THREAD

**Issue by Baytars** [py-pdf/PyPDF2#598]
I appreciate it that your tool keep the original reading order of text and omit those repeated headers and footers that interfere with main body text that crosses pages, which makes conversion from PDF to EPUB convenient. However, there seems to be a gremlin for the extracted text - some strings are misreplaced by some punctuation marks, like
- `fi` misreplaced by `˛` (e.g. `fields` extracted to be `˛elds`)
- `ff` misreplaced by `˙` or `˜` (e.g. `different` extracted to be `di˙erent` and `Differential` extracted to be `Di˜erential`)
- `ft` misreplaced by `˚` (e.g. `after` extracted to be `a˚er`)
- `th` misreplaced by `˜` (e.g. `this` extracted to be `˜is`)
For comparison I used Python `pdftotext` package too and found out there's no such a problem, but that package keep the original typography which puts two columns of texts in a row and is not ideal for PDF conversion.
Any clue about this issue? Looking forward to a perfect PyPDF because it is so useful!

**Comment by MartinThoma** [comment]
#464 might solve this

**Comment by MartinThoma** [comment]
#924 very likely fixed it. It looks as if you might have seen issues with cmaps / ligatures.

`PyPDF2==2.1.0` should no longer have this issue. I'll release it today.

**Comment by gargarvin** [comment]
I am still having this issue. 
'fi' 'fl' and 'ff' characters are returning NULL

[PDF](https://transfer.sh/9SyIwg/Inspection_redacted.pdf)

**Comment by pubpub-zz** [comment]
We can leave it closed: @gargarvin opened #1351 for the new test case
