### ISSUE TITLE
merge fails when a PPT converted to PDF using google docs slide is used

### ISSUE THREAD

**Issue by abhardwaj29** [py-pdf/PyPDF2#602]
```

decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
--
return decimal.Decimal.__new__(cls, str(value)) File "/usr/local/lib/python3.9/site-packages/PyPDF4/generic.py", line 232, in __new__return FloatObject(num)


```

I have a PDF file that I generated from a PPT using google docs, I checked the file metadata and that says PDF version is 1.4 but if I save the same ppt as PDF using office it creates a PDF version 1.7

In case of 1.4 I am getting that error when merging PDF.

**Comment by ktowen** [comment]
Any news on this?

**Comment by MartinThoma** [comment]
Could that be related? https://github.com/mstamy2/PyPDF2/pull/387

**Comment by MartinThoma** [comment]
Can you share a PDF that shows the issue?

**Comment by MartinThoma** [comment]
Can you share the code you wrote that lead to this issue?

**Comment by Atlasfreak** [comment]
As I am currently getting the same error I can confirm that #387 fixes the issue. At least the changes for generic.py, the changes in pdf.py are unrelated.
I am currently not able to share a pdf that creates this issue.

**Comment by MartinThoma** [comment]
Can somebody please check if the issue still appears with the latest version of PyPDF2?

**Comment by MartinThoma** [comment]
I tried to reproduce it like this:

```
>>> from PyPDF2 import PdfReader, PdfMerger
>>> merger = PdfMerger()
>>> for pdf in ["crazyones.pdf", "google-slides-pdf.pdf"]:
...   merger.append(pdf)
... 
>>> merger.write("out.pdf")
>>> merger.close()
```

Worked fine with PyPDF2==2.9.0.

As I cannot reproduce it due to the lack of code and a PDF file, I close it. It might also have been solved by other changes.

Please let me know if you still encounter this issue with the latest PyPDF2 version.
