### ISSUE TITLE
Adding Attachments and Javascript not working

### ISSUE THREAD

**Issue by draro** [py-pdf/PyPDF2#607]
I added attachments to a PDF, then I want a JS to call the attachments, but once try to add the JS, the attachments are excluded from the PDF.

File size adding only attachments:
* size of SOURCE: 55168
* size of OUTPUT: 9441963

Adding the output.addJS(js):
* size of SOURCE: 55168
* size of OUTPUT: 37217

Also the output._root_object are different.

How can I fix my issue?

**Comment by MartinThoma** [comment]
Can you share the PDF / the code?

**Comment by draro** [comment]
Hi, sorry but I do not remember exactly what i was studying at that time. I can try to search for the code but not sure how i ended up with a solution

**Comment by MartinThoma** [comment]
I will close this issue now. If anybody encounters it again, please let me know.
