### ISSUE TITLE
Issue displaying a light purple Background on Mac(iOS, Mac OS)

### ISSUE THREAD

**Issue by Kam21** [py-pdf/PyPDF2#615]
Hi All,

Is anyone came across an issue displaying a light purple background on mac OS ? 

We encoded few PDF with PyPDF2 and trying to display on mac (iOS & Mac); it is displaying as black background.

attached 
Expected:

<img width="687" alt="Correct_Display" src="https://user-images.githubusercontent.com/8528848/113580737-1f9eed00-95f4-11eb-9c58-b7576cd565bb.png">

Displaying as:
<img width="698" alt="Issue_Display" src="https://user-images.githubusercontent.com/8528848/113580792-334a5380-95f4-11eb-9d2b-53d3113480a5.png">

Note: However , the adobe reader is displaying correctly on Mac

Please advice, why the mac OS is changing the background to black.

**Comment by MartinThoma** [comment]
Do you have an example PDF + code that shows the issue?

**Comment by MartinThoma** [comment]
This issue has too little information to work on it. I'm closing it for this reason. If anybody has more information, I can reopen it.
