### ISSUE TITLE
Slow processing on long multi-line content

### ISSUE THREAD

**Issue by nell-cx** [py-pdf/PyPDF2#622]
I've got a PDF (unfortunately proprietary and can't be shared) that has very long content structured as follows:

```
9 0 obj
<<
/AAPL:AKAnnotationObject (<65 characters>\
<65 characters>\
<65 characters>\
...
<final characters>)
>>
endobj
```

The object, overall, takes 314426 lines. I've found that using this document with `PdfFileMerger` would take around a couple days to complete `write`ing. Digging in to [readStringFromStream](https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/generic.py#L326) I can tell that it's definitely chugging through the file - but sure seems to take a while to get through it.

Could this be related to #78?

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/PyPDF2/commit/c6c56f550bb384e05f0139c796ba1308837d6373 improved the runtime quite a lot.

As this issue does not contain enough information to work on it, I'll close it
