### ISSUE TITLE
UnicodeDecodeError occurs when processing PDF files with Shift-JIS embedded font names.

### ISSUE THREAD

**Issue by TakamiChie** [py-pdf/PyPDF2#623]
In PDFFileReader, UnicodeDecodeError occurs when reading an old PDF with Shift-JIS used in the name of the embedded font and writing it.
The smallest code samples are:

```python
from io import BytesIO

from PyPDF2 import PdfReader, PdfWriter
from tests import get_pdf_from_url

reader = PdfReader(
    BytesIO(
        get_pdf_from_url(
            "https://github.com/mstamy2/PyPDF2/files/6560105/6.pdf",
            name="issue-623.pdf",
        )
    ),
    strict=True,
)
writer = PdfWriter()
writer.add_page(reader.pages[0])
with open("dest.pdf", "wb") as f:
    writer.write(f)  # Error occurred

```

Now, if you set `strict=False` to the constructor of PdfFileReader, the warning appears, but the write itself succeeds (`PdfReadWarning: Important character in Name Object [generic.py:489]`).
However, the name of the embedded font is not written correctly, and character information is not output.

I found something that can be published in a PDF that reproduces the phenomenon, so attach it. If necessary, please check.
[PDF reproduced by the phenomenon](https://github.com/mstamy2/PyPDF2/files/6560105/6.pdf)

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/PyPDF2/commit/8691814abf77a035524805d764c6e1220dc1d607 might address that need

**Comment by MartinThoma** [comment]
Thank you for reporting the problem :heart: 

It seem to me that the issue no longer exists in the latest version of PyPDF2, hence I close it. Please let me know if I'm wrong :-)
