### ISSUE TITLE
PdfFileReader error for pdfs without known pdf version

### ISSUE THREAD

**Issue by VanekPetr** [py-pdf/PyPDF2#624]
I got an error when getting "idnum" and "generation" inside PdfFileReader(...) -> read(stream) -> readObjectHeader(stream). It seams that the stream format is not supported.

Could it be because of unknown pdf version (see attached figure)? Is there any way how to handle it?

![PDFproperties](https://user-images.githubusercontent.com/43985658/120372640-f609f580-c306-11eb-8c3a-1909b7c15ade.PNG)

Thank you!

**Comment by DimIsaev** [comment]
dead project?

**Comment by MartinThoma** [comment]
Is this still an issue? Is it possible to share a PDF+code which shows the issue?

**Comment by MartinThoma** [comment]
As this issue does not contain enough information to work on it, I'm going to close it.

If anybody has more information, please feel free to ping me here :-)
