### ISSUE TITLE
Some valid but unstand indirect object cause PyPDF2 failure

### ISSUE THREAD

**Issue by ulion** [py-pdf/PyPDF2#64]
The issue is something like this: `/FontFile2 11  0 R`

There is more than 1 space there, cause PyPDF2 failure:

```
/PyPDF2/generic.py", line 256, in readFromStream
    return NumberObject(num)
ValueError: invalid literal for int() with base 10: ''
```

This should be supported anyway.

**Comment by MartinThoma** [comment]
Nothing seems to be left to do here.
