### ISSUE TITLE
PyPDF2 is not extracting text correctly.

### ISSUE THREAD

**Issue by dennisyd** [py-pdf/PyPDF2#643]
I recently extracted text using PyPDF2 and it only pulled around 100 words from a pdf file that contained over 2500 words. I used pdfminer and it extracted the text correctly (about 2500 words).

**Comment by MartinThoma** [comment]
Can you share the pdf and a file with the expected output?

**Comment by dennisyd** [comment]
Could you explain a little more? Why did you contact me?

Thanks,
Yancy

**Comment by MartinThoma** [comment]
You have created an issue on github in October. I've answered the and github sent you an email

**Comment by dennisyd** [comment]
ok thanks

**Comment by MartinThoma** [comment]
As this issue does not contain any information that is helpful, I'll close it. Feel free to create a new issue with your version of PyPDF2 + code + a PDF that shows the specific issue you have.
