### ISSUE TITLE
Page Rotation and Bounding Box issue

### ISSUE THREAD

**Issue by siriv1997** [py-pdf/PyPDF2#649]
1. I have a document with some pages being landscape, and the others being portrait.
While reading that pdf landscape pages are rotating 270 deg because of this issue I have faced bounding boxes in different places.
2. I have tried to avoid rotation by using **page.mergeRotatedTranslatedPage(page3,270,page.mediaBox.getWidth()/2 ,page.mediaBox.getHeight()/2 ,True),page.rotateClockwise(270)**. But they haven't given me any positive results.
 I have attached the code snippet below:

```python
doc_name = fileName
obj = s3_connection.Object(bucket, doc_name)  # Fetching document from S3bucket
fs = obj.get()['Body'].read()                 # Reading the document
pdf = PdfFileReader(BytesIO(fs),strict=False)
orientation = pdf.getPage(33).get('/Rotate')

size_pdf = pdf.getPage(k[1]-1).mediabox
page_width = size_pdf.getWidth()
page_height = size_pdf.getHeight()

can = canvas.Canvas(packet,pagesize=(8.5 * 72, 11 * 72))

box=ast.literal_eval(k[0])
B_W = box['Width']
B_H = box['Height']
B_L = box['Left']
B_T = box['Top']

can.rect(B_L*float(page_width),(float(page_height)-(B_T*float(page_height)))-(B_H * float(page_height)),B_W* float(page_width),B_H*float(page_height),fill=True,stroke=True)
can.save()

new_pdf = PdfFileReader(packet,strict=False)                     
page = pdf.getPage(temp_page_number - 1)
page3 = new_pdf.getPage(0)  

page.mergeRotatedTranslatedPage(page3, 180, page3.mediaBox.getWidth()/2, page3.mediaBox.getWidth()/2)
```

**Comment by MartinThoma** [comment]
> But they haven't given me any positive results.

What does that mean?

**Comment by MartinThoma** [comment]
Could you create a minimal example? I guess the AWS S3 stuff is not necessary to show your issue?

**Comment by MartinThoma** [comment]
I close this issue now as I don't understand the problem. If you add more information, I can open it again.
