### ISSUE TITLE
Error merging PDF (assert start >= last_end)

### ISSUE THREAD

**Issue by jeldis** [py-pdf/PyPDF2#650]
Hi,
I was using the PyPDF2 library to merge two PDF files, for some reason some give the error in **PdfFileReader** (assert start >= last_end), searching inside **pdf.py** I find that it has (assert), the question is, it must be this instructions in the code that is used in production?, it should be removed and put into a testing environment (unitesting)

Best regards,

Jorge

**Comment by MartinThoma** [comment]
Do you have example code + a PDF that shows the issue?

**Comment by MartinThoma** [comment]
I'm closing this issue now as it is not reproducible. If you add more information, I can open it again.
