### ISSUE TITLE
Decryption error in script mode, works in ptpython/shell

### ISSUE THREAD

**Issue by pyahmed** [py-pdf/PyPDF2#652]
I have a couple of pdf files from which I would like to extract some data. I fiddled around in ptpython (a python REPL) and managed to get the text extracted. Once I saved the same steps in .py file and ran it, it throws an error:
`PyPDF2.utils.PdfReadError: file has not been decrypted`

After a lot of back and forth and rechecking, the file seems to be encrypted and prohibit copying the text, yet can be opened in Adobe PDF Reader / SumatraPDF for example.

Steps to reproduce:

OS: Windows 10 Pro/x64
Python: 3.9.1 / 64 bit
PyPDF2: 1.26.0

As I can't share the files in question I looked for a similar 'protected' file. The following PDF has similar restrictions and allows to reproduce the behaviour described here:
https://download.novapdf.com/download/samples/pdf-example-encryption.pdf

```python
from PyPDF2 import PdfReader
filename = 'pdf-example-encryption.pdf'
reader = PdfReader(filename)
print(reader.metadata)
```
The above code will trigger the following error, irrespective of whether it is ran from a .py file or from a python shell (official or ptpython).

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 296, in documentInfo
    return self.metadata
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 274, in metadata
    obj = self.trailer[TK.INFO]
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 644, in __getitem__
    return dict.__getitem__(self, key).get_object()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 222, in get_object
    return self.pdf.get_object(self).get_object()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 1053, in get_object
    raise PdfReadError("file has not been decrypted")
PyPDF2.errors.PdfReadError: file has not been decrypted
```
However if you run only the following code in a shell:

```python
from PyPDF2 import PdfReader
filename = 'pdf-example-encryption.pdf'
reader = PdfReader(filename)
```

Then instead of running this line:
`print(pdf_reader.metadata)`

just type `pdf_reader.` and hit tab for autocompletion suggestions. Once the autocompletion suggestions have been shown this code will work:
```python
print(reader.metadata)
print(reader.page[0].extract_text())
```

How to make it work in a .py file so that it works in a "non-interactive" mode?

**Comment by MartinThoma** [comment]
Interesting. When I upload the example PDF to http://pdf-analyser.edpsciences.org/check, it shows:

> PDF Syntax error : Text extraction is not allowed: ', mode 'w+b' at 0x7feecd999030>

My guess is that it's either protected in some way or that the PDF doesn't follow the PDF specification

**Comment by MartinThoma** [comment]
I can **confirm** for `PyPDF2==1.27.7` that [this file](https://download.novapdf.com/download/samples/pdf-example-encryption.pdf) with the code:

```python
import PyPDF2
pdf_reader = PyPDF2.PdfFileReader('pdf-example-encryption.pdf')
print(pdf_reader.documentInfo)
```

leads to

```
Traceback (most recent call last):
  File "/home/moose/foo.py", line 5, in <module>
    print(pdf_reader.documentInfo)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1230, in <lambda>
    documentInfo = property(lambda self: self.getDocumentInfo(), None, None)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1225, in getDocumentInfo
    obj = self.trailer[TK.INFO]
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 539, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 191, in getObject
    return self.pdf.getObject(self).getObject()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/pdf.py", line 1745, in getObject
    raise PdfReadError("file has not been decrypted")
PyPDF2.errors.PdfReadError: file has not been decrypted
```

I can also confirm the weird auto-complete behavior with ptpython. My guess is that it calls a function which triggers the rest to work ... but it's a real WTF.

**Comment by MartinThoma** [comment]
This issue still occurs, even with the latest changes.

@exiledkingcc Do you maybe have an idea why this happens?

**Comment by exiledkingcc** [comment]
this magic happens because there is decrypting in `_get_num_pages`.
here is my guess: 
your python shell will load properties of `PdfReader` object, 
the property `pages` (or other properties) will call `_get_num_pages` eventually.
then the pdf is decrypted, evething will be fine.
but metadata will NOT.

this code in script is OK:
```
reader = PyPDF2.PdfReader("pdf-example-encryption.pdf")
print(len(reader.pages))   # get error if this line removed
print(reader.documentInfo)
```

@MartinThoma 
some (or many) pdfs are encrypted by the empty password (`""`)
maybe we should find a better way to handle there pdfs.

**Comment by MartinThoma** [comment]
Ouch, the empty, password thing was mentioned before 🙈 thank you for having a look!

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/PyPDF2/pull/1015 fixed this issue.
