### ISSUE TITLE
extractText function returns None

### ISSUE THREAD

**Issue by vteran93** [py-pdf/PyPDF2#664]
I have been doing some testing and I found that the extract text function is returning None and other times deleting white spaces in the pdf content inside a paragraph.

Expected behavior:

Return all the text from the pdf with the correct spaces.

**Comment by MartinThoma** [comment]
Please share the PDF files you were using - the smaller the PDF that shows the issue, the better :-)

**Comment by vteran93** [comment]
Hi Martin, I was debugging my PDF today because it has intellectual property inside and I can not share it (sorry) and I think I found the issue. It happens when you have Something like `b"\t Address"` in a string inside `Tj` operator, it skipped by this section
```python
if operator == b_("Tj"):
    _text = operands[0]
    if isinstance(_text, TextStringObject):
        text += Tj_sep
        text += _text
        text += "\n"
```
the reason is that the `b"\t Address"` is type `ByteStringObject` digging more into it, I found the method `createStringObject` which try to `decode_pdfdocencoding` and that function raise an UnicodeDecode error for the first 24 chars (+ 1 more belonging to U+00AD) in the unicode table including `\t` which is `ord` 9 because _pdfDocEncoding returns `u_('\u0000')`, so i was thinking: why are they doing it?


![image](https://user-images.githubusercontent.com/1650359/162800417-2e1108b1-cbec-479f-a9d2-ecd699d824c8.png)

**Comment by MartinThoma** [comment]
You seem to be super close to solve it. Maybe you can manually craft a PDF that shows the issue (similar to https://github.com/py-pdf/PyPDF2/blob/master/Tests/test_reader.py#L124-L144 )?

**Comment by vteran93** [comment]
At this moment in my life, I do have not enough knowledge about Unicode to tell which the problem is? 🐛  If they do that, is maybe because the codification for different languages has something to do. (-.-!)ゞ

**Comment by vteran93** [comment]
Ok, I just discovered that PyPDF2 also does not support decompress for flate :-) 
[like in this example ](https://stackoverflow.com/questions/53608910/decompress-flatedecode-objects-in-pdf-in-python)

```python
import re
import zlib

pdf = open("some_doc.pdf", "rb").read()
stream = re.compile(b'.*?FlateDecode.*?stream(.*?)endstream', re.S)

for s in re.findall(stream,pdf):
    s = s.strip(b'\r\n')
    try:
        print(zlib.decompress(s).decode('UTF-8'))
        print("")
    except:
        pass
```

**Comment by pubpub-zz** [comment]
@vteran93, can you check with latest version that your issue has been fixed

**Comment by MartinThoma** [comment]
@vteran93 could you please check if your problem is solved with the latest version of PyPDF2?

**Comment by MartinThoma** [comment]
I assume it is solved. Please let me know if it isn't.
