### ISSUE TITLE
Rename primary branch from master to main

### ISSUE THREAD

**Issue by MasterOdin** [py-pdf/PyPDF2#736]
Request to switch from the primary branch be `main` from `master`, which is suggested for improving inclusion. See https://github.com/github/renaming for links to discussion around why as well as info on how best to do it on GH.

-----

# Renaming master ➔ main is done

Please run this locally:

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by MartinThoma** [comment]
Uh, interesting:

> Renaming a branch will:
> * Re-target any open pull requests

Then I don't see any issue in doing so.

How will existing forks / contributors be affected?

**Comment by MartinThoma** [comment]
I see three timing possibilities

1. Immediately (e.g. tomorrow): I guess most people still haven't noticed that PyPDF2 is back. We could rename before people come back / actively contribute (again)
2. Soon-ish (e.g. May 2022): Give people some time to see the news Issue
3. Scheduled (e.g. end of 2022)

As GitHub seems to have added quite a couple of notices for this case, I suggest (2).

**Comment by MasterOdin** [comment]
Given this this a revival of a long dormant repo that has a new home, new docs page, etc., I think fine to just do it immediately, and whatever is broken can be broken along with the other stuff that's been changed in this short period of time, but the root thing would want to be preserved (PRs) will keep working just fine.

**Comment by MartinThoma** [comment]
# Renaming master ➔ main is done

Please run this locally:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by MartinThoma** [comment]
There were 72 PRs before, now there are only 67 PRs. Seems like github accidentially closed 5. One of them is https://github.com/py-pdf/PyPDF2/pull/331

**Comment by MartinThoma** [comment]
![image](https://user-images.githubusercontent.com/1658117/162922534-0b4e0e9a-93f7-4ced-ab80-3bba87570533.png)
I'll check that after work

**Comment by MartinThoma** [comment]
Another issue after this change is that readthedocs was still using `master` instead of  `main`. It's fixed now.
