### ISSUE TITLE
PageRange import error

### ISSUE THREAD

**Issue by Dobatymo** [py-pdf/PyPDF2#737]
```
  File "test-pdf.py", line 7, in <module>
    from PyPDF2 import PdfFileMerger, PdfFileReader
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/PyPDF2/__init__.py", line 2, in <module>
    from .merger import PdfFileMerger
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/PyPDF2/merger.py", line 33, in <module>
    from .pagerange import PageRange
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/PyPDF2/pagerange.py", line 36, in <module>
    class PageRange(object):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/PyPDF2/pagerange.py", line 86, in PageRange
    __init__.__doc__ = __init__.__doc__.format(page_range_help=PAGE_RANGE_HELP)
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by MartinThoma** [comment]
Interesting .. I know how to fix this and I'll do that today. However, I'm not sure why this occurs in the first place.

**Comment by MartinThoma** [comment]
It is https://github.com/py-pdf/PyPDF2/pull/674 and the fix is to restore

```
    # Just formatting this when there is __doc__ for __init__
    if __init__.__doc__:
        __init__.__doc__ = __init__.__doc__.format(page_range_help=PAGE_RANGE_HELP)
```

**Comment by MartinThoma** [comment]
The fix is now in `master` and will be deployed with 1.27.3 in roughly 6 hours.

If this is blocking you, you can [install the development version](https://pypdf2.readthedocs.io/en/latest/user/installation.html#development-version) in the mean time.

**Comment by MartinThoma** [comment]
@Dobatymo Could you please show me the output of `python --version` and `python -m platform`?

**Comment by Dobatymo** [comment]
This was in CI on github actions with the linux runner. According to the path in the traceback it should be python version 3.6.15

**Comment by MartinThoma** [comment]
Huh, interesting. I wasn't aware of that flag. Thank you!

**Comment by MartinThoma** [comment]
I was asking because I'm interested in [who is using PyPDF2](https://github.com/py-pdf/PyPDF2/discussions/683). I was wondering if I need to extend CI :-)
