### ISSUE TITLE
Speed up parser

### ISSUE THREAD

**Issue by wolever** [py-pdf/PyPDF2#78]
Currently the parser is quite slow, even for moderately sized PDFs. When I get a bit of time, I'm going to investigate different ways it could be sped up. Right now (pending some profiling, obviously) I suspect this is going to involve re-writing some of the core parser loops in something lower level like Cython. I'm looking into options to see if it's possible to write in a language which will be able to compile back to vanilla Python for the benefit of PyPy and friends.

I'm opening this issue to start discussion on the matter, and see if you've got any strong feelings either way.

**Comment by MartinThoma** [comment]
Is this still a concern? Do you have an example pdf to share where we go into details why it's slow with PyPDF2 2.1.0+?

**Comment by vedantv3** [comment]
are there any leads to speed up this pypdf 
becuase its extraction is good problem is only the speed

**Comment by stefan6419846** [comment]
We recently removed some specific bottlenecks which affected speed. Without specific details where exactly *pypdf* is slow code-wise and corresponding example files there is not much planned here. As usual, you are of course invited to investigate possible performance improvements and provide corresponding PRs to make *pypdf* faster.
