### ISSUE TITLE
Unsupported PNG filter 3

### ISSUE THREAD

**Issue by DmitriyReztsov** [py-pdf/PyPDF2#793]
During merging two or more files I've met with such error: Unsupported PNG filter 3. Merging has its place programmaticaly, with opening pdf to BytesIO. I didn't see something special in the file, which raised this error. If I open, save as the same file in PDF-editor (Foxit PhantomPDF, for example) then PyPDF can read and merge such file 

## Environment

Which environment were you using when you encountered the problem?

```python
$ python -m platform 
# Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
# 1.27.8
```

## Code

This is a minimal, complete example that shows the issue:

```python
def get_request(url: str) -> Tuple[bytes, bool]:
    resp = requests.get(url, allow_redirects=True)
    if not resp.ok:
        logger.error(f"Could not download file from {url}, server responded {resp.status_code}: {resp.reason}")
        return b"", False
    return resp.content, True

def merge_to_pdf(files: List, created_by: User, merged_name: str) -> File:
    buffer = BytesIO()
    merger = PdfFileMerger()
    merged_filename = f"{merged_name}.pdf"

    if settings.BUILD_ENV == "local":
        for file in files:
            merger.append(file)  # this line calls raises the error
    else:
        for file in files:
            pdf_content, ok = get_request(file)
            if not ok:
                return None
            pdf_buffer = BytesIO(pdf_content)
            merger.append(PdfFileReader(pdf_buffer))  # and this line calls raises the error (in non-local env)

    merger.write(buffer)
    merger.close()
    buffer.seek(0)
    merged_file = File.objects.create(
        file=DjangoFile(buffer, merged_filename),
        name=merged_filename,
        created_by=created_by,
    )
    return merged_file
```

## PDF

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
[930_Exhibit_A-1_Final_20220209_Intialed_mt.pdf](https://github.com/py-pdf/PyPDF2/files/8539376/930_Exhibit_A-1_Final_20220209_Intialed_mt.pdf)

**Comment by gentisaliu** [comment]
I would like to contribute.

**Comment by MartinThoma** [comment]
@gentisaliu Cool! In which way? How can I help you to get started?

**Comment by gentisaliu** [comment]
Thanks Martin.

I wanted to start with this issue, but I am unable to reproduce the error. 

@DmitriyReztsov Are you sure the attached PDF above is the one causing the problem?

```python
def test_issue793():
    pdf1_path = os.path.join(RESOURCE_ROOT, "issue-793.pdf")
    pdf2_path = os.path.join(RESOURCE_ROOT, "form.pdf")

    merger = PyPDF2.PdfFileMerger()

    merger.append(pdf1_path)  # ensure this call does not raise an "Unsupported PNG filter 3" error
    merger.append(pdf2_path)

    tmp_path = "issue793_merged.pdf"
    merger.write(tmp_path)
    merger.close()

    # Clean up
    os.remove(tmp_path)

**Comment by MartinThoma** [comment]
Thank you both for having a look at it :hugs:
