### ISSUE TITLE
Pdf form overlap issue

### ISSUE THREAD

**Issue by Rob1080** [py-pdf/PyPDF2#85]
When merging 2 pdfs, where one has form elements and the other does not; the "check box" form element overwrites any text that is present.  

Is there a workaround for this?

The example below shows the text "blah" overlapped by check box element.
![check box form element overlap text](https://cloud.githubusercontent.com/assets/2420259/2550332/0326a054-b682-11e3-9034-4c5197a410dd.PNG)

**Comment by MartinThoma** [comment]
@Rob1080 I know it's been a long time. Do you happen to have an example (code + PDF) that shows the issue with the latest PyPDF2 version? Can you create one?

**Comment by MartinThoma** [comment]
I'm uncertain if this really is an issue. Without example files, I don't think we can work on it.

**Comment by amitkprimo** [comment]
@Rob1080 @mstamy2 @mstamy2 @rrthomas @avm 
// Here is the code of two PDFs merged on one page (overlapping) In Node js

const pdftk = require("node-pdftk");
const fs = require("fs");
const path = require("path");

const PdfController = {
  pdf: async (req, res) => {
    try {
      const pdfFile1Path =
        "/controllers/blank_GS_P5-PED08.pdf";
      const pdfFile2Path =
        "/controllers/content_GS_P5-PED08.pdf";
      const outputFilePath =
        "/controllers/merged_GS_P5-PED08.pdf";

      // Set a temporary directory where your Node.js process has write 
      // permissions using the tmpDir option
      const tmpDir = "/tmp"; // Change '/tmp' to an appropriate directory

      // Read the input PDF files
      const pdfFile1Buffer = fs.readFileSync(pdfFile1Path);
      const pdfFile2Buffer = fs.readFileSync(pdfFile2Path);

      // Use the stamp operation to overlay pdfFile2 onto pdfFile1
      await pdftk
        .input(pdfFile1Buffer)
        .stamp(pdfFile2Buffer)
        .output(outputFilePath);

      // Send a success response with the output PDF path
      res
        .status(200)a
        .json({
          message: "PDFs merged successfully with overlap",
          outputPath: outputFilePath,
        });
    } catch (error) {
      console.error("Error merging PDFs:", error);
      res.status(500).json({ error: "An error occurred while merging PDFs" });
    }
  },
};

module.exports = PdfController;

**Comment by stefan6419846** [comment]
How is this relevant for *pypdf*? If ever, one probably wants to use a *pdftk* wrapper for Python, but as mentioned by @MartinThoma, this might be fixable in *pypdf* as well if we have a corresponding *pypdf* code snippet as well as the failing PDF.

**Comment by amitkprimo** [comment]
> How is this relevant for _pypdf_? If ever, one probably wants to use a _pdftk_ wrapper for Python, but as mentioned by @MartinThoma, this might be fixable in _pypdf_ as well if we have a corresponding _pypdf_ code snippet as well as the failing PDF.

You can use PyPDF2
I have Solutions also in Python 
here is code
import PyPDF2
def merge_pdfs_with_data_filling(primary_pdf_path, data_pdf_path, output_pdf_path):
    primary_pdf = PyPDF2.PdfReader(open(primary_pdf_path, "rb"))
    data_pdf = PyPDF2.PdfReader(open(data_pdf_path, "rb"))
    output_pdf = PyPDF2.PdfWriter()

    num_pages = max(len(primary_pdf.pages), len(data_pdf.pages))

    for page_num in range(num_pages):
        primary_page = primary_pdf.pages[page_num] if page_num < len(primary_pdf.pages) else None
        data_page = data_pdf.pages[page_num] if page_num < len(data_pdf.pages) else None

        if primary_page and data_page:
            output_page = primary_page
            output_page.merge_page(data_page)  # Merge content from data_page into output_page
        elif primary_page:
            output_page = primary_page
        else:
            output_page = data_page

        output_pdf.add_page(output_page)

    with open(output_pdf_path, "wb") as output_file:
        output_pdf.write(output_file)

# Paths to the primary PDF, data PDF, and output PDF
primary_pdf_path = "blank_GS_P5-PED08.pdf"
data_pdf_path = "content_GS_P5-PED08.pdf"
output_pdf_path = "merged_GS_P5-PED08.pdf"

# Merge PDFs with data filling
merge_pdfs_with_data_filling(primary_pdf_path, data_pdf_path, output_pdf_path)
print(f"PDFs merged and filled with data saved as '{output_pdf_path}'.")

**Comment by rrthomas** [comment]
@amitkprimo please don't tag a bunch of people on an issue like this, especially people like me who have nothing to do with the issue and aren't even project maintainers!

**Comment by MartinThoma** [comment]
@amitkprimo I don't understand what you're trying to tell us. Is there a problem? Why do you paste JavaScript code in here? How is it related to this issue?

**Comment by amitkprimo** [comment]
> @amitkprimo I don't understand what you're trying to tell us. Is there a problem? Why do you paste JavaScript code in here? How is it related to this issue?

I just explained with code how to merge two PDFs into one page in Python or Node. I'm trying to find a solution, and I found it, so I thought it might help other people. If you don't like it, please ignore it.

**Comment by rrthomas** [comment]
@amitkprimo, what you wrote here could be a good Stack Exchange question and answer; if you post it there, it's much more likely to be found by people looking to solve the same problem.
