### ISSUE TITLE
'PdfReadWarning: incorrect startxref pointer' logs when no issue is found

### ISSUE THREAD

**Issue by jessj52** [py-pdf/PyPDF2#852]
Hello! I noticed a new-to-me `PdfReadWarning` warning this afternoon after upgrading PyPDF2 (version 1.27.10):
`PdfReadWarning: incorrect startxref pointer(0) [_reader.py:938]` ([source](https://github.com/py-pdf/PyPDF2/blob/main/PyPDF2/_reader.py#L939))

I tested with my own PDFs, and also the files from PDF_Samples in this repo. This warning seems to log on every PDF I attempt to read via:

```python
from PyPDF2 import PdfFileReader
pdf_path = 'some-path/file.pdf'
with open(pdf_path, "rb") as pdf:
  pdf_reader = PdfFileReader(pdf)
```

It looks like the value being returned by `_get_xref_issues()` is 0, but there's a comment at the top of this method that says [a return value of 0 means no issues were found](https://github.com/py-pdf/PyPDF2/blob/def7a629ad4e1341dfdd68f6c7f56c111f1ee5c6/PyPDF2/_reader.py#L1158). I haven't noticed any other issues (my script actually still runs just fine!), so I think it's just an over-zealous warning.

**Comment by MT-Cash** [comment]
Uh, damn, you're right: https://github.com/py-pdf/PyPDF2/commit/fd775d34d9ccf8f77596ca9e82944c869901ac0f

The fix is rather easy: wrap the block with `if xref_issue_nr != 0`. I'll add the fix + deploy when I have my lunch break (in ~5 hours)

**Comment by MartinThoma** [comment]
I needed to run a couple of tests at work which meant that I had 5 minutes in which I couldn't really do anything else :smile: 

The fix was merged + a new release was deployed. Please let me know if the issue is fixed :-)

**Comment by jessj52** [comment]
Looks good to me! Thank you!
