### ISSUE TITLE
wx.lib.pdfviewer -  fails on import - regression error - cross project error

### ISSUE THREAD

**Issue by johns1c** [py-pdf/PyPDF2#860]
## Issue 

My viewer which is based on  WXPython  wx,lib.pdfviewer fails when tying to import  ContentStream and PageObject.  I have just looked at the github original and the  imports  are the same.  I can change my code but the issue with the original remains.

The code reads
```
from PyPDF2.pdf import ContentStream, PageObject
```

## Environment

Python 3 
wxPython Phoenix

##  Code

just run the  wxPython (Phoenix) demo 

[(https://github.com/wxWidgets/Phoenix/blob/master/demo/PDFViewer.py)]

**Comment by MartinThoma** [comment]
I cannot reproduce it:

```
>>> from PyPDF2.pdf import ContentStream, PageObject
>>> import PyPDF2
>>> PyPDF2.__version__
'1.27.12'
```

Which PyPDF version do you use? (And why didn't you simply execute the example from the bug template?)

**Comment by johns1c** [comment]
Sorry,  

I set up a new VENV specifically and used PIP to install PyPDF2 and WX but something must have gone wrong  because I have just repeated it and it works.   I must admit that I was in a bit of a hurry because my  wife wants me packed for the holiday

Chris

Sent from Mail for Windows

**Comment by johns1c** [comment]
No fault - user error

**Comment by MartinThoma** [comment]
Haha, happens to the best 😁 have a great and relaxing vacation! 🌴🌞

**Comment by johns1c** [comment]
Got it!  I had a drive mapped to the directory one above an old PyPdf2 directory and python was bringing pdf from there

Chris

Chris (from my iThingy
