### ISSUE TITLE
Unify warning types

### ISSUE THREAD

**Issue by MasterOdin** [py-pdf/PyPDF2#912]
For deprecated functions, they issue warnings with two different styles, one using `UserWarning` and the other `PendingDeprecationWarning`. For example:

https://github.com/py-pdf/PyPDF2/blob/24993292fcf65353e4494580b4ca76055ff0589d/PyPDF2/_page.py#L481-L483

https://github.com/py-pdf/PyPDF2/blob/24993292fcf65353e4494580b4ca76055ff0589d/PyPDF2/_page.py#L638-L643

I'm assuming any issuing `UserWarning` should be modified to use `PendingDeprecationWarning`? Just wanted to confirm intent before making a PR for it.

**Comment by MartinThoma** [comment]
Yes, exactly. All user warnings for deprecations were not on purpose. I just forgot to add the parameter

**Comment by MartinThoma** [comment]
@MasterOdin Was this issue solved (with https://github.com/py-pdf/PyPDF2/pull/928 ) ?

**Comment by MasterOdin** [comment]
Yup
