### ISSUE TITLE
Error: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by barchen1** [py-pdf/PyPDF2#925]
## Code + PDF

I got the error for [1.pdf](https://github.com/py-pdf/PyPDF2/files/8796328/1.pdf) :

```python
from PyPDF2 import PdfReader
from PyPDF2.generic import ArrayObject

reader = PdfReader("1.pdf")

for page_sliced in reader.pages:
    page_object = page_sliced.get_object()

    # Extracts the PDF's Annots (Annotations and Commenting):
    annots = page_object.get("/Annots")
    if annots:
        if not isinstance(annots, ArrayObject):
            annots = [annots]

        for annot in annots:
            annot_objects = annot.get_object()

```

And I get an error in `annot.getObject()` in the `generic.py` file when It tries to convert to int an empty byte.
![Screen Shot 2022-05-29 at 16 35 37](https://user-images.githubusercontent.com/54398957/170937975-4a094d0c-657a-4c53-9163-8a9ff848d468.png)

Need to add a check that the value is not empty before converting it to an integer.

## Environment

This occurs in the latest version of PyPDF2 (current master) with the following traceback:

```
Traceback (most recent call last):
  File "foo.py", line 16, in <module>
    annot_objects = annot.get_object()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 236, in get_object
    return self.pdf.get_object(self).get_object()
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 1099, in get_object
    retval = self._get_object_from_stream(indirect_reference)  # type: ignore
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/_reader.py", line 1069, in _get_object_from_stream
    obj = read_object(stream_data, self)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 1365, in read_object
    return NumberObject.read_from_stream(stream)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 386, in read_from_stream
    return NumberObject(num)
  File "/home/moose/Github/py-pdf/PyPDF2/PyPDF2/generic.py", line 356, in __new__
    val = int(value)
ValueError: invalid literal for int() with base 10: b''
```

**Comment by MartinThoma** [comment]
@barchen1 Pleae use the issue template:

1. What environment (system) are you using?
2. Which Python version do you have?
3. Which PyPDF2 version do you use?

**Comment by MartinThoma** [comment]
But very nice that you shared the PDF :heart:

**Comment by barchen1** [comment]
@MartinThoma Please let me know if you need more info from me

**Comment by pubpub-zz** [comment]
@MartinThoma,
I'm on it. fix coming soon

**Comment by MartinThoma** [comment]
You rock, @pubpub-zz!

I would like to highlight your contributions in the 2.1 release. Is there a website (linkedin / github / Twitter) you would like me to link to? Do you want to stay anonymous or would you like me to use your real name?

**Comment by MartinThoma** [comment]
( info@martin-thoma.de if you want to communicate privately)

**Comment by pubpub-zz** [comment]
@barchen1,
for copyright reason, we would like to use for the automatic non-regression test a link to the original document. The problem is very tricky to reproduce... and this will ease release of the change

**Comment by MartinThoma** [comment]
@pubpub-zz You could use the download-solution ( https://github.com/py-pdf/PyPDF2/files/8796328/1.pdf ). This way the actual file was never part of the repository (although it looks like it in the URL).

**Comment by MartinThoma** [comment]
@barchen1 If you have the copyright in the uploaded file, please let us know. Then we can add it as a test case to the repository to ensure that the issue does not appear again.

It is fixed, but I haven't created a release so far. I will make a release on Monday.

**Comment by barchen1** [comment]
@MartinThoma Did you created a release with the fix?

**Comment by MartinThoma** [comment]
Yes! #932 was part of the 2.1.0 release on 2022-06-06 :-)
