### ISSUE TITLE
Problem with closing PDF file saved by PyPDF2

### ISSUE THREAD

**Issue by Kaemer1645** [py-pdf/PyPDF2#963]
I'm create PDF file using PyPDF2. After that when I'm oppening this file with Adobe Acrobat and I would like to close it. The window appears with messege like "Would you like to save this file?"
I haven't got this problem with previous versions of PyPDF2.

## Environment

```bash
$ python -m platform
Windows-10-10.0.19044-SP0

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.1.0
```

## Code

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfFileWriter
import os

c_dir = os.getcwd()
path = os.path.join(c_dir,'test_2.pdf')
pdf = PdfFileWriter()
pdf.addBlankPage(100, 100)
pdf.write(open(path, 'wb'))
```

## PDF

[test_2.pdf](https://github.com/py-pdf/PyPDF2/files/8868340/test_2.pdf)

**Comment by MartinThoma** [comment]
Thank you for reporting the issue :pray: 

I don't quite understand: Which versions work and which are broken?

**Comment by MartinThoma** [comment]
Please note that `pdf.write(open(path, 'wb'))` is not good style. This leaves the file handle open. Instead, you should write:

```python
with open(path, "wb") as fh:
    pdf.write(fh)
```

After the with-block, the file handle `fh` will be closed automatically by Python. I'm uncertain if this is related.

**Comment by geoxyIT** [comment]
I know use with style is more pythonic but using "with" it didn't work too.

The versions which work is 
pypdf==1.27.2
pypdf==1.27.3
pypdf==1.27.4
pypdf==1.27.5
but every above this versions like 1.27.6 1.27.8... didn't work.

## Code

```python
# from PyPDF2 import PdfFileWriter
import os

c_dir = os.getcwd()
path = os.path.join(c_dir, 'test_10.pdf')
pdf = PdfFileWriter()
pdf.addBlankPage(100, 100)
file = open(path, 'wb')
pdf.write(file)
file.close()

pdf2 = PdfFileWriter()
path2 = os.path.join(c_dir, 'test_11.pdf')
with open(path2, "wb") as fh:
    pdf2.addBlankPage(100, 100)
    pdf2.write(fh)
```

Both work wrong on version >= 1.27.6

**Comment by Kaemer1645** [comment]
I know use with style is more pythonic but using "with" it didn't work too.

The versions which work is 
pypdf==1.27.2
pypdf==1.27.3
pypdf==1.27.4
pypdf==1.27.5
but every above this versions like 1.27.6 1.27.8... didn't work.

## Code

```python
# from PyPDF2 import PdfFileWriter
import os

c_dir = os.getcwd()
path = os.path.join(c_dir, 'test_10.pdf')
pdf = PdfFileWriter()
pdf.addBlankPage(100, 100)
file = open(path, 'wb')
pdf.write(file)
file.close()

pdf2 = PdfFileWriter()
path2 = os.path.join(c_dir, 'test_11.pdf')
with open(path2, "wb") as fh:
    pdf2.addBlankPage(100, 100)
    pdf2.write(fh)
```

Both work wrong on version >= 1.27.6

**Comment by pubpub-zz** [comment]
@Kaemer1645 , 
Can you try to see what is the result of analysis of the generated pdf to have a better understanding (ex not tried)
https://www.datalogics.com/products/pdf-tools/pdf-checker/

**Comment by Kaemer1645** [comment]
[report_1.27.6.txt](https://github.com/py-pdf/PyPDF2/files/8870992/report_1.27.6.txt)
[report_1.27.5.txt](https://github.com/py-pdf/PyPDF2/files/8870993/report_1.27.5.txt)

**Comment by pubpub-zz** [comment]
@Kaemer1645,
may I bother you a little more :  can you post the output with version 1.27.5 ? thx

**Comment by pubpub-zz** [comment]
@MartinThoma ,
Looking carefully to the generated file, I can see an AcroForm field where Fields(identified as mandatory) is missing. When I manually delete the field (not the object which remains unlinked to the root object after file writing), the pdf file did not asked for saving at closure. can you double check and investigate about any change about this field ?

**Comment by Kaemer1645** [comment]
@pubpub-zz of course I can
[test_1_27_6.pdf](https://github.com/py-pdf/PyPDF2/files/8876285/test_1_27_6.pdf)
[test_1_27_5.pdf](https://github.com/py-pdf/PyPDF2/files/8876286/test_1_27_5.pdf)

**Comment by MartinThoma** [comment]
@pubpub-zz I didn't have the time to look into that since yesterday, but what popped into my mind is #414 (introduced in 1.27.6)

**Comment by mawr-san** [comment]
Hi there, 
Got the exact same problem after updating an old version of PyPDF2.
Here my actual versions : 
```
PS E:\> python --version
Python 3.10.5
PS E:\> python -m platform
Windows-10-10.0.19044-SP0
PS E:\> python -c "import PyPDF2;print(PyPDF2.__version__)"
2.1.0
```

**Comment by pubpub-zz** [comment]
The issue comes from #412 (refer to discussion #355)

when `/NeedAppearances` is set to true, it asks for saving

My current proposal would  be to remove call to `set_need_appearances_writer()` in `__init__()` and just call it in `update_page_form_field_values()`

@MartinThoma , @MasterOdin  your opinion  ?

**Comment by pubpub-zz** [comment]
@Kaemer1645, if you want for the moment, you may add
```
from PyPDF2.generic import NameObject,BooleanObject
pdf._root_object["/AcroForm"][NameObject("/NeedAppearances")] = BooleanObject(False)
```

before calling `pdf.write(...)`

**Comment by MartinThoma** [comment]
@mawr-san / @Kaemer1645 Would you please check if the following PDF also has the mentioned issue:

[potentially-solved.pdf](https://github.com/py-pdf/PyPDF2/files/8882226/potentially-solved.pdf)

If the bug doesn't appear with that PDF, we can merge https://github.com/py-pdf/PyPDF2/pull/970 (going with the fix proposed by @pubpub-zz )

**Comment by geoxyIT** [comment]
@MartinThoma everything works fine!

**Comment by Kaemer1645** [comment]
@MartinThoma everything works fine!

**Comment by MartinThoma** [comment]
Nice! Thanks for confirming!

The fix is now in `main` and I'll create a new release some time tomorrow :-)
