### ISSUE TITLE
File causes loop method call between functions `extract_xform_text` and `_extract_text` 

### ISSUE THREAD

**Issue by VBobCat** [py-pdf/PyPDF2#966]
While reading a certain file, my program exits without any exception being raised.

I investigated the issue and it seems the cause is functions `extract_xform_text` and `_extract_text` in [_page.py](https://github.com/py-pdf/PyPDF2/blob/main/PyPDF2/_page.py) call each other in a neverending loop. 

## Environment

Which environment were you using when you encountered the problem?

```
Python 3.10.5
Windows-10-10.0.19044-SP0
PyPDF2 2.1.0
```

## Code

This is a minimal, complete example that shows the issue:

My code (that uses PyPDF2) is this:

```
def pdf_to_text(filename):
    with open(filename, 'rb') as pdf_file_object:
        # try:
            reader = PyPDF2.PdfFileReader(pdf_file_object, strict=False)
            num_pages = reader.numPages
            if num_pages:
                page_texts = []
                for i in range(num_pages):
                    page = reader.getPage(i)
                    page_text = page.extract_text()
                    page_texts.append(page_text)
                return ' '.join(page_texts)
```

I put a breakpoint in `extract_xform_text` and it receives these three parameters (`self`, `xform`, `space_width`):
```
{
    'self': {
        '/Contents': IndirectObject(2, 0),
        '/CropBox': [0, 0, 595.56, 842.04],
        '/Group': {
            '/CS': '/DeviceRGB',
            '/S': '/Transparency',
            '/Type': '/Group'
        },
        '/MediaBox': [0, 0, 595.56, 842.04], '/Parent': IndirectObject(34, 0),
        '/Resources': {
            '/ExtGState': {
                '/GS0': IndirectObject(14, 0)
            },
            '/Font': {
                '/TT0': IndirectObject(54, 0),
                '/TT1': IndirectObject(57, 0)
            },
            '/ProcSet': ['/PDF', '/Text'],
            '/XObject': {
                '/Fm0': IndirectObject(7, 0)
            }
        },
        '/Rotate': 0,
        '/StructParents': 1,
        '/Tabs': '/S',
        '/Type': '/Page'
    },
    'xform': {
        '/ADBE_FillSign': {
            '/Subtype': '/page',
            '/Type': '/FillSignData'
        },
        '/BBox': [195.809, 527.097, 407.639, 553.999], 
        '/FormType': 1, 
        '/Matrix': [1, 0, 0, 1, 0, 0],
        '/Resources': {
            '/XObject': {
                '/Fm0': IndirectObject(6, 0)
            }
        }, 
        '/Subtype': '/Form', 
        '/Type': '/XObject'
    },
    'space_width': 200.0
}

```

## PDF

I am sorry but I'm unable to share the very PDF file, because it contains sensitive information.

**Comment by pubpub-zz** [comment]
@VBobCat 
To try to de-sensibilize the information, can you try to just cut off the page. if still not possible can you use `_debug_for_extract()` to extract the document structure (remove the TJ/Tj will remove the text)

**Comment by MartinThoma** [comment]
I think https://corpora.tika.apache.org/base/docs/govdocs1/998/998167.pdf might fall into the same issue

**Comment by pubpub-zz** [comment]
[ https://corpora.tika.apache.org/base/docs/govdocs1/998/998167.pdf ](https://github.com/py-pdf/PyPDF2/files/8884493/998167.pdf)
is a good sample I think the issue is because of we are looking for a xobject within the xobject with the same name. I was not looking in the good place :)

**Comment by MartinThoma** [comment]
I'm rather certain that the issue was solved. Please let us know if that is not the case!
