### ISSUE TITLE
ENV : clarification about building

### ISSUE THREAD

**Issue by pubpub-zz** [py-pdf/PyPDF2#972]
@MartinThoma,
To prevent too many cosmetic commits can you please re-clarify what are the command line parameters and config file used during generation.
Also, do you have some reference/recommendation about codevod to propose the best coverage : I was expecting more pdf input files to cover coverage, but not sure it's working

**Comment by pubpub-zz** [comment]
converted to discussion

**Comment by MartinThoma** [comment]
Sure!

The simplest stylistic changes I make are done be [`pre-commit`](https://pre-commit.com/). You can do those automatically with every commit by running once

```
pip install pre-commit

# Within the PyPDF2 git root folder:
pre-commit install 

# it should show something like 'pre-commit installed at .git/hooks/pre-commit'
```

For existing PRs, you can run `pre-commit run --all`. Common changes are:

* Apply the black formatter
* Apply isort for sorting imports
* Ensure files end with a newline

**Comment by MartinThoma** [comment]
Simple, but not easily automatable:

* PEP8 naming: The flake8-plugin [`pep8-naming`](https://pypi.org/project/pep8-naming/) points out simple PEP8 issues, but we still have the functions/methods/parameters that got deprecated. So there are quite a lot of messages
* Private/public API: Keeping the public interface (anything that does not start with an underscore) small is desirable as we can easily change things. If we modify the behavior / name of anything of the public interface, we have to [go through the deprecation process](https://pypdf2.readthedocs.io/en/latest/dev/deprecations.html) to ensure we're not unexpectedly breaking other peoples code.

Complex:

* Code structure: I don't want functions / classes / modules to become too big. On the one hand, it makes them hard for me to understand. On the other hand, there might be more merge conflicts and the merge conflicts become more complicated.

**Comment by MartinThoma** [comment]
> do you have some reference/recommendation about codevod to propose the best coverage

On a more general note about testing: I'm currently downloading the Tika test dataset of 800,000 PDF files. Well, a part of it as my laptop doesn't have enough storage :sweat_smile: I plan to run simple operations over all of those files to ensure that we don't crash.

The other path I'm trying to go is to increase test coverage to 100% and kill all mutants found by the [mutmut](https://pypi.org/project/mutmut/) mutation tester ([intro to mutation testing](https://medium.com/analytics-vidhya/unit-testing-in-python-mutation-testing-7a70143180d8) if you're curious).

Increasing test coverage is typically also easier if you have smaller functions. Then you just test the function - you might not even need a PDF for that. Those test typically also run faster, but there is a higher risk that you're testing something that cannot happen / that the test itself is not so good. Mutation testing improves the quality of the tests.
